<?php

declare(strict_types=1);

namespace Qmdb\Modules\IdentityResolution\Infrastructure\Migration;

use Qmdb\Shared\Schema\Migration\Migration;
use Qmdb\Shared\Schema\Migration\MigrationId;
use Qmdb\Shared\Schema\Migration\MigrationStepId;
use Qmdb\Shared\Schema\Migration\SqlMigrationStep;

/**
 * Forward-only catalog extension.  The closed MySQL checks deliberately mirror
 * the in-process enums so a new identity-resolution action cannot silently
 * bypass the persisted security boundary.
 */
final readonly class ExtendIdentityResolutionSecurityCatalogMigration implements Migration
{
    public function id(): MigrationId
    {
        return new MigrationId('20260902050500_extend_identity_resolution_security_catalog');
    }

    public function description(): string
    {
        return 'Extend governed security catalog checks for private identity resolution.';
    }

    public function dependencies(): array
    {
        return [(new CreatePersonCanonicalAliasesMigration())->id()];
    }

    public function up(): array
    {
        return [
            new SqlMigrationStep(new MigrationStepId('001_extend_idempotency_operations'), 'Allow private identity-resolution idempotency operations.', <<<'SQL'
ALTER TABLE identity_idempotency_records DROP CHECK ck_identity_idempotency_operation,
 ADD CONSTRAINT ck_identity_idempotency_operation CHECK (operation IN (
 'ACCOUNT_REGISTRATION','EMAIL_VERIFICATION_RESEND','PASSWORD_RECOVERY_REQUEST','PASSWORD_RECOVERY_RESET',
 'PERSON_PROFILE_CREATE','PERSON_PROFILE_UPDATE','PERSON_ROLE_ACTIVATE','PERSON_ROLE_DEACTIVATE','MEMORIZER_PROGRESS_UPDATE','DEPENDENT_PROFILE_CREATE','DEPENDENT_PROFILE_UPDATE','GUARDIANSHIP_REVOKE',
 'ORGANIZATION_CREATE','ORGANIZATION_UPDATE','ORGANIZATION_RETIRE','ORGANIZATION_UNIT_CREATE','ORGANIZATION_UNIT_UPDATE','ORGANIZATION_UNIT_RETIRE',
 'ORGANIZATION_AFFILIATION_REQUEST','ORGANIZATION_AFFILIATION_ACCEPT','ORGANIZATION_AFFILIATION_DECLINE','ORGANIZATION_AFFILIATION_WITHDRAW','ORGANIZATION_AFFILIATION_ASSIGNMENTS_UPDATE','ORGANIZATION_AFFILIATION_SUSPEND','ORGANIZATION_AFFILIATION_RESUME','ORGANIZATION_AFFILIATION_END','ORGANIZATION_AFFILIATION_LEAVE',
 'PROFILE_CLAIM_PAIRING_CREATE','PROFILE_CLAIM_PAIRING_REVOKE','PROFILE_CLAIM_AUTHORIZE_GUARDIAN','PROFILE_CLAIM_AUTHORIZE_PLATFORM','PROFILE_CLAIM_ACCEPT','PROFILE_CLAIM_DECLINE','PROFILE_CLAIM_REVOKE','PROFILE_VERIFICATION_RECORD','PROFILE_VERIFICATION_REVOKE','PROFILE_DUPLICATE_REPORT','PROFILE_DUPLICATE_CONSENT','PROFILE_DUPLICATE_DISMISS','PROFILE_DUPLICATE_RESOLVE'
 ))
SQL),
            new SqlMigrationStep(new MigrationStepId('002_extend_step_up_actions'), 'Allow exact identity-resolution step-up actions.', <<<'SQL'
ALTER TABLE account_step_up_grants DROP CHECK ck_step_up_grants_action,
 ADD CONSTRAINT ck_step_up_grants_action CHECK (action IN (
 'MFA_ENROLL_TOTP','MFA_REGISTER_PASSKEY','MFA_ENABLE','MFA_DISABLE','MFA_REGENERATE_RECOVERY_CODES','MFA_REVOKE_TOTP','MFA_REVOKE_PASSKEY',
 'AUTHORIZATION_PLATFORM_ROLE_ASSIGN','AUTHORIZATION_PLATFORM_ROLE_REVOKE','AUTHORIZATION_WORKSPACE_ROLE_ASSIGN','AUTHORIZATION_WORKSPACE_ROLE_REVOKE',
 'TEMPORARY_PRIVILEGE_APPROVE','TEMPORARY_PRIVILEGE_ACTIVATE','TEMPORARY_PRIVILEGE_REVOKE','SUPPORT_ACCESS_PLATFORM_APPROVE','SUPPORT_ACCESS_WORKSPACE_APPROVE','SUPPORT_ACCESS_ACTIVATE','SUPPORT_ACCESS_REVOKE','SUPPORT_ACCESS_REVIEW','BREAK_GLASS_ACTIVATE','BREAK_GLASS_REVIEW',
 'ACCOUNT_SUSPEND','ACCOUNT_REACTIVATE','PERSON_PROFILE_SENSITIVE_UPDATE','DEPENDENT_PROFILE_CREATE','GUARDIANSHIP_REVOKE','ORGANIZATION_RETIRE','ORGANIZATION_UNIT_RETIRE',
 'ORGANIZATION_AFFILIATION_ACCEPT','ORGANIZATION_AFFILIATION_ACCEPT_LEADERSHIP','ORGANIZATION_AFFILIATION_SUSPEND','ORGANIZATION_AFFILIATION_RESUME','ORGANIZATION_AFFILIATION_END','ORGANIZATION_AFFILIATION_LEAVE','ORGANIZATION_LEADERSHIP_ASSIGN','ORGANIZATION_LEADERSHIP_REMOVE',
 'PROFILE_CLAIM_AUTHORIZE_GUARDIAN','PROFILE_CLAIM_AUTHORIZE_PLATFORM','PROFILE_CLAIM_ACCEPT','PROFILE_CLAIM_REVOKE','PROFILE_VERIFICATION_RECORD','PROFILE_VERIFICATION_REVOKE','PROFILE_DUPLICATE_REPORT','PROFILE_DUPLICATE_CONSENT','PROFILE_DUPLICATE_DISMISS','PROFILE_DUPLICATE_RESOLVE'
 ))
SQL),
            new SqlMigrationStep(new MigrationStepId('003_extend_rate_limit_scopes'), 'Allow identity-resolution rate-limit scopes.', <<<'SQL'
ALTER TABLE identity_rate_limit_buckets DROP CHECK ck_identity_rate_limit_scope,
 ADD CONSTRAINT ck_identity_rate_limit_scope CHECK (scope IN (
 'ACCOUNT_REGISTRATION_EMAIL','ACCOUNT_REGISTRATION_PEER','EMAIL_VERIFICATION_RESEND_EMAIL','EMAIL_VERIFICATION_RESEND_PEER','EMAIL_VERIFICATION_ATTEMPT','EMAIL_VERIFICATION_PEER','PASSWORD_AUTHENTICATION_EMAIL','PASSWORD_AUTHENTICATION_PEER','PASSWORD_RECOVERY_REQUEST_EMAIL','PASSWORD_RECOVERY_REQUEST_PEER','PASSWORD_RECOVERY_ATTEMPT','PASSWORD_RECOVERY_ATTEMPT_PEER','MFA_AUTHENTICATION_ACCOUNT','MFA_AUTHENTICATION_PEER','PASSKEY_AUTHENTICATION_PEER','STEP_UP_ACCOUNT','STEP_UP_PEER','PASSKEY_REGISTRATION_ACCOUNT','PRIVILEGED_ACCESS_REQUEST_ACCOUNT','PRIVILEGED_ACCESS_REQUEST_PEER','PRIVILEGED_ACCESS_APPROVAL_ACCOUNT','PRIVILEGED_ACCESS_ACTIVATION_ACCOUNT','BREAK_GLASS_ACTIVATION_ACCOUNT','BREAK_GLASS_ACTIVATION_PEER','ACCOUNT_STATE_OPERATION_ACCOUNT','ACCOUNT_STATE_OPERATION_PEER','PERSON_PROFILE_MUTATION_ACCOUNT','PERSON_PROFILE_MUTATION_PEER','DEPENDENT_PROFILE_CREATION_ACCOUNT','DEPENDENT_PROFILE_CREATION_PEER','ORGANIZATION_MUTATION_ACCOUNT','ORGANIZATION_MUTATION_PEER','ORGANIZATION_UNIT_MUTATION_ACCOUNT','ORGANIZATION_UNIT_MUTATION_PEER',
 'ORGANIZATION_AFFILIATION_REQUEST_ACCOUNT','ORGANIZATION_AFFILIATION_REQUEST_PEER','ORGANIZATION_AFFILIATION_RESPONSE_ACCOUNT','ORGANIZATION_AFFILIATION_RESPONSE_PEER','ORGANIZATION_AFFILIATION_MUTATION_ACCOUNT','ORGANIZATION_AFFILIATION_MUTATION_PEER',
 'PROFILE_CLAIM_PAIRING_ACCOUNT','PROFILE_CLAIM_PAIRING_PEER','PROFILE_CLAIM_AUTHORIZATION_ACCOUNT','PROFILE_CLAIM_AUTHORIZATION_PEER','PROFILE_CLAIM_REDEMPTION_ACCOUNT','PROFILE_CLAIM_REDEMPTION_PEER','PROFILE_DUPLICATE_REPORT_ACCOUNT','PROFILE_DUPLICATE_REPORT_PEER','PROFILE_DUPLICATE_MUTATION_ACCOUNT'
 ))
SQL),
            new SqlMigrationStep(new MigrationStepId('004_extend_notification_types'), 'Allow private identity-resolution notification intents.', <<<'SQL'
ALTER TABLE account_security_notifications DROP CHECK ck_security_notifications_type,
 ADD CONSTRAINT ck_security_notifications_type CHECK (notification_type IN (
 'PASSWORD_RESET_COMPLETED','MFA_ENABLED','MFA_DISABLED','TOTP_AUTHENTICATOR_ADDED','TOTP_AUTHENTICATOR_REMOVED','PASSKEY_ADDED','PASSKEY_REMOVED','RECOVERY_CODES_REGENERATED','RECOVERY_CODE_USED','PASSKEY_SUSPENDED','PLATFORM_ROLE_ASSIGNED','PLATFORM_ROLE_REVOKED','WORKSPACE_ROLE_ASSIGNED','WORKSPACE_ROLE_REVOKED','TEMPORARY_PRIVILEGE_REQUESTED','TEMPORARY_PRIVILEGE_APPROVED','TEMPORARY_PRIVILEGE_REJECTED','TEMPORARY_PRIVILEGE_ACTIVATED','TEMPORARY_PRIVILEGE_REVOKED','TEMPORARY_PRIVILEGE_EXPIRED','SUPPORT_ACCESS_REQUESTED','SUPPORT_ACCESS_PARTIALLY_APPROVED','SUPPORT_ACCESS_APPROVED','SUPPORT_ACCESS_ACTIVATED','SUPPORT_ACCESS_ENDED','SUPPORT_ACCESS_REVOKED','SUPPORT_ACCESS_REVIEW_REQUIRED','SUPPORT_ACCESS_REVIEW_OVERDUE','SUPPORT_ACCESS_REVIEW_COMPLETED','BREAK_GLASS_ACTIVATED','BREAK_GLASS_ENDED','BREAK_GLASS_EXPIRED','BREAK_GLASS_REVIEW_REQUIRED','BREAK_GLASS_REVIEW_OVERDUE','BREAK_GLASS_REVIEW_COMPLETED','ACCOUNT_SUSPENDED','ACCOUNT_REACTIVATED','PERSON_PROFILE_CREATED','PERSON_PROFILE_UPDATED','DEPENDENT_PROFILE_CREATED','GUARDIANSHIP_REVOKED',
 'ORGANIZATION_AFFILIATION_REQUESTED','ORGANIZATION_AFFILIATION_ACCEPTED','ORGANIZATION_AFFILIATION_DECLINED','ORGANIZATION_AFFILIATION_EXPIRED','ORGANIZATION_AFFILIATION_SUSPENDED','ORGANIZATION_AFFILIATION_RESUMED','ORGANIZATION_AFFILIATION_ENDED','ORGANIZATION_AFFILIATION_ASSIGNMENTS_CHANGED','ORGANIZATION_LEADERSHIP_CHANGED',
 'PROFILE_CLAIM_AUTHORIZED','PROFILE_CLAIM_ACCEPTED','PROFILE_CLAIM_DECLINED','PROFILE_CLAIM_REVOKED','PROFILE_CLAIM_EXPIRED','PROFILE_VERIFICATION_RECORDED','PROFILE_VERIFICATION_REVOKED','PROFILE_DUPLICATE_REPORTED','PROFILE_DUPLICATE_CONSENT_REQUIRED','PROFILE_DUPLICATE_CONSENT_DECLINED','PROFILE_DUPLICATE_RESOLVED','PROFILE_DUPLICATE_BLOCKED'
 ))
SQL),
            new SqlMigrationStep(new MigrationStepId('005_extend_audit_subject_kinds'), 'Allow identity-resolution audit subjects.', <<<'SQL'
ALTER TABLE security_audit_events DROP CHECK ck_security_audit_events_subject,
 ADD CONSTRAINT ck_security_audit_events_subject CHECK (subject_kind IN ('ACCOUNT','SESSION','DEVICE','ROLE_ASSIGNMENT','AUTHENTICATOR','RECOVERY_CODE_SET','PRIVILEGED_ACCESS','WORKSPACE','SECURITY_AUDIT','PERSON','PERSON_ROLE','GUARDIANSHIP','ORGANIZATION','ORGANIZATION_UNIT','ORGANIZATION_AFFILIATION','ORGANIZATION_AFFILIATION_ASSIGNMENT','PROFILE_CLAIM','PROFILE_VERIFICATION','PERSON_DUPLICATE_CASE','PERSON_ALIAS'))
SQL),
        ];
    }

    public function down(): array
    {
        return [];
    }

    public function reversible(): bool
    {
        return false;
    }
}
