<?php

declare(strict_types=1);

namespace Qmdb\Modules\RecordPassport\Infrastructure\Migration;

use Qmdb\Modules\CertificateIssuance\Infrastructure\Migration\CreateCertificateIssuanceMigration;
use Qmdb\Shared\Schema\Migration\Migration;
use Qmdb\Shared\Schema\Migration\MigrationId;
use Qmdb\Shared\Schema\Migration\MigrationStepId;
use Qmdb\Shared\Schema\Migration\SqlMigrationStep;

/** Person-private passport projections with explicitly revocable public shares. */
final readonly class CreateRecordPassportMigration implements Migration
{
    public function id(): MigrationId { return new MigrationId('20260915102000_create_record_passports'); }
    public function description(): string { return 'Create P8 private record passports, entries, consent, and public shares.'; }
    public function dependencies(): array { return [(new CreateCertificateIssuanceMigration())->id()]; }
    public function up(): array
    {
        return [
            new SqlMigrationStep(new MigrationStepId('001_passports'), 'Create one private current passport for each Person.', "CREATE TABLE record_passports (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, person_id BIGINT UNSIGNED NOT NULL, status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE', version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, archived_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_passport_public(public_id), UNIQUE KEY uq_p8_passport_person(person_id), KEY ix_p8_passport_status(status,id), CONSTRAINT fk_p8_passport_person FOREIGN KEY(person_id) REFERENCES people_persons(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_passport CHECK(status IN ('ACTIVE','ARCHIVED') AND version>=1 AND (status<>'ARCHIVED' OR archived_at IS NOT NULL))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('002_entries'), 'Create immutable certificate, result, and approved legacy passport entries.', "CREATE TABLE record_passport_entries (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, passport_id BIGINT UNSIGNED NOT NULL, source_workspace_id BIGINT UNSIGNED NULL, source_kind VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_public_id BINARY(16) NOT NULL, certificate_id BIGINT UNSIGNED NULL, result_publication_id BIGINT UNSIGNED NULL, legacy_record_id BIGINT UNSIGNED NULL, entry_manifest_canonical_json JSON NOT NULL, entry_sha256 BINARY(32) NOT NULL, occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_passport_entry_public(public_id), UNIQUE KEY uq_p8_passport_entry_source(passport_id,source_kind,source_public_id), KEY ix_p8_passport_entry_passport(passport_id,occurred_at,id), KEY ix_p8_passport_entry_workspace(source_workspace_id,id), CONSTRAINT fk_p8_passport_entry_passport FOREIGN KEY(passport_id) REFERENCES record_passports(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_passport_entry_workspace FOREIGN KEY(source_workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_passport_entry_certificate FOREIGN KEY(certificate_id) REFERENCES certificates(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_passport_entry_publication FOREIGN KEY(result_publication_id) REFERENCES competition_result_publications(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_passport_entry CHECK(source_kind IN ('CERTIFICATE','OFFICIAL_RESULT','LEGACY_RECORD')) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('003_events'), 'Create append-only passport events.', "CREATE TABLE record_passport_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, passport_id BIGINT UNSIGNED NOT NULL, event_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_type VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_account_id BIGINT UNSIGNED NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, correlation_id BINARY(16) NOT NULL, occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_passport_event_public(public_id), KEY ix_p8_passport_event(passport_id,id), CONSTRAINT fk_p8_passport_event_passport FOREIGN KEY(passport_id) REFERENCES record_passports(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_passport_event_actor FOREIGN KEY(actor_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_passport_event CHECK(event_type IN ('CREATED','ENTRY_ADDED','SHARE_GRANTED','SHARE_REVOKED','ARCHIVED') AND actor_type IN ('ACCOUNT','SYSTEM') AND ((actor_type='ACCOUNT' AND actor_account_id IS NOT NULL) OR (actor_type='SYSTEM' AND actor_account_id IS NULL)))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('004_consents'), 'Create append-only sharing consent evidence.', "CREATE TABLE record_passport_consents (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, passport_id BIGINT UNSIGNED NOT NULL, action VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_account_id BIGINT UNSIGNED NOT NULL, scope_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_passport_consent_public(public_id), KEY ix_p8_passport_consent(passport_id,id), CONSTRAINT fk_p8_passport_consent_passport FOREIGN KEY(passport_id) REFERENCES record_passports(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_passport_consent_actor FOREIGN KEY(actor_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_passport_consent CHECK(action IN ('GRANTED','REVOKED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('005_shares'), 'Create revocable opaque public passport shares.', "CREATE TABLE record_passport_shares (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, passport_id BIGINT UNSIGNED NOT NULL, share_code_hash BINARY(32) NOT NULL, share_code_fingerprint BINARY(16) NOT NULL, status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE', expires_at DATETIME(6) NULL, granted_by_account_id BIGINT UNSIGNED NOT NULL, revoked_by_account_id BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, revoked_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_passport_share_public(public_id), UNIQUE KEY uq_p8_passport_share_code(share_code_hash), KEY ix_p8_passport_share_active(status,expires_at,id), CONSTRAINT fk_p8_passport_share_passport FOREIGN KEY(passport_id) REFERENCES record_passports(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_passport_share_granter FOREIGN KEY(granted_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_passport_share_revoker FOREIGN KEY(revoked_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_passport_share CHECK(status IN ('ACTIVE','REVOKED','EXPIRED') AND (status<>'REVOKED' OR (revoked_at IS NOT NULL AND revoked_by_account_id IS NOT NULL)))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('006_share_entries'), 'Freeze each public-share entry projection.', "CREATE TABLE record_passport_share_entries (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, share_id BIGINT UNSIGNED NOT NULL, passport_entry_id BIGINT UNSIGNED NOT NULL, public_projection_canonical_json JSON NOT NULL, projection_sha256 BINARY(32) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_passport_share_entry(share_id,passport_entry_id), CONSTRAINT fk_p8_passport_share_entry_share FOREIGN KEY(share_id) REFERENCES record_passport_shares(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_passport_share_entry_entry FOREIGN KEY(passport_entry_id) REFERENCES record_passport_entries(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('007_events_no_update'), 'Prevent passport event mutation.', "CREATE TRIGGER trg_p8_passport_events_no_update BEFORE UPDATE ON record_passport_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Passport events are append-only'"),
            new SqlMigrationStep(new MigrationStepId('008_events_no_delete'), 'Prevent passport event deletion.', "CREATE TRIGGER trg_p8_passport_events_no_delete BEFORE DELETE ON record_passport_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Passport events are append-only'"),
            new SqlMigrationStep(new MigrationStepId('009_entries_no_update'), 'Prevent passport entry mutation.', "CREATE TRIGGER trg_p8_passport_entries_no_update BEFORE UPDATE ON record_passport_entries FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Passport entries are immutable'"),
            new SqlMigrationStep(new MigrationStepId('010_entries_no_delete'), 'Prevent passport entry deletion.', "CREATE TRIGGER trg_p8_passport_entries_no_delete BEFORE DELETE ON record_passport_entries FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Passport entries are immutable'"),
        ];
    }
    public function down(): array { return []; }
    public function reversible(): bool { return false; }
}
