<?php

declare(strict_types=1);

namespace Qmdb\Modules\SecurityAuthorization\Domain;

enum AuthorizationDecisionReason: string
{
    case ALLOWED = 'ALLOWED';
    case DENIED_UNKNOWN_PERMISSION = 'DENIED_UNKNOWN_PERMISSION';
    case DENIED_SCOPE_MISMATCH = 'DENIED_SCOPE_MISMATCH';
    case DENIED_ACCOUNT_NOT_ACTIVE = 'DENIED_ACCOUNT_NOT_ACTIVE';
    case DENIED_WORKSPACE_NOT_ACTIVE = 'DENIED_WORKSPACE_NOT_ACTIVE';
    case DENIED_MEMBERSHIP_NOT_ACTIVE = 'DENIED_MEMBERSHIP_NOT_ACTIVE';
    case DENIED_NO_ROLE_ASSIGNMENT = 'DENIED_NO_ROLE_ASSIGNMENT';
    case DENIED_ROLE_NOT_ACTIVE = 'DENIED_ROLE_NOT_ACTIVE';
    case DENIED_PERMISSION_NOT_ACTIVE = 'DENIED_PERMISSION_NOT_ACTIVE';
    case DENIED_INSUFFICIENT_ASSURANCE = 'DENIED_INSUFFICIENT_ASSURANCE';
    case DENIED_CATALOG_INCONSISTENCY = 'DENIED_CATALOG_INCONSISTENCY';
}
