<?php

declare(strict_types=1);

namespace Qmdb\Modules\SecurityAuthorization\Domain;

enum RoleAssignmentReasonCode: string
{
    case SECURITY_ADMINISTRATION = 'SECURITY_ADMINISTRATION';
    case SYSTEM_WORKSPACE_OWNER_INITIALIZATION = 'SYSTEM_WORKSPACE_OWNER_INITIALIZATION';
    case SYSTEM_PLATFORM_BOOTSTRAP = 'SYSTEM_PLATFORM_BOOTSTRAP';
    case SECURITY_RESPONSE = 'SECURITY_RESPONSE';
    case MEMBERSHIP_STATE_CHANGE = 'MEMBERSHIP_STATE_CHANGE';
    case ROLE_RETIRED = 'ROLE_RETIRED';
}
