<?php

declare(strict_types=1);

namespace Qmdb\Modules\TrustedArchive\Infrastructure\Migration;

use Qmdb\Modules\RecordPassport\Infrastructure\Migration\CreateRecordPassportMigration;
use Qmdb\Shared\Schema\Migration\Migration;
use Qmdb\Shared\Schema\Migration\MigrationId;
use Qmdb\Shared\Schema\Migration\MigrationStepId;
use Qmdb\Shared\Schema\Migration\SqlMigrationStep;

/** Workspace-owned append-only hash-chain archive. */
final readonly class CreateTrustedArchiveMigration implements Migration
{
    public function id(): MigrationId { return new MigrationId('20260915103000_create_trusted_archive'); }
    public function description(): string { return 'Create P8 trusted archive streams, records, artifacts, events, and holds.'; }
    public function dependencies(): array { return [(new CreateRecordPassportMigration())->id()]; }
    public function up(): array
    {
        return [
            new SqlMigrationStep(new MigrationStepId('001_streams'), 'Create workspace archive streams.', "CREATE TABLE trusted_archive_streams (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, stream_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, next_sequence BIGINT UNSIGNED NOT NULL DEFAULT 1, head_record_sha256 BINARY(32) NULL, status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE', version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, sealed_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_archive_stream_public(public_id), UNIQUE KEY uq_p8_archive_stream_code(workspace_id,stream_code), UNIQUE KEY uq_p8_archive_stream_workspace_id(workspace_id,id), CONSTRAINT fk_p8_archive_stream_workspace FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_archive_stream CHECK(next_sequence>=1 AND version>=1 AND status IN ('ACTIVE','SEALED','ARCHIVED') AND (status<>'SEALED' OR sealed_at IS NOT NULL))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('002_records'), 'Create immutable chained archive records.', "CREATE TABLE trusted_archive_records (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, stream_id BIGINT UNSIGNED NOT NULL, sequence_number BIGINT UNSIGNED NOT NULL, record_kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_public_id BINARY(16) NOT NULL, manifest_canonical_json JSON NOT NULL, manifest_sha256 BINARY(32) NOT NULL, previous_record_sha256 BINARY(32) NULL, record_sha256 BINARY(32) NOT NULL, status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PENDING', sealed_at DATETIME(6) NULL, supersedes_record_id BIGINT UNSIGNED NULL, created_by_account_id BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_archive_record_public(public_id), UNIQUE KEY uq_p8_archive_record_sequence(workspace_id,stream_id,sequence_number), UNIQUE KEY uq_p8_archive_record_hash(record_sha256), UNIQUE KEY uq_p8_archive_record_workspace_id(workspace_id,id), KEY ix_p8_archive_record_status(workspace_id,status,id), CONSTRAINT fk_p8_archive_record_stream FOREIGN KEY(workspace_id,stream_id) REFERENCES trusted_archive_streams(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_archive_record_supersedes FOREIGN KEY(workspace_id,supersedes_record_id) REFERENCES trusted_archive_records(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_archive_record_creator FOREIGN KEY(created_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_archive_record CHECK(sequence_number>=1 AND record_kind IN ('CERTIFICATE','PASSPORT_ENTRY','PUBLICATION','LEGACY_RECORD','MANUAL_GOVERNED') AND status IN ('PENDING','SEALED','SUPERSEDED') AND (status<>'SEALED' OR sealed_at IS NOT NULL))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('003_artifacts'), 'Create immutable archive artifact descriptors.', "CREATE TABLE trusted_archive_artifacts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, archive_record_id BIGINT UNSIGNED NOT NULL, artifact_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, storage_provider_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, storage_object_key VARCHAR(320) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, sha256 BINARY(32) NOT NULL, byte_size BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_archive_artifact_public(public_id), UNIQUE KEY uq_p8_archive_artifact_type(workspace_id,archive_record_id,artifact_type), CONSTRAINT fk_p8_archive_artifact_record FOREIGN KEY(workspace_id,archive_record_id) REFERENCES trusted_archive_records(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_archive_artifact CHECK(byte_size>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('004_events'), 'Create append-only archive evidence.', "CREATE TABLE trusted_archive_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, archive_record_id BIGINT UNSIGNED NOT NULL, event_type VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_type VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_account_id BIGINT UNSIGNED NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_archive_event_public(public_id), KEY ix_p8_archive_event(workspace_id,archive_record_id,id), CONSTRAINT fk_p8_archive_event_record FOREIGN KEY(workspace_id,archive_record_id) REFERENCES trusted_archive_records(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_archive_event_actor FOREIGN KEY(actor_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_archive_event CHECK(event_type IN ('APPENDED','SEALED','VERIFIED','RECONCILIATION_FAILED','SUPERSEDED','HOLD_PLACED','HOLD_RELEASED') AND actor_type IN ('ACCOUNT','SYSTEM') AND ((actor_type='ACCOUNT' AND actor_account_id IS NOT NULL) OR (actor_type='SYSTEM' AND actor_account_id IS NULL)))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('005_holds'), 'Create append-only governed archive holds.', "CREATE TABLE trusted_archive_holds (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, archive_record_id BIGINT UNSIGNED NOT NULL, action VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, hold_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_account_id BIGINT UNSIGNED NOT NULL, occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_archive_hold_public(public_id), KEY ix_p8_archive_hold(workspace_id,archive_record_id,id), CONSTRAINT fk_p8_archive_hold_record FOREIGN KEY(workspace_id,archive_record_id) REFERENCES trusted_archive_records(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_archive_hold_actor FOREIGN KEY(actor_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_archive_hold CHECK(action IN ('PLACED','RELEASED') AND hold_type IN ('LEGAL','SECURITY','INTEGRITY','OPERATIONAL','MANUAL_GOVERNED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('006_records_no_update'), 'Prevent archive record mutation.', "CREATE TRIGGER trg_p8_archive_records_no_update BEFORE UPDATE ON trusted_archive_records FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Trusted archive records are immutable'"),
            new SqlMigrationStep(new MigrationStepId('007_records_no_delete'), 'Prevent archive record deletion.', "CREATE TRIGGER trg_p8_archive_records_no_delete BEFORE DELETE ON trusted_archive_records FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Trusted archive records are immutable'"),
            new SqlMigrationStep(new MigrationStepId('008_events_no_update'), 'Prevent archive event mutation.', "CREATE TRIGGER trg_p8_archive_events_no_update BEFORE UPDATE ON trusted_archive_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Trusted archive events are append-only'"),
            new SqlMigrationStep(new MigrationStepId('009_events_no_delete'), 'Prevent archive event deletion.', "CREATE TRIGGER trg_p8_archive_events_no_delete BEFORE DELETE ON trusted_archive_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Trusted archive events are append-only'"),
        ];
    }
    public function down(): array { return []; }
    public function reversible(): bool { return false; }
}
