<?php

declare(strict_types=1);

namespace Qmdb\Modules\TrustedArchive\Infrastructure\Migration;

use Qmdb\Shared\Schema\Migration\Migration;
use Qmdb\Shared\Schema\Migration\MigrationId;
use Qmdb\Shared\Schema\Migration\MigrationStepId;
use Qmdb\Shared\Schema\Migration\SqlMigrationStep;

/** Staged, non-public legacy record import with immutable provenance. */
final readonly class CreateLegacyRecordImportMigration implements Migration
{
    public function id(): MigrationId { return new MigrationId('20260915104000_create_legacy_record_import'); }
    public function description(): string { return 'Create P8 staged legacy import, validation, approval, and immutable legacy records.'; }
    public function dependencies(): array { return [(new CreateTrustedArchiveMigration())->id()]; }
    public function up(): array
    {
        return [
            new SqlMigrationStep(new MigrationStepId('001_batches'), 'Create workspace-scoped legacy import batches.', "CREATE TABLE legacy_record_import_batches (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, source_label VARCHAR(160) NOT NULL, source_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_sha256 BINARY(32) NOT NULL, source_byte_size BIGINT UNSIGNED NOT NULL, status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'STAGED', validated_row_count INT UNSIGNED NOT NULL DEFAULT 0, accepted_row_count INT UNSIGNED NOT NULL DEFAULT 0, rejected_row_count INT UNSIGNED NOT NULL DEFAULT 0, submitted_by_account_id BIGINT UNSIGNED NOT NULL, approved_by_account_id BIGINT UNSIGNED NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, validated_at DATETIME(6) NULL, approved_at DATETIME(6) NULL, processed_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_legacy_batch_public(public_id), UNIQUE KEY uq_p8_legacy_batch_source(workspace_id,source_sha256), UNIQUE KEY uq_p8_legacy_batch_workspace_id(workspace_id,id), KEY ix_p8_legacy_batch_queue(workspace_id,status,created_at,id), CONSTRAINT fk_p8_legacy_batch_workspace FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_batch_submitter FOREIGN KEY(submitted_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_batch_approver FOREIGN KEY(approved_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_legacy_batch CHECK(source_type IN ('CSV','JSON','MANUAL_GOVERNED') AND source_byte_size>=1 AND version>=1 AND status IN ('STAGED','VALIDATED','APPROVED','PROCESSING','COMPLETED','REJECTED','FAILED') AND (status<>'APPROVED' OR (approved_at IS NOT NULL AND approved_by_account_id IS NOT NULL))) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('002_rows'), 'Create staged and validated legacy source rows.', "CREATE TABLE legacy_record_import_rows (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, batch_id BIGINT UNSIGNED NOT NULL, source_row_number INT UNSIGNED NOT NULL, source_identity_fingerprint BINARY(32) NOT NULL, raw_payload_ciphertext MEDIUMBLOB NOT NULL, payload_key_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, payload_sha256 BINARY(32) NOT NULL, validation_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PENDING', validation_codes_canonical_json JSON NOT NULL, matched_person_id BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, validated_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_legacy_row_public(public_id), UNIQUE KEY uq_p8_legacy_row_number(workspace_id,batch_id,source_row_number), KEY ix_p8_legacy_row_validate(workspace_id,batch_id,validation_status,id), CONSTRAINT fk_p8_legacy_row_batch FOREIGN KEY(workspace_id,batch_id) REFERENCES legacy_record_import_batches(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_row_person FOREIGN KEY(matched_person_id) REFERENCES people_persons(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_legacy_row CHECK(source_row_number>=1 AND validation_status IN ('PENDING','VALID','REJECTED','DUPLICATE','AMBIGUOUS')) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('003_records'), 'Create approved immutable non-public legacy records.', "CREATE TABLE legacy_records (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, import_batch_id BIGINT UNSIGNED NOT NULL, import_row_id BIGINT UNSIGNED NOT NULL, person_id BIGINT UNSIGNED NULL, record_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'APPROVED', provenance_canonical_json JSON NOT NULL, provenance_sha256 BINARY(32) NOT NULL, supersedes_legacy_record_id BIGINT UNSIGNED NULL, superseded_by_legacy_record_id BIGINT UNSIGNED NULL, approved_by_account_id BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, approved_at DATETIME(6) NOT NULL, superseded_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_legacy_record_public(public_id), UNIQUE KEY uq_p8_legacy_record_source(workspace_id,import_row_id), UNIQUE KEY uq_p8_legacy_record_workspace_id(workspace_id,id), KEY ix_p8_legacy_record_person(person_id,status,id), CONSTRAINT fk_p8_legacy_record_batch FOREIGN KEY(workspace_id,import_batch_id) REFERENCES legacy_record_import_batches(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_record_row FOREIGN KEY(import_row_id) REFERENCES legacy_record_import_rows(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_record_person FOREIGN KEY(person_id) REFERENCES people_persons(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_record_supersedes FOREIGN KEY(workspace_id,supersedes_legacy_record_id) REFERENCES legacy_records(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_record_superseded_by FOREIGN KEY(workspace_id,superseded_by_legacy_record_id) REFERENCES legacy_records(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_record_approver FOREIGN KEY(approved_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_legacy_record CHECK(record_type IN ('CERTIFICATE','RESULT','RECOGNITION','OTHER_APPROVED') AND status IN ('APPROVED','SUPERSEDED','REJECTED') AND (status<>'SUPERSEDED' OR (superseded_at IS NOT NULL AND superseded_by_legacy_record_id IS NOT NULL))) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('004_events'), 'Create append-only legacy import lifecycle evidence.', "CREATE TABLE legacy_record_import_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, batch_id BIGINT UNSIGNED NOT NULL, event_type VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_type VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_account_id BIGINT UNSIGNED NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, safe_counts_canonical_json JSON NULL, occurred_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p8_legacy_event_public(public_id), KEY ix_p8_legacy_event(workspace_id,batch_id,id), CONSTRAINT fk_p8_legacy_event_batch FOREIGN KEY(workspace_id,batch_id) REFERENCES legacy_record_import_batches(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p8_legacy_event_actor FOREIGN KEY(actor_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p8_legacy_event CHECK(event_type IN ('STAGED','VALIDATED','APPROVED','PROCESSING','COMPLETED','REJECTED','FAILED') AND actor_type IN ('ACCOUNT','SYSTEM') AND ((actor_type='ACCOUNT' AND actor_account_id IS NOT NULL) OR (actor_type='SYSTEM' AND actor_account_id IS NULL)))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            new SqlMigrationStep(new MigrationStepId('005_passport_legacy_fk'), 'Link immutable passport entries to approved legacy records.', 'ALTER TABLE record_passport_entries ADD CONSTRAINT fk_p8_passport_entry_legacy FOREIGN KEY(legacy_record_id) REFERENCES legacy_records(id) ON DELETE RESTRICT ON UPDATE RESTRICT'),
            new SqlMigrationStep(new MigrationStepId('006_events_no_update'), 'Prevent legacy import event mutation.', "CREATE TRIGGER trg_p8_legacy_events_no_update BEFORE UPDATE ON legacy_record_import_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Legacy import events are append-only'"),
            new SqlMigrationStep(new MigrationStepId('007_events_no_delete'), 'Prevent legacy import event deletion.', "CREATE TRIGGER trg_p8_legacy_events_no_delete BEFORE DELETE ON legacy_record_import_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Legacy import events are append-only'"),
            new SqlMigrationStep(new MigrationStepId('008_records_no_update'), 'Prevent legacy record mutation.', "CREATE TRIGGER trg_p8_legacy_records_no_update BEFORE UPDATE ON legacy_records FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Legacy records are immutable'"),
            new SqlMigrationStep(new MigrationStepId('009_records_no_delete'), 'Prevent legacy record deletion.', "CREATE TRIGGER trg_p8_legacy_records_no_delete BEFORE DELETE ON legacy_records FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Legacy records are immutable'"),
        ];
    }
    public function down(): array { return []; }
    public function reversible(): bool { return false; }
}
