<?php

declare(strict_types=1);

// phpcs:disable Generic.Files.LineLength.TooLong

use Qmdb\Shared\Http\Controller\LivenessController;
use Qmdb\Modules\IdentitySessions\Interface\Http\ApplicationReadinessController;
use Qmdb\Shared\Http\Controller\SystemAboutApiController;
use Qmdb\Shared\Http\Controller\SystemAboutPageController;
use Qmdb\Shared\Http\Controller\SystemHomeController;
use Qmdb\Shared\Http\Controller\SystemStatusPageController;
use Qmdb\Modules\IdentityAccess\Interface\Http\AccountRegistrationAcceptedController;
use Qmdb\Modules\IdentityAccess\Interface\Http\AccountRegistrationFormController;
use Qmdb\Modules\IdentityAccess\Interface\Http\AccountRegistrationSubmitController;
use Qmdb\Modules\IdentityAccess\Interface\Http\EmailVerificationCompletedController;
use Qmdb\Modules\IdentityAccess\Interface\Http\EmailVerificationFormController;
use Qmdb\Modules\IdentityAccess\Interface\Http\EmailVerificationResendFormController;
use Qmdb\Modules\IdentityAccess\Interface\Http\EmailVerificationResendSubmitController;
use Qmdb\Modules\IdentityAccess\Interface\Http\EmailVerificationSubmitController;
use Qmdb\Modules\IdentitySessions\Interface\Http\AccountSecurityController;
use Qmdb\Modules\IdentitySessions\Interface\Http\DeviceRevocationController;
use Qmdb\Modules\IdentitySessions\Interface\Http\LoginFormController;
use Qmdb\Modules\IdentitySessions\Interface\Http\LoginSubmitController;
use Qmdb\Modules\IdentitySessions\Interface\Http\LogoutController;
use Qmdb\Modules\IdentitySessions\Interface\Http\SessionRevocationController;
use Qmdb\Modules\IdentityRecovery\Interface\Http\PasswordRecoveryRequestAcceptedController;
use Qmdb\Modules\IdentityRecovery\Interface\Http\PasswordRecoveryRequestFormController;
use Qmdb\Modules\IdentityRecovery\Interface\Http\PasswordRecoveryRequestSubmitController;
use Qmdb\Modules\IdentityRecovery\Interface\Http\PasswordResetCompletedController;
use Qmdb\Modules\IdentityRecovery\Interface\Http\PasswordResetFormController;
use Qmdb\Modules\IdentityRecovery\Interface\Http\PasswordResetSubmitController;
use Qmdb\Modules\IdentityMultiFactor\Interface\Http\IdentityMultiFactorController;
use Qmdb\Modules\TenancyContext\Interface\Http\AccountWorkspacesController;
use Qmdb\Modules\TenancyContext\Interface\Http\CurrentWorkspaceController;
use Qmdb\Modules\TenancyContext\Interface\Http\WorkspaceClearController;
use Qmdb\Modules\TenancyContext\Interface\Http\WorkspaceSwitchController;
use Qmdb\Modules\SecurityPrivilegedAccess\Interface\Http\PrivilegedAccessController;
use Qmdb\Modules\IdentityAccountState\Interface\Http\AccountStateSecurityController;
use Qmdb\Modules\IdentityAccountState\Interface\Http\SecurityAuditViewerController;
use Qmdb\Modules\Geography\Interface\Http\GeographyChildrenLookupController;
use Qmdb\Modules\Geography\Interface\Http\NigeriaGeographyAreaController;
use Qmdb\Modules\Geography\Interface\Http\NigeriaGeographyDirectoryController;
use Qmdb\Modules\People\Interface\Http\PeopleProfilesController;
use Qmdb\Modules\Organizations\Interface\Http\OrganizationsRegistryController;
use Qmdb\Modules\OrganizationAffiliations\Interface\Http\OrganizationAffiliationsController;
use Qmdb\Modules\IdentityResolution\Interface\Http\PeopleIdentityResolutionController;
use Qmdb\Modules\QuranReferenceGovernance\Interface\Http\QuranReleaseGovernanceController;
use Qmdb\Modules\QuranReferenceGovernance\Interface\Http\QuranPublicReferenceController;
use Qmdb\Modules\QuranReferenceGovernance\Interface\Http\QuranSearchCorpusIntegrityController;
use Qmdb\Modules\CompetitionResults\Interface\Http\CompetitionP6WorkflowController;
use Qmdb\Modules\CompetitionResults\Interface\Http\CompetitionPublicResultsController;
use Qmdb\Modules\CompetitionLive\Interface\Http\CompetitionPublicLiveController;
use Qmdb\Modules\CompetitionLive\Interface\Http\CompetitionLiveSessionWorkflowController;
use Qmdb\Modules\CompetitionLive\Interface\Http\CompetitionLiveParticipantWorkflowController;
use Qmdb\Modules\CompetitionPublication\Interface\Http\CompetitionResultPublicationWorkflowController;
use Qmdb\Shared\Http\Routing\HttpMethod;
use Qmdb\Shared\Http\Routing\Route;
use Qmdb\Shared\Http\Routing\RouteCollection;
use Qmdb\Shared\Http\Routing\RoutePattern;

return static function (
    SystemHomeController $homeController,
    SystemAboutPageController $aboutPageController,
    SystemStatusPageController $statusPageController,
    SystemAboutApiController $aboutApiController,
    LivenessController $livenessController,
    ApplicationReadinessController $readinessController,
    AccountRegistrationFormController $registrationForm,
    AccountRegistrationSubmitController $registrationSubmit,
    AccountRegistrationAcceptedController $registrationAccepted,
    EmailVerificationResendFormController $resendForm,
    EmailVerificationResendSubmitController $resendSubmit,
    EmailVerificationFormController $verificationForm,
    EmailVerificationSubmitController $verificationSubmit,
    EmailVerificationCompletedController $verificationCompleted,
    LoginFormController $loginForm,
    LoginSubmitController $loginSubmit,
    LogoutController $logout,
    AccountSecurityController $accountSecurity,
    SessionRevocationController $sessionRevocation,
    DeviceRevocationController $deviceRevocation,
    PasswordRecoveryRequestFormController $recoveryRequestForm,
    PasswordRecoveryRequestSubmitController $recoveryRequestSubmit,
    PasswordRecoveryRequestAcceptedController $recoveryRequestAccepted,
    PasswordResetFormController $passwordResetForm,
    PasswordResetSubmitController $passwordResetSubmit,
    PasswordResetCompletedController $passwordResetCompleted,
    IdentityMultiFactorController $multiFactor,
    AccountWorkspacesController $accountWorkspaces,
    WorkspaceSwitchController $workspaceSwitch,
    WorkspaceClearController $workspaceClear,
    CurrentWorkspaceController $currentWorkspace,
    PrivilegedAccessController $privilegedAccess,
    AccountStateSecurityController $accountState,
    SecurityAuditViewerController $securityAudit,
    NigeriaGeographyDirectoryController $geographyDirectory,
    NigeriaGeographyAreaController $geographyArea,
    GeographyChildrenLookupController $geographyChildren,
    PeopleProfilesController $peopleProfiles,
    OrganizationsRegistryController $organizationsRegistry,
    OrganizationAffiliationsController $organizationAffiliations,
    PeopleIdentityResolutionController $identityResolution,
    QuranReleaseGovernanceController $quranReleaseGovernance,
    QuranPublicReferenceController $quranPublicReference,
    QuranSearchCorpusIntegrityController $quranSearchCorpusIntegrity,
    CompetitionP6WorkflowController $competitionP6Workflow,
    CompetitionPublicResultsController $competitionPublicResults,
    CompetitionPublicLiveController $competitionPublicLive,
    CompetitionLiveSessionWorkflowController $competitionLiveSessionWorkflow,
    CompetitionLiveParticipantWorkflowController $competitionLiveParticipantWorkflow,
    CompetitionResultPublicationWorkflowController $competitionResultPublicationWorkflow,
): RouteCollection {
    return new RouteCollection(
        new Route('system.home', [HttpMethod::GET], new RoutePattern('/'), $homeController),
        new Route('system.about.page', [HttpMethod::GET], new RoutePattern('/system/about'), $aboutPageController),
        new Route('system.status.page', [HttpMethod::GET], new RoutePattern('/system/status'), $statusPageController),
        new Route(
            'geography.nigeria.index',
            [HttpMethod::GET],
            new RoutePattern('/locations/nigeria'),
            $geographyDirectory,
        ),
        new Route(
            'geography.nigeria.area',
            [HttpMethod::GET],
            new RoutePattern('/locations/nigeria/{levelOneSlug}'),
            $geographyArea,
        ),
        new Route(
            'geography.lookup.children',
            [HttpMethod::GET],
            new RoutePattern('/lookups/geography/children'),
            $geographyChildren,
        ),
        new Route(
            'system.health.live',
            [HttpMethod::GET],
            new RoutePattern('/health/live'),
            $livenessController,
        ),
        new Route(
            'system.health.ready',
            [HttpMethod::GET],
            new RoutePattern('/health/ready'),
            $readinessController,
        ),
        new Route(
            'api.v1.system.about',
            [HttpMethod::GET],
            new RoutePattern('/api/v1/system/about'),
            $aboutApiController,
        ),
        new Route('account.registration.form', [HttpMethod::GET], new RoutePattern('/register'), $registrationForm),
        new Route(
            'account.registration.submit',
            [HttpMethod::POST],
            new RoutePattern('/register'),
            $registrationSubmit,
        ),
        new Route(
            'account.registration.accepted',
            [HttpMethod::GET],
            new RoutePattern('/register/accepted'),
            $registrationAccepted,
        ),
        new Route(
            'account.email_verification.resend.form',
            [HttpMethod::GET],
            new RoutePattern('/verify-email/resend'),
            $resendForm,
        ),
        new Route(
            'account.email_verification.resend.submit',
            [HttpMethod::POST],
            new RoutePattern('/verify-email/resend'),
            $resendSubmit,
        ),
        new Route(
            'account.email_verification.completed',
            [HttpMethod::GET],
            new RoutePattern('/verify-email/completed'),
            $verificationCompleted,
        ),
        new Route(
            'account.email_verification.form',
            [HttpMethod::GET],
            new RoutePattern('/verify-email/{challengeId}'),
            $verificationForm,
        ),
        new Route(
            'account.email_verification.submit',
            [HttpMethod::POST],
            new RoutePattern('/verify-email/{challengeId}'),
            $verificationSubmit,
        ),
        new Route('account.login.form', [HttpMethod::GET], new RoutePattern('/login'), $loginForm),
        new Route('account.login.submit', [HttpMethod::POST], new RoutePattern('/login'), $loginSubmit),
        new Route('account.logout', [HttpMethod::POST], new RoutePattern('/logout'), $logout),
        new Route(
            'account.workspaces.index',
            [HttpMethod::GET],
            new RoutePattern('/account/workspaces'),
            $accountWorkspaces,
        ),
        new Route(
            'account.workspaces.switch',
            [HttpMethod::POST],
            new RoutePattern('/account/workspaces/switch'),
            $workspaceSwitch,
        ),
        new Route(
            'account.workspaces.clear',
            [HttpMethod::POST],
            new RoutePattern('/account/workspaces/clear'),
            $workspaceClear,
        ),
        new Route('workspace.current', [HttpMethod::GET], new RoutePattern('/workspace'), $currentWorkspace),
        new Route('quran.public.home', [HttpMethod::GET], new RoutePattern('/quran'), $quranPublicReference),
        new Route('competition.public.live', [HttpMethod::GET], new RoutePattern('/competitions/{editionSlug}/live'), $competitionPublicLive),
        new Route('competition.public.live.snapshot', [HttpMethod::GET], new RoutePattern('/competitions/{editionSlug}/live/snapshot'), $competitionPublicLive),
        new Route('competition.public.live.stream', [HttpMethod::GET], new RoutePattern('/competitions/{editionSlug}/live/stream'), $competitionPublicLive),
        new Route('quran.public.surahs', [HttpMethod::GET], new RoutePattern('/quran/surahs'), $quranPublicReference),
        new Route('quran.public.surah', [HttpMethod::GET], new RoutePattern('/quran/surahs/{surahNumber}'), $quranPublicReference),
        new Route('quran.public.ayah', [HttpMethod::GET], new RoutePattern('/quran/surahs/{surahNumber}/ayahs/{ayahNumber}'), $quranPublicReference),
        new Route('quran.public.partition', [HttpMethod::GET], new RoutePattern('/quran/partitions/{type}/{partitionNumber}'), $quranPublicReference),
        new Route('quran.public.sajdahs', [HttpMethod::GET], new RoutePattern('/quran/sajdahs'), $quranPublicReference),
        new Route('quran.public.search', [HttpMethod::GET], new RoutePattern('/quran/search'), $quranPublicReference),
        new Route('platform.security.accounts.detail', [HttpMethod::GET], new RoutePattern('/platform/security/accounts/{accountId}'), $accountState),
        new Route('platform.quran.releases.index', [HttpMethod::GET], new RoutePattern('/platform/quran/releases'), $quranReleaseGovernance),
        new Route('platform.quran.releases.detail', [HttpMethod::GET], new RoutePattern('/platform/quran/releases/{releaseId}'), $quranReleaseGovernance),
        new Route('platform.quran.releases.stage', [HttpMethod::GET, HttpMethod::POST], new RoutePattern('/platform/quran/releases/{releaseId}/stage'), $quranReleaseGovernance),
        new Route('platform.quran.releases.validate', [HttpMethod::GET, HttpMethod::POST], new RoutePattern('/platform/quran/releases/{releaseId}/validate'), $quranReleaseGovernance),
        new Route('platform.quran.releases.approve', [HttpMethod::GET, HttpMethod::POST], new RoutePattern('/platform/quran/releases/{releaseId}/approve'), $quranReleaseGovernance),
        new Route('platform.quran.releases.activate', [HttpMethod::GET, HttpMethod::POST], new RoutePattern('/platform/quran/releases/{releaseId}/activate'), $quranReleaseGovernance),
        new Route('platform.quran.releases.reject', [HttpMethod::GET, HttpMethod::POST], new RoutePattern('/platform/quran/releases/{releaseId}/reject'), $quranReleaseGovernance),
        new Route('platform.quran.search_corpus', [HttpMethod::GET], new RoutePattern('/platform/quran/releases/{releaseId}/search-corpus'), $quranSearchCorpusIntegrity),
        new Route('platform.quran.search_corpus.validate', [HttpMethod::GET, HttpMethod::POST], new RoutePattern('/platform/quran/releases/{releaseId}/search-corpus/validate'), $quranSearchCorpusIntegrity),
        new Route('platform.security.accounts.suspend', [HttpMethod::GET, HttpMethod::POST], new RoutePattern('/platform/security/accounts/{accountId}/suspend'), $accountState),
        new Route('platform.security.accounts.reactivate', [HttpMethod::GET, HttpMethod::POST], new RoutePattern('/platform/security/accounts/{accountId}/reactivate'), $accountState),
        new Route('account.security.events', [HttpMethod::GET], new RoutePattern('/account/security/events'), $securityAudit),
        new Route('platform.security.events', [HttpMethod::GET], new RoutePattern('/platform/security/events'), $securityAudit),
        new Route('platform.security.events.detail', [HttpMethod::GET], new RoutePattern('/platform/security/events/{eventId}'), $securityAudit),
        new Route('platform.security.audit', [HttpMethod::GET], new RoutePattern('/platform/security/audit'), $securityAudit),
        new Route('account.privileged_access.index', [HttpMethod::GET], new RoutePattern('/account/security/privileged-access'), $privilegedAccess),
        new Route('account.privileged_access.temporary.request.form', [HttpMethod::GET], new RoutePattern('/account/security/privileged-access/temporary/request'), $privilegedAccess),
        new Route('account.privileged_access.temporary.request.submit', [HttpMethod::POST], new RoutePattern('/account/security/privileged-access/temporary/request'), $privilegedAccess),
        new Route('account.privileged_access.support.request.form', [HttpMethod::GET], new RoutePattern('/account/security/support-access/request'), $privilegedAccess),
        new Route('account.privileged_access.support.request.submit', [HttpMethod::POST], new RoutePattern('/account/security/support-access/request'), $privilegedAccess),
        new Route('account.privileged_access.detail', [HttpMethod::GET], new RoutePattern('/account/security/privileged-access/{requestId}'), $privilegedAccess),
        new Route('account.privileged_access.approve.form', [HttpMethod::GET], new RoutePattern('/account/security/privileged-access/{requestId}/approve'), $privilegedAccess),
        new Route('account.privileged_access.approve.submit', [HttpMethod::POST], new RoutePattern('/account/security/privileged-access/{requestId}/approve'), $privilegedAccess),
        new Route('account.privileged_access.reject.submit', [HttpMethod::POST], new RoutePattern('/account/security/privileged-access/{requestId}/reject'), $privilegedAccess),
        new Route('account.privileged_access.cancel.submit', [HttpMethod::POST], new RoutePattern('/account/security/privileged-access/{requestId}/cancel'), $privilegedAccess),
        new Route('account.privileged_access.activate.submit', [HttpMethod::POST], new RoutePattern('/account/security/privileged-access/{requestId}/activate'), $privilegedAccess),
        new Route('account.privileged_access.revoke.submit', [HttpMethod::POST], new RoutePattern('/account/security/privileged-access/{requestId}/revoke'), $privilegedAccess),
        new Route('workspace.privileged_access.approve.form', [HttpMethod::GET], new RoutePattern('/workspace/security/support-access/{requestId}/approve'), $privilegedAccess),
        new Route('workspace.privileged_access.approve.submit', [HttpMethod::POST], new RoutePattern('/workspace/security/support-access/{requestId}/approve'), $privilegedAccess),
        new Route('account.privileged_access.active.end.submit', [HttpMethod::POST], new RoutePattern('/account/security/privileged-access/active/end'), $privilegedAccess),
        new Route('account.privileged_access.break_glass.activate.form', [HttpMethod::GET], new RoutePattern('/account/security/break-glass/activate'), $privilegedAccess),
        new Route('account.privileged_access.break_glass.activate.submit', [HttpMethod::POST], new RoutePattern('/account/security/break-glass/activate'), $privilegedAccess),
        new Route('account.privileged_access.review.form', [HttpMethod::GET], new RoutePattern('/account/security/privileged-access/{requestId}/review'), $privilegedAccess),
        new Route('account.privileged_access.review.submit', [HttpMethod::POST], new RoutePattern('/account/security/privileged-access/{requestId}/review'), $privilegedAccess),
        new Route(
            'account.security.sessions',
            [HttpMethod::GET],
            new RoutePattern('/account/security/sessions'),
            $accountSecurity,
        ),
        new Route(
            'account.security.session_revoke.form',
            [HttpMethod::GET],
            new RoutePattern('/account/security/sessions/{sessionId}/revoke'),
            $sessionRevocation,
        ),
        new Route(
            'account.security.session_revoke.submit',
            [HttpMethod::POST],
            new RoutePattern('/account/security/sessions/{sessionId}/revoke'),
            $sessionRevocation,
        ),
        new Route(
            'account.security.device_revoke.form',
            [HttpMethod::GET],
            new RoutePattern('/account/security/devices/{deviceId}/revoke'),
            $deviceRevocation,
        ),
        new Route(
            'account.security.device_revoke.submit',
            [HttpMethod::POST],
            new RoutePattern('/account/security/devices/{deviceId}/revoke'),
            $deviceRevocation,
        ),
        new Route(
            'account.password_recovery.request.form',
            [HttpMethod::GET],
            new RoutePattern('/forgot-password'),
            $recoveryRequestForm,
        ),
        new Route(
            'account.password_recovery.request.submit',
            [HttpMethod::POST],
            new RoutePattern('/forgot-password'),
            $recoveryRequestSubmit,
        ),
        new Route(
            'account.password_recovery.request.accepted',
            [HttpMethod::GET],
            new RoutePattern('/forgot-password/accepted'),
            $recoveryRequestAccepted,
        ),
        new Route(
            'account.password_recovery.reset.form',
            [HttpMethod::GET],
            new RoutePattern('/reset-password/{challengeId}'),
            $passwordResetForm,
        ),
        new Route(
            'account.password_recovery.reset.submit',
            [HttpMethod::POST],
            new RoutePattern('/reset-password/{challengeId}'),
            $passwordResetSubmit,
        ),
        new Route(
            'account.password_recovery.reset.completed',
            [HttpMethod::GET],
            new RoutePattern('/reset-password/completed'),
            $passwordResetCompleted,
        ),
        new Route('account.mfa.login.form', [HttpMethod::GET], new RoutePattern('/login/mfa'), $multiFactor),
        new Route(
            'account.mfa.login.totp',
            [HttpMethod::POST],
            new RoutePattern('/login/mfa/totp'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.login.recovery_code',
            [HttpMethod::POST],
            new RoutePattern('/login/mfa/recovery-code'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.login.passkey.options',
            [HttpMethod::POST],
            new RoutePattern('/login/mfa/passkey/options'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.login.passkey.verify',
            [HttpMethod::POST],
            new RoutePattern('/login/mfa/passkey/verify'),
            $multiFactor,
        ),
        new Route(
            'account.passkey.login.options',
            [HttpMethod::POST],
            new RoutePattern('/login/passkey/options'),
            $multiFactor,
        ),
        new Route(
            'account.passkey.login.verify',
            [HttpMethod::POST],
            new RoutePattern('/login/passkey/verify'),
            $multiFactor,
        ),
        new Route(
            'account.step_up.form',
            [HttpMethod::GET],
            new RoutePattern('/account/step-up/{action}'),
            $multiFactor,
        ),
        new Route(
            'account.step_up.password',
            [HttpMethod::POST],
            new RoutePattern('/account/step-up/password'),
            $multiFactor,
        ),
        new Route(
            'account.step_up.totp',
            [HttpMethod::POST],
            new RoutePattern('/account/step-up/totp'),
            $multiFactor,
        ),
        new Route(
            'account.step_up.recovery_code',
            [HttpMethod::POST],
            new RoutePattern('/account/step-up/recovery-code'),
            $multiFactor,
        ),
        new Route(
            'account.step_up.passkey.options',
            [HttpMethod::POST],
            new RoutePattern('/account/step-up/passkey/options'),
            $multiFactor,
        ),
        new Route(
            'account.step_up.passkey.verify',
            [HttpMethod::POST],
            new RoutePattern('/account/step-up/passkey/verify'),
            $multiFactor,
        ),
        new Route(
            'account.security.authentication',
            [HttpMethod::GET],
            new RoutePattern('/account/security/authentication'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.totp.enroll.form',
            [HttpMethod::GET],
            new RoutePattern('/account/security/mfa/totp/enroll'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.totp.enroll.submit',
            [HttpMethod::POST],
            new RoutePattern('/account/security/mfa/totp/enroll'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.totp.confirm',
            [HttpMethod::POST],
            new RoutePattern('/account/security/mfa/totp/{authenticatorId}/confirm'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.totp.qr',
            [HttpMethod::GET],
            new RoutePattern('/account/security/mfa/totp/{authenticatorId}/qr'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.totp.revoke.form',
            [HttpMethod::GET],
            new RoutePattern('/account/security/mfa/totp/{authenticatorId}/revoke'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.totp.revoke.submit',
            [HttpMethod::POST],
            new RoutePattern('/account/security/mfa/totp/{authenticatorId}/revoke'),
            $multiFactor,
        ),
        new Route(
            'account.passkey.register.form',
            [HttpMethod::GET],
            new RoutePattern('/account/security/passkeys/register'),
            $multiFactor,
        ),
        new Route(
            'account.passkey.register.options',
            [HttpMethod::POST],
            new RoutePattern('/account/security/passkeys/registration/options'),
            $multiFactor,
        ),
        new Route(
            'account.passkey.register.verify',
            [HttpMethod::POST],
            new RoutePattern('/account/security/passkeys/registration/verify'),
            $multiFactor,
        ),
        new Route(
            'account.passkey.revoke.form',
            [HttpMethod::GET],
            new RoutePattern('/account/security/passkeys/{passkeyId}/revoke'),
            $multiFactor,
        ),
        new Route(
            'account.passkey.revoke.submit',
            [HttpMethod::POST],
            new RoutePattern('/account/security/passkeys/{passkeyId}/revoke'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.enable',
            [HttpMethod::POST],
            new RoutePattern('/account/security/mfa/enable'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.disable.form',
            [HttpMethod::GET],
            new RoutePattern('/account/security/mfa/disable'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.disable.submit',
            [HttpMethod::POST],
            new RoutePattern('/account/security/mfa/disable'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.recovery_codes.status',
            [HttpMethod::GET],
            new RoutePattern('/account/security/mfa/recovery-codes'),
            $multiFactor,
        ),
        new Route(
            'account.mfa.recovery_codes.regenerate',
            [HttpMethod::POST],
            new RoutePattern('/account/security/mfa/recovery-codes/regenerate'),
            $multiFactor,
        ),
        new Route('account.person_profile.view', [HttpMethod::GET], new RoutePattern('/account/profile'), $peopleProfiles),
        new Route('account.person_profile.create.form', [HttpMethod::GET], new RoutePattern('/account/profile/create'), $peopleProfiles),
        new Route('account.person_profile.create.submit', [HttpMethod::POST], new RoutePattern('/account/profile'), $peopleProfiles),
        new Route('account.person_profile.edit.form', [HttpMethod::GET], new RoutePattern('/account/profile/edit'), $peopleProfiles),
        new Route('account.person_profile.update.submit', [HttpMethod::POST], new RoutePattern('/account/profile/update'), $peopleProfiles),
        new Route('account.person_profile.role.activate', [HttpMethod::POST], new RoutePattern('/account/profile/roles/{role_type}/activate'), $peopleProfiles),
        new Route('account.person_profile.role.deactivate.form', [HttpMethod::GET], new RoutePattern('/account/profile/roles/{role_type}/deactivate'), $peopleProfiles),
        new Route('account.person_profile.role.deactivate.submit', [HttpMethod::POST], new RoutePattern('/account/profile/roles/{role_type}/deactivate'), $peopleProfiles),
        new Route('account.person_profile.memorizer_progress.form', [HttpMethod::GET], new RoutePattern('/account/profile/memorizer-progress'), $peopleProfiles),
        new Route('account.person_profile.memorizer_progress.submit', [HttpMethod::POST], new RoutePattern('/account/profile/memorizer-progress'), $peopleProfiles),
        new Route('account.person_profile.dependents.index', [HttpMethod::GET], new RoutePattern('/account/dependents'), $peopleProfiles),
        new Route('account.person_profile.dependent.create.form', [HttpMethod::GET], new RoutePattern('/account/dependents/create'), $peopleProfiles),
        new Route('account.person_profile.dependent.create.submit', [HttpMethod::POST], new RoutePattern('/account/dependents'), $peopleProfiles),
        new Route('account.person_profile.dependent.view', [HttpMethod::GET], new RoutePattern('/account/dependents/{person_id}'), $peopleProfiles),
        new Route('account.person_profile.dependent.edit.form', [HttpMethod::GET], new RoutePattern('/account/dependents/{person_id}/edit'), $peopleProfiles),
        new Route('account.person_profile.dependent.update.submit', [HttpMethod::POST], new RoutePattern('/account/dependents/{person_id}/update'), $peopleProfiles),
        new Route('account.person_profile.dependent.memorizer_progress.form', [HttpMethod::GET], new RoutePattern('/account/dependents/{person_id}/memorizer-progress'), $peopleProfiles),
        new Route('account.person_profile.dependent.memorizer_progress.submit', [HttpMethod::POST], new RoutePattern('/account/dependents/{person_id}/memorizer-progress'), $peopleProfiles),
        new Route('account.person_profile.guardianship.revoke.form', [HttpMethod::GET], new RoutePattern('/account/dependents/{person_id}/guardianship/revoke'), $peopleProfiles),
        new Route('account.person_profile.guardianship.revoke.submit', [HttpMethod::POST], new RoutePattern('/account/dependents/{person_id}/guardianship/revoke'), $peopleProfiles),
        new Route('account.profile_claim_pairing.form', [HttpMethod::GET], new RoutePattern('/account/profile/claim-pairing'), $identityResolution),
        new Route('account.profile_claim_pairing.create', [HttpMethod::POST], new RoutePattern('/account/profile/claim-pairing'), $identityResolution),
        new Route('account.profile_claim_pairing.revoke', [HttpMethod::POST], new RoutePattern('/account/profile/claim-pairing/{pairingId}/revoke'), $identityResolution),
        new Route('account.profile_claims.index', [HttpMethod::GET], new RoutePattern('/account/profile/claims'), $identityResolution),
        new Route('account.profile_claim.detail', [HttpMethod::GET], new RoutePattern('/account/profile/claims/{claimId}'), $identityResolution),
        new Route('account.profile_claim.accept', [HttpMethod::POST], new RoutePattern('/account/profile/claims/{claimId}/accept'), $identityResolution),
        new Route('account.profile_claim.decline', [HttpMethod::POST], new RoutePattern('/account/profile/claims/{claimId}/decline'), $identityResolution),
        new Route('account.dependent_profile_claim.authorization.form', [HttpMethod::GET], new RoutePattern('/account/dependents/{personId}/profile-claim/authorization'), $identityResolution),
        new Route('account.dependent_profile_claim.authorization.submit', [HttpMethod::POST], new RoutePattern('/account/dependents/{personId}/profile-claim/authorization'), $identityResolution),
        new Route('account.dependent_profile_claim.revoke', [HttpMethod::POST], new RoutePattern('/account/dependents/{personId}/profile-claims/{claimId}/revoke'), $identityResolution),
        new Route('platform.profile_claim.index', [HttpMethod::GET], new RoutePattern('/platform/people/profile-claims'), $identityResolution),
        new Route('platform.profile_claim.authorization.form', [HttpMethod::GET], new RoutePattern('/platform/people/profile-claims/authorization'), $identityResolution),
        new Route('platform.profile_claim.authorization.submit', [HttpMethod::POST], new RoutePattern('/platform/people/profile-claims/authorization'), $identityResolution),
        new Route('platform.profile_claim.revoke', [HttpMethod::POST], new RoutePattern('/platform/people/profile-claims/{claimId}/revoke'), $identityResolution),
        new Route('platform.profile_verification.index', [HttpMethod::GET], new RoutePattern('/platform/people/profile-verifications'), $identityResolution),
        new Route('platform.profile_verification.detail', [HttpMethod::GET], new RoutePattern('/platform/people/profile-verifications/{personId}'), $identityResolution),
        new Route('platform.profile_verification.record', [HttpMethod::POST], new RoutePattern('/platform/people/profile-verifications/{personId}'), $identityResolution),
        new Route('platform.profile_verification.revoke', [HttpMethod::POST], new RoutePattern('/platform/people/profile-verifications/{personId}/{assertionId}/revoke'), $identityResolution),
        new Route('account.person_duplicate.report.form', [HttpMethod::GET], new RoutePattern('/account/profile/duplicates/report'), $identityResolution),
        new Route('account.person_duplicate.report.submit', [HttpMethod::POST], new RoutePattern('/account/profile/duplicates/report'), $identityResolution),
        new Route('account.person_duplicate.index', [HttpMethod::GET], new RoutePattern('/account/profile/duplicate-cases'), $identityResolution),
        new Route('account.person_duplicate.case.detail', [HttpMethod::GET], new RoutePattern('/account/profile/duplicate-cases/{caseId}'), $identityResolution),
        new Route('account.person_duplicate.consent', [HttpMethod::POST], new RoutePattern('/account/profile/duplicate-cases/{caseId}/consent'), $identityResolution),
        new Route('account.person_duplicate.decline', [HttpMethod::POST], new RoutePattern('/account/profile/duplicate-cases/{caseId}/decline'), $identityResolution),
        new Route('account.dependent_duplicate.report.form', [HttpMethod::GET], new RoutePattern('/account/dependents/{personId}/duplicates/report'), $identityResolution),
        new Route('account.dependent_duplicate.report.submit', [HttpMethod::POST], new RoutePattern('/account/dependents/{personId}/duplicates/report'), $identityResolution),
        new Route('account.dependent_duplicate.case.detail', [HttpMethod::GET], new RoutePattern('/account/dependents/{personId}/duplicate-cases/{caseId}'), $identityResolution),
        new Route('account.dependent_duplicate.consent', [HttpMethod::POST], new RoutePattern('/account/dependents/{personId}/duplicate-cases/{caseId}/consent'), $identityResolution),
        new Route('account.dependent_duplicate.decline', [HttpMethod::POST], new RoutePattern('/account/dependents/{personId}/duplicate-cases/{caseId}/decline'), $identityResolution),
        new Route('platform.person_duplicate.index', [HttpMethod::GET], new RoutePattern('/platform/people/duplicates'), $identityResolution),
        new Route('platform.person_duplicate.detail', [HttpMethod::GET], new RoutePattern('/platform/people/duplicates/{caseId}'), $identityResolution),
        new Route('platform.person_duplicate.review', [HttpMethod::POST], new RoutePattern('/platform/people/duplicates/{caseId}/review'), $identityResolution),
        new Route('platform.person_duplicate.dismiss', [HttpMethod::POST], new RoutePattern('/platform/people/duplicates/{caseId}/dismiss'), $identityResolution),
        new Route('platform.person_duplicate.resolve.form', [HttpMethod::GET], new RoutePattern('/platform/people/duplicates/{caseId}/resolve'), $identityResolution),
        new Route('platform.person_duplicate.resolve.submit', [HttpMethod::POST], new RoutePattern('/platform/people/duplicates/{caseId}/resolve'), $identityResolution),
        new Route('workspace.organizations.index', [HttpMethod::GET], new RoutePattern('/workspace/organizations'), $organizationsRegistry),
        new Route('workspace.organizations.create.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/create'), $organizationsRegistry),
        new Route('workspace.organizations.create.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations'), $organizationsRegistry),
        new Route('workspace.organizations.view', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}'), $organizationsRegistry),
        new Route('workspace.organizations.edit.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/edit'), $organizationsRegistry),
        new Route('workspace.organizations.update.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/update'), $organizationsRegistry),
        new Route('workspace.organizations.retire.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/retire'), $organizationsRegistry),
        new Route('workspace.organizations.retire.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/retire'), $organizationsRegistry),
        new Route('workspace.organizations.units.create.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/units/create'), $organizationsRegistry),
        new Route('workspace.organizations.units.create.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/units'), $organizationsRegistry),
        new Route('workspace.organizations.units.view', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/units/{unitId}'), $organizationsRegistry),
        new Route('workspace.organizations.units.edit.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/units/{unitId}/edit'), $organizationsRegistry),
        new Route('workspace.organizations.units.update.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/units/{unitId}/update'), $organizationsRegistry),
        new Route('workspace.organizations.units.retire.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/units/{unitId}/retire'), $organizationsRegistry),
        new Route('workspace.organizations.units.retire.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/units/{unitId}/retire'), $organizationsRegistry),
        new Route('workspace.organizations.affiliations.index', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/affiliations'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.request.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/request'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.request.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/request'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.view', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.assignments.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/assignments'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.assignments.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/assignments'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.withdraw.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/withdraw'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.withdraw.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/withdraw'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.suspend.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/suspend'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.suspend.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/suspend'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.resume.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/resume'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.resume.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/resume'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.end.form', [HttpMethod::GET], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/end'), $organizationAffiliations),
        new Route('workspace.organizations.affiliations.end.submit', [HttpMethod::POST], new RoutePattern('/workspace/organizations/{organizationId}/affiliations/{affiliationId}/end'), $organizationAffiliations),
        new Route('account.affiliations.index', [HttpMethod::GET], new RoutePattern('/account/affiliations'), $organizationAffiliations),
        new Route('account.affiliations.detail', [HttpMethod::GET], new RoutePattern('/account/affiliations/{affiliationId}'), $organizationAffiliations),
        new Route('account.affiliations.accept.form', [HttpMethod::GET], new RoutePattern('/account/affiliations/{affiliationId}/accept'), $organizationAffiliations),
        new Route('account.affiliations.accept.submit', [HttpMethod::POST], new RoutePattern('/account/affiliations/{affiliationId}/accept'), $organizationAffiliations),
        new Route('account.affiliations.decline.form', [HttpMethod::GET], new RoutePattern('/account/affiliations/{affiliationId}/decline'), $organizationAffiliations),
        new Route('account.affiliations.decline.submit', [HttpMethod::POST], new RoutePattern('/account/affiliations/{affiliationId}/decline'), $organizationAffiliations),
        new Route('account.affiliations.leave.form', [HttpMethod::GET], new RoutePattern('/account/affiliations/{affiliationId}/leave'), $organizationAffiliations),
        new Route('account.affiliations.leave.submit', [HttpMethod::POST], new RoutePattern('/account/affiliations/{affiliationId}/leave'), $organizationAffiliations),
        new Route('account.competition_judging.dashboard', [HttpMethod::GET], new RoutePattern('/account/judging'), $competitionP6Workflow),
        new Route('account.competition_judging.assignment.detail', [HttpMethod::GET], new RoutePattern('/account/judging/assignments/{assignmentId}'), $competitionP6Workflow),
        new Route('account.competition_judging.assignment.accept', [HttpMethod::POST], new RoutePattern('/account/judging/assignments/{assignmentId}/accept'), $competitionP6Workflow),
        new Route('account.competition_judging.assignment.decline', [HttpMethod::POST], new RoutePattern('/account/judging/assignments/{assignmentId}/decline'), $competitionP6Workflow),
        new Route('account.competition_judging.score.form', [HttpMethod::GET], new RoutePattern('/account/judging/assignments/{assignmentId}/participants/{participantId}/score'), $competitionP6Workflow),
        new Route('account.competition_judging.score.submit', [HttpMethod::POST], new RoutePattern('/account/judging/assignments/{assignmentId}/participants/{participantId}/score/submit'), $competitionP6Workflow),
        new Route('account.competition_judging.score.lock.form', [HttpMethod::GET], new RoutePattern('/account/judging/assignments/{assignmentId}/participants/{participantId}/score/lock'), $competitionP6Workflow),
        new Route('account.competition_judging.score.lock', [HttpMethod::POST], new RoutePattern('/account/judging/assignments/{assignmentId}/participants/{participantId}/score/lock'), $competitionP6Workflow),
        new Route('account.competition_appeal.index', [HttpMethod::GET], new RoutePattern('/account/competition-appeals'), $competitionP6Workflow),
        new Route('account.competition_appeal.detail', [HttpMethod::GET], new RoutePattern('/account/competition-appeals/{appealId}'), $competitionP6Workflow),
        new Route('account.competition_appeal.withdraw.form', [HttpMethod::GET], new RoutePattern('/account/competition-appeals/{appealId}/withdraw'), $competitionP6Workflow),
        new Route('account.competition_appeal.withdraw', [HttpMethod::POST], new RoutePattern('/account/competition-appeals/{appealId}/withdraw'), $competitionP6Workflow),
        new Route('workspace.competition.round.ready.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/rounds/{roundId}/ready'), $competitionP6Workflow),
        new Route('workspace.competition.round.ready', [HttpMethod::POST], new RoutePattern('/workspace/competitions/rounds/{roundId}/ready'), $competitionP6Workflow),
        new Route('workspace.competition.round.open_scoring.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/rounds/{roundId}/open-scoring'), $competitionP6Workflow),
        new Route('workspace.competition.round.open_scoring', [HttpMethod::POST], new RoutePattern('/workspace/competitions/rounds/{roundId}/open-scoring'), $competitionP6Workflow),
        new Route('workspace.competition.round.close_scoring.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/rounds/{roundId}/close-scoring'), $competitionP6Workflow),
        new Route('workspace.competition.round.close_scoring', [HttpMethod::POST], new RoutePattern('/workspace/competitions/rounds/{roundId}/close-scoring'), $competitionP6Workflow),
        new Route('workspace.competition.round.cancel.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/rounds/{roundId}/cancel'), $competitionP6Workflow),
        new Route('workspace.competition.round.cancel', [HttpMethod::POST], new RoutePattern('/workspace/competitions/rounds/{roundId}/cancel'), $competitionP6Workflow),
        new Route('workspace.competition.assignment.revoke', [HttpMethod::POST], new RoutePattern('/workspace/competitions/assignments/{assignmentId}/revoke'), $competitionP6Workflow),
        new Route('workspace.competition.result.verify.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-runs/{resultRunId}/verify'), $competitionP6Workflow),
        new Route('workspace.competition.result.verify', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-runs/{resultRunId}/verify'), $competitionP6Workflow),
        new Route('workspace.competition.result.calculate.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/rounds/{roundId}/calculate-results'), $competitionP6Workflow),
        new Route('workspace.competition.result.calculate', [HttpMethod::POST], new RoutePattern('/workspace/competitions/rounds/{roundId}/calculate-results'), $competitionP6Workflow),
        new Route('workspace.competition.result.publish.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-runs/{resultRunId}/publish'), $competitionP6Workflow),
        new Route('workspace.competition.result.publish', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-runs/{resultRunId}/publish'), $competitionP6Workflow),
        new Route('workspace.competition.result.void.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-runs/{resultRunId}/void'), $competitionP6Workflow),
        new Route('workspace.competition.result.void', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-runs/{resultRunId}/void'), $competitionP6Workflow),
        new Route('workspace.competition.appeal.start_review', [HttpMethod::POST], new RoutePattern('/workspace/competitions/appeals/{appealId}/start-review'), $competitionP6Workflow),
        new Route('workspace.competition.appeal.uphold.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/appeals/{appealId}/uphold'), $competitionP6Workflow),
        new Route('workspace.competition.appeal.uphold', [HttpMethod::POST], new RoutePattern('/workspace/competitions/appeals/{appealId}/uphold'), $competitionP6Workflow),
        new Route('workspace.competition.appeal.dismiss.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/appeals/{appealId}/dismiss'), $competitionP6Workflow),
        new Route('workspace.competition.appeal.dismiss', [HttpMethod::POST], new RoutePattern('/workspace/competitions/appeals/{appealId}/dismiss'), $competitionP6Workflow),
        new Route('workspace.competition.live_session.open.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/open'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.open', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/open'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.pause.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/pause'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.pause', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/pause'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.resume.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/resume'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.resume', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/resume'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.start_recovery.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/start-recovery'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.start_recovery', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/start-recovery'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.complete_recovery.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/complete-recovery'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.complete_recovery', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/complete-recovery'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.close.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/close'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.close', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/close'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.cancel.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/cancel'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_session.cancel', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/cancel'), $competitionLiveSessionWorkflow),
        new Route('workspace.competition.live_participant.check_in.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/check-in'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.check_in', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/check-in'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.call.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/call'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.call', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/call'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.ready.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/ready'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.ready', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/ready'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.start.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/start'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.start', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/start'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.interrupt.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/interrupt'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.interrupt', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/interrupt'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.resume.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/resume'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.resume', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/resume'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.complete.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/complete'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.complete', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/complete'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.absent.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/absent'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.absent', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/absent'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.withdraw.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/withdraw'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.withdraw', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/withdraw'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.disqualify.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/disqualify'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.live_participant.disqualify', [HttpMethod::POST], new RoutePattern('/workspace/competitions/live-sessions/{sessionId}/participants/{participantId}/disqualify'), $competitionLiveParticipantWorkflow),
        new Route('workspace.competition.result_publication.prepare.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-runs/{resultRunId}/publications/prepare'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.prepare', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-runs/{resultRunId}/publications/prepare'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.publish_provisional.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/publish-provisional'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.publish_provisional', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/publish-provisional'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.hold.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/hold'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.hold', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/hold'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.release_hold.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/release-hold'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.release_hold', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/release-hold'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.finalize.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/finalize'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.finalize', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/finalize'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.withdraw.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/withdraw'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.withdraw', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/withdraw'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.supersede.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/supersede'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.supersede', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/supersede'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.archive.form', [HttpMethod::GET], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/archive'), $competitionResultPublicationWorkflow),
        new Route('workspace.competition.result_publication.archive', [HttpMethod::POST], new RoutePattern('/workspace/competitions/result-publications/{publicationId}/archive'), $competitionResultPublicationWorkflow),
        new Route('competition.public.results.edition', [HttpMethod::GET], new RoutePattern('/competitions/{editionSlug}/results'), $competitionPublicResults),
        new Route('competition.public.results.category', [HttpMethod::GET], new RoutePattern('/competitions/{editionSlug}/categories/{categorySlug}/results'), $competitionPublicResults),
        new Route('competition.public.results.round', [HttpMethod::GET], new RoutePattern('/competitions/{editionSlug}/categories/{categorySlug}/rounds/{roundCode}/results'), $competitionPublicResults),
    );
};
