<?php

declare(strict_types=1);

namespace Qmdb\Modules\OrganizationAffiliations\Domain;

enum OrganizationAffiliationReasonCode: string
{
    case AFFILIATION_REQUESTED = 'AFFILIATION_REQUESTED';
    case AFFILIATION_ACCEPTED = 'AFFILIATION_ACCEPTED';
    case AFFILIATION_DECLINED = 'AFFILIATION_DECLINED';
    case REQUEST_WITHDRAWN = 'REQUEST_WITHDRAWN';
    case REQUEST_EXPIRED = 'REQUEST_EXPIRED';
    case ADMINISTRATIVE_SUSPENSION = 'ADMINISTRATIVE_SUSPENSION';
    case SECURITY_REVIEW = 'SECURITY_REVIEW';
    case AFFILIATION_RESUMED = 'AFFILIATION_RESUMED';
    case ORGANIZATION_ENDED = 'ORGANIZATION_ENDED';
    case PERSON_LEFT = 'PERSON_LEFT';
    case GUARDIAN_WITHDREW = 'GUARDIAN_WITHDREW';
}
