<?php

declare(strict_types=1);

namespace Qmdb\Bootstrap\Module;

use Qmdb\Shared\Module\Module;
use Qmdb\Shared\Module\ModuleId;
use Qmdb\Shared\Module\ModuleRegistrationContext;

final readonly class MediaModerationModule implements Module
{
    public function id(): ModuleId
    {
        return new ModuleId('media.moderation');
    }
    public function dependencies(): array
    {
        return [new ModuleId('media.catalog'), new ModuleId('identity.access'), new ModuleId('identity.sessions'), new ModuleId('identity.multifactor'), new ModuleId('tenancy.context'), new ModuleId('security.authorization'), new ModuleId('security.audit'), new ModuleId('foundation.http'), new ModuleId('foundation.presentation'), new ModuleId('foundation.database')];
    }
    public function register(ModuleRegistrationContext $context): void
    {
        $context->service(\Qmdb\Shared\DependencyInjection\ServiceDefinition::factory(\Qmdb\Modules\MediaModeration\Infrastructure\Persistence\MySqlMediaGovernanceRepository::class, 'media.moderation', [\Qmdb\Shared\Database\Connection\DatabaseConnectionProvider::class], new \Qmdb\Shared\DependencyInjection\ClosureServiceFactory(static fn (\Qmdb\Shared\DependencyInjection\DependencyResolver $resolver): \Qmdb\Modules\MediaModeration\Infrastructure\Persistence\MySqlMediaGovernanceRepository => new \Qmdb\Modules\MediaModeration\Infrastructure\Persistence\MySqlMediaGovernanceRepository(\Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Shared\Database\Connection\DatabaseConnectionProvider::class)))));
        $context->service(\Qmdb\Shared\DependencyInjection\ServiceDefinition::factory(\Qmdb\Modules\MediaModeration\Application\MediaGovernanceService::class, 'media.moderation', [\Qmdb\Modules\MediaModeration\Application\MediaGovernanceRepository::class, \Qmdb\Modules\SecurityAuthorization\Application\AuthorizationRequirementGuard::class, \Qmdb\Modules\IdentityMultiFactor\Application\StepUpGuard::class, \Qmdb\Modules\IdentityAccess\Security\RateLimit\IdentityRateLimiter::class, \Qmdb\Modules\IdentityAccess\Security\Fingerprint\IdentityFingerprintGenerator::class, \Qmdb\Modules\SecurityAudit\Application\SecurityAuditEventAppender::class, \Qmdb\Shared\Database\Transaction\TransactionManager::class, \Qmdb\Shared\Time\Clock::class], new \Qmdb\Shared\DependencyInjection\ClosureServiceFactory(static fn (\Qmdb\Shared\DependencyInjection\DependencyResolver $resolver): \Qmdb\Modules\MediaModeration\Application\MediaGovernanceService => new \Qmdb\Modules\MediaModeration\Application\MediaGovernanceService(\Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\MediaModeration\Application\MediaGovernanceRepository::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\SecurityAuthorization\Application\AuthorizationRequirementGuard::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\IdentityMultiFactor\Application\StepUpGuard::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\IdentityAccess\Security\RateLimit\IdentityRateLimiter::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\IdentityAccess\Security\Fingerprint\IdentityFingerprintGenerator::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\SecurityAudit\Application\SecurityAuditEventAppender::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Shared\Database\Transaction\TransactionManager::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Shared\Time\Clock::class)))));
        $context->service(\Qmdb\Shared\DependencyInjection\ServiceDefinition::factory(\Qmdb\Modules\MediaModeration\Interface\Http\MediaGovernanceController::class, 'media.moderation', [\Qmdb\Modules\IdentitySessions\Interface\Http\AuthenticatedRequestGuard::class, \Qmdb\Modules\TenancyContext\Application\TenantContextRequiredGuard::class, \Qmdb\Modules\SecurityAuthorization\Application\AuthorizationRequirementGuard::class, \Qmdb\Modules\IdentityAccess\Interface\Http\IdentityCsrf::class, \Qmdb\Modules\MediaModeration\Application\MediaGovernanceService::class, \Qmdb\Modules\MediaModeration\Application\MediaGovernanceRepository::class, \Qmdb\Modules\IdentityAccess\Interface\Http\IdentityAccessView::class], new \Qmdb\Shared\DependencyInjection\ClosureServiceFactory(static fn (\Qmdb\Shared\DependencyInjection\DependencyResolver $resolver): \Qmdb\Modules\MediaModeration\Interface\Http\MediaGovernanceController => new \Qmdb\Modules\MediaModeration\Interface\Http\MediaGovernanceController(\Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\IdentitySessions\Interface\Http\AuthenticatedRequestGuard::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\TenancyContext\Application\TenantContextRequiredGuard::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\SecurityAuthorization\Application\AuthorizationRequirementGuard::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\IdentityAccess\Interface\Http\IdentityCsrf::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\MediaModeration\Application\MediaGovernanceService::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\MediaModeration\Application\MediaGovernanceRepository::class), \Qmdb\Shared\DependencyInjection\ServiceReference::get($resolver, \Qmdb\Modules\IdentityAccess\Interface\Http\IdentityAccessView::class)))));
        $context->alias(\Qmdb\Modules\MediaModeration\Application\MediaGovernanceRepository::class, \Qmdb\Modules\MediaModeration\Infrastructure\Persistence\MySqlMediaGovernanceRepository::class);
    }
}
