<?php

declare(strict_types=1);

namespace Qmdb\Bootstrap\Module;

use Qmdb\Modules\IdentityResolution\Application\IdentityResolutionRepository;
use Qmdb\Modules\IdentityResolution\Application\IdentityResolutionManagementAuthoritySnapshotProvider;
use Qmdb\Modules\IdentityResolution\Application\IdentityResolutionVerificationProjectionProvider;
use Qmdb\Modules\IdentityResolution\Application\GuardianProfileClaimAuthorizationService;
use Qmdb\Modules\IdentityResolution\Application\PeopleIdentityResolutionReadinessCheck;
use Qmdb\Modules\IdentityResolution\Application\PlatformProfileClaimAuthorizationService;
use Qmdb\Modules\IdentityResolution\Application\ProfileClaimAcceptanceService;
use Qmdb\Modules\IdentityResolution\Application\ProfileClaimDeclineService;
use Qmdb\Modules\IdentityResolution\Application\ProfileClaimPairingRevocationService;
use Qmdb\Modules\IdentityResolution\Application\ProfileClaimRevocationService;
use Qmdb\Modules\IdentityResolution\Application\ProfileVerificationAssertionService;
use Qmdb\Modules\IdentityResolution\Application\ProfileVerificationRevocationService;
use Qmdb\Modules\IdentityResolution\Application\PersonDuplicateConsentService;
use Qmdb\Modules\IdentityResolution\Application\PersonDuplicateDismissalService;
use Qmdb\Modules\IdentityResolution\Application\PersonDuplicateReportService;
use Qmdb\Modules\IdentityResolution\Application\PersonDuplicateResolutionPreflight;
use Qmdb\Modules\IdentityResolution\Application\PersonDuplicateResolutionService;
use Qmdb\Modules\IdentityResolution\Application\PersonDuplicateReviewService;
use Qmdb\Modules\IdentityResolution\Application\ProfileClaimPairingCreationService;
use Qmdb\Modules\IdentityResolution\Application\ProfileClaimMaintenanceService;
use Qmdb\Modules\IdentityResolution\Application\ProfileClaimPairingHasher;
use Qmdb\Modules\IdentityResolution\Application\ProfileClaimPairingResolver;
use Qmdb\Modules\IdentityResolution\Application\ScheduledProfileClaimMaintenanceTask;
use Qmdb\Modules\IdentityResolution\Configuration\IdentityResolutionConfiguration;
use Qmdb\Modules\IdentityResolution\Domain\ProfileClaimPairingCodeGenerator;
use Qmdb\Modules\IdentityResolution\Infrastructure\Persistence\MySqlIdentityResolutionRepository;
use Qmdb\Modules\IdentityResolution\Infrastructure\Persistence\MySqlCanonicalPersonIdentityResolver;
use Qmdb\Modules\IdentityResolution\Infrastructure\Persistence\MySqlPeopleProfilesCanonicalizationParticipant;
use Qmdb\Modules\IdentityResolution\Infrastructure\Security\SecureProfileClaimPairingCodeGenerator;
use Qmdb\Modules\IdentityResolution\Interface\Console\PeopleIdentityResolutionVerifyConsoleCommand;
use Qmdb\Modules\IdentityResolution\Interface\Http\PeopleIdentityResolutionController;
use Qmdb\Modules\IdentityAccess\Interface\Http\IdentityAccessView;
use Qmdb\Modules\IdentityAccess\Interface\Http\IdentityCsrf;
use Qmdb\Modules\IdentitySessions\Interface\Http\AuthenticatedRequestGuard;
use Qmdb\Modules\IdentityAccess\Domain\Repository\IdentityAccessRepository;
use Qmdb\Modules\IdentityAccess\Security\Fingerprint\IdentityFingerprintGenerator;
use Qmdb\Modules\IdentityAccess\Security\RateLimit\IdentityRateLimiter;
use Qmdb\Modules\SecurityAudit\Application\SecurityAuditEventAppender;
use Qmdb\Modules\IdentityMultiFactor\Application\StepUpGuard;
use Qmdb\Modules\People\Application\PeopleProfileSecurityNotificationService;
use Qmdb\Modules\People\Configuration\PeopleProfilesConfiguration;
use Qmdb\Modules\People\Application\PersonCanonicalIdentityResolver;
use Qmdb\Modules\People\Application\PersonCanonicalizationParticipant;
use Qmdb\Modules\People\Application\PersonManagementAuthoritySnapshotProvider;
use Qmdb\Modules\People\Application\PersonVerificationProjectionProvider;
use Qmdb\Modules\SecurityAuthorization\Application\AuthorizationRequirementGuard;
use Qmdb\Modules\OrganizationAffiliations\Application\OrganizationAffiliationPersonCanonicalizationParticipant;
use Qmdb\Shared\Background\Scheduler\FixedIntervalSchedule;
use Qmdb\Shared\Background\Scheduler\ScheduledTaskId;
use Qmdb\Shared\Background\Scheduler\ScheduledTaskRegistration;
use Qmdb\Shared\Database\Connection\DatabaseConnectionProvider;
use Qmdb\Shared\Database\Transaction\TransactionManager;
use Qmdb\Shared\DependencyInjection\ClosureServiceFactory;
use Qmdb\Shared\DependencyInjection\DependencyResolver;
use Qmdb\Shared\DependencyInjection\ServiceDefinition;
use Qmdb\Shared\DependencyInjection\ServiceReference;
use Qmdb\Shared\Module\Module;
use Qmdb\Shared\Module\ModuleId;
use Qmdb\Shared\Module\ModuleRegistrationContext;
use Qmdb\Shared\Schema\Health\SchemaHealthCheck;
use Qmdb\Shared\Time\Clock;

final readonly class PeopleIdentityResolutionModule implements Module
{
    private const string ID = 'people.identity_resolution';

    public function __construct(private IdentityResolutionConfiguration $configuration)
    {
    }

    public function id(): ModuleId
    {
        return new ModuleId(self::ID);
    }

    public function dependencies(): array
    {
        return [new ModuleId('foundation.core'), new ModuleId('foundation.application'), new ModuleId('foundation.observability'), new ModuleId('foundation.database'), new ModuleId('foundation.schema'), new ModuleId('foundation.background'), new ModuleId('foundation.http'), new ModuleId('foundation.presentation'), new ModuleId('security.web'), new ModuleId('security.authorization'), new ModuleId('security.audit'), new ModuleId('identity.accounts'), new ModuleId('identity.sessions'), new ModuleId('identity.multifactor'), new ModuleId('identity.security_notifications'), new ModuleId('people.profiles'), new ModuleId('organizations.affiliations')];
    }

    public function register(ModuleRegistrationContext $context): void
    {
        $context->service(ServiceDefinition::instance(IdentityResolutionConfiguration::class, self::ID, $this->configuration));
        $context->service(ServiceDefinition::instance(ProfileClaimPairingCodeGenerator::class, self::ID, new SecureProfileClaimPairingCodeGenerator()));
        $context->service(ServiceDefinition::factory(MySqlIdentityResolutionRepository::class, self::ID, [DatabaseConnectionProvider::class], new ClosureServiceFactory(static fn (DependencyResolver $r): MySqlIdentityResolutionRepository => new MySqlIdentityResolutionRepository(ServiceReference::get($r, DatabaseConnectionProvider::class)))));
        $context->alias(IdentityResolutionRepository::class, MySqlIdentityResolutionRepository::class);
        $context->service(ServiceDefinition::factory(MySqlCanonicalPersonIdentityResolver::class, self::ID, [DatabaseConnectionProvider::class], new ClosureServiceFactory(static fn (DependencyResolver $r): MySqlCanonicalPersonIdentityResolver => new MySqlCanonicalPersonIdentityResolver(ServiceReference::get($r, DatabaseConnectionProvider::class)))));
        $context->alias(PersonCanonicalIdentityResolver::class, MySqlCanonicalPersonIdentityResolver::class);
        $context->service(ServiceDefinition::factory(MySqlPeopleProfilesCanonicalizationParticipant::class, self::ID, [DatabaseConnectionProvider::class], new ClosureServiceFactory(static fn (DependencyResolver $r): MySqlPeopleProfilesCanonicalizationParticipant => new MySqlPeopleProfilesCanonicalizationParticipant(ServiceReference::get($r, DatabaseConnectionProvider::class)))));
        $context->alias(PersonCanonicalizationParticipant::class, MySqlPeopleProfilesCanonicalizationParticipant::class);
        $context->service(ServiceDefinition::factory(IdentityResolutionManagementAuthoritySnapshotProvider::class, self::ID, [MySqlIdentityResolutionRepository::class], new ClosureServiceFactory(static fn (DependencyResolver $r): IdentityResolutionManagementAuthoritySnapshotProvider => new IdentityResolutionManagementAuthoritySnapshotProvider(ServiceReference::get($r, MySqlIdentityResolutionRepository::class)))));
        $context->alias(PersonManagementAuthoritySnapshotProvider::class, IdentityResolutionManagementAuthoritySnapshotProvider::class);
        $context->service(ServiceDefinition::factory(IdentityResolutionVerificationProjectionProvider::class, self::ID, [MySqlIdentityResolutionRepository::class, PersonCanonicalIdentityResolver::class], new ClosureServiceFactory(static fn (DependencyResolver $r): IdentityResolutionVerificationProjectionProvider => new IdentityResolutionVerificationProjectionProvider(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, PersonCanonicalIdentityResolver::class)))));
        $context->alias(PersonVerificationProjectionProvider::class, IdentityResolutionVerificationProjectionProvider::class);
        $context->service(ServiceDefinition::factory(ProfileClaimPairingHasher::class, self::ID, [IdentityResolutionConfiguration::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileClaimPairingHasher => new ProfileClaimPairingHasher(ServiceReference::get($r, IdentityResolutionConfiguration::class)))));
        $context->service(ServiceDefinition::factory(ProfileClaimPairingResolver::class, self::ID, [MySqlIdentityResolutionRepository::class, ProfileClaimPairingHasher::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileClaimPairingResolver => new ProfileClaimPairingResolver(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, ProfileClaimPairingHasher::class)))));
        $context->service(ServiceDefinition::factory(ProfileClaimPairingCreationService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityRateLimiter::class, IdentityFingerprintGenerator::class, ProfileClaimPairingCodeGenerator::class, ProfileClaimPairingHasher::class, IdentityResolutionConfiguration::class, SecurityAuditEventAppender::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileClaimPairingCreationService => new ProfileClaimPairingCreationService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityRateLimiter::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, ProfileClaimPairingCodeGenerator::class), ServiceReference::get($r, ProfileClaimPairingHasher::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(ProfileClaimPairingRevocationService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityFingerprintGenerator::class, SecurityAuditEventAppender::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileClaimPairingRevocationService => new ProfileClaimPairingRevocationService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(GuardianProfileClaimAuthorizationService::class, self::ID, [MySqlIdentityResolutionRepository::class, ProfileClaimPairingResolver::class, IdentityAccessRepository::class, IdentityRateLimiter::class, IdentityFingerprintGenerator::class, StepUpGuard::class, PeopleProfilesConfiguration::class, IdentityResolutionConfiguration::class, SecurityAuditEventAppender::class, PeopleProfileSecurityNotificationService::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): GuardianProfileClaimAuthorizationService => new GuardianProfileClaimAuthorizationService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, ProfileClaimPairingResolver::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityRateLimiter::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, PeopleProfilesConfiguration::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(PlatformProfileClaimAuthorizationService::class, self::ID, [MySqlIdentityResolutionRepository::class, ProfileClaimPairingResolver::class, IdentityAccessRepository::class, IdentityRateLimiter::class, IdentityFingerprintGenerator::class, AuthorizationRequirementGuard::class, StepUpGuard::class, PeopleProfilesConfiguration::class, IdentityResolutionConfiguration::class, SecurityAuditEventAppender::class, PeopleProfileSecurityNotificationService::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PlatformProfileClaimAuthorizationService => new PlatformProfileClaimAuthorizationService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, ProfileClaimPairingResolver::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityRateLimiter::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, PeopleProfilesConfiguration::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(ProfileClaimAcceptanceService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityRateLimiter::class, IdentityFingerprintGenerator::class, StepUpGuard::class, PeopleProfilesConfiguration::class, IdentityResolutionConfiguration::class, SecurityAuditEventAppender::class, PeopleProfileSecurityNotificationService::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileClaimAcceptanceService => new ProfileClaimAcceptanceService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityRateLimiter::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, PeopleProfilesConfiguration::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(ProfileClaimDeclineService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityFingerprintGenerator::class, SecurityAuditEventAppender::class, PeopleProfileSecurityNotificationService::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileClaimDeclineService => new ProfileClaimDeclineService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(ProfileClaimRevocationService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityFingerprintGenerator::class, AuthorizationRequirementGuard::class, StepUpGuard::class, SecurityAuditEventAppender::class, PeopleProfileSecurityNotificationService::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileClaimRevocationService => new ProfileClaimRevocationService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(ProfileVerificationAssertionService::class, self::ID, [MySqlIdentityResolutionRepository::class, PersonCanonicalIdentityResolver::class, IdentityAccessRepository::class, IdentityFingerprintGenerator::class, AuthorizationRequirementGuard::class, StepUpGuard::class, PeopleProfileSecurityNotificationService::class, SecurityAuditEventAppender::class, IdentityResolutionConfiguration::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileVerificationAssertionService => new ProfileVerificationAssertionService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, PersonCanonicalIdentityResolver::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(ProfileVerificationRevocationService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityFingerprintGenerator::class, AuthorizationRequirementGuard::class, StepUpGuard::class, PeopleProfileSecurityNotificationService::class, SecurityAuditEventAppender::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileVerificationRevocationService => new ProfileVerificationRevocationService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(PersonDuplicateResolutionPreflight::class, self::ID, [MySqlIdentityResolutionRepository::class, PersonCanonicalizationParticipant::class, OrganizationAffiliationPersonCanonicalizationParticipant::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PersonDuplicateResolutionPreflight => new PersonDuplicateResolutionPreflight(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, PersonCanonicalizationParticipant::class), ServiceReference::get($r, OrganizationAffiliationPersonCanonicalizationParticipant::class)))));
        $context->service(ServiceDefinition::factory(PersonDuplicateReportService::class, self::ID, [MySqlIdentityResolutionRepository::class, PersonCanonicalIdentityResolver::class, IdentityAccessRepository::class, IdentityRateLimiter::class, IdentityFingerprintGenerator::class, AuthorizationRequirementGuard::class, StepUpGuard::class, PeopleProfileSecurityNotificationService::class, SecurityAuditEventAppender::class, IdentityResolutionConfiguration::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PersonDuplicateReportService => new PersonDuplicateReportService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, PersonCanonicalIdentityResolver::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityRateLimiter::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(PersonDuplicateConsentService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityRateLimiter::class, IdentityFingerprintGenerator::class, StepUpGuard::class, PeopleProfileSecurityNotificationService::class, SecurityAuditEventAppender::class, IdentityResolutionConfiguration::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PersonDuplicateConsentService => new PersonDuplicateConsentService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityRateLimiter::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(PersonDuplicateDismissalService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityFingerprintGenerator::class, AuthorizationRequirementGuard::class, StepUpGuard::class, SecurityAuditEventAppender::class, IdentityResolutionConfiguration::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PersonDuplicateDismissalService => new PersonDuplicateDismissalService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(PersonDuplicateResolutionService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityFingerprintGenerator::class, AuthorizationRequirementGuard::class, StepUpGuard::class, PersonDuplicateResolutionPreflight::class, PersonCanonicalizationParticipant::class, OrganizationAffiliationPersonCanonicalizationParticipant::class, PeopleProfileSecurityNotificationService::class, SecurityAuditEventAppender::class, IdentityResolutionConfiguration::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PersonDuplicateResolutionService => new PersonDuplicateResolutionService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, StepUpGuard::class), ServiceReference::get($r, PersonDuplicateResolutionPreflight::class), ServiceReference::get($r, PersonCanonicalizationParticipant::class), ServiceReference::get($r, OrganizationAffiliationPersonCanonicalizationParticipant::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(PersonDuplicateReviewService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityAccessRepository::class, IdentityFingerprintGenerator::class, AuthorizationRequirementGuard::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PersonDuplicateReviewService => new PersonDuplicateReviewService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityAccessRepository::class), ServiceReference::get($r, IdentityFingerprintGenerator::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(PeopleIdentityResolutionController::class, self::ID, [AuthenticatedRequestGuard::class, IdentityCsrf::class, IdentityAccessView::class, MySqlIdentityResolutionRepository::class, AuthorizationRequirementGuard::class, ProfileClaimPairingCreationService::class, ProfileClaimPairingRevocationService::class, GuardianProfileClaimAuthorizationService::class, PlatformProfileClaimAuthorizationService::class, ProfileClaimAcceptanceService::class, ProfileClaimDeclineService::class, ProfileClaimRevocationService::class, ProfileVerificationAssertionService::class, ProfileVerificationRevocationService::class, PersonDuplicateReportService::class, PersonDuplicateConsentService::class, PersonDuplicateDismissalService::class, PersonDuplicateResolutionService::class, PersonDuplicateReviewService::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PeopleIdentityResolutionController => new PeopleIdentityResolutionController(ServiceReference::get($r, AuthenticatedRequestGuard::class), ServiceReference::get($r, IdentityCsrf::class), ServiceReference::get($r, IdentityAccessView::class), ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, AuthorizationRequirementGuard::class), ServiceReference::get($r, ProfileClaimPairingCreationService::class), ServiceReference::get($r, ProfileClaimPairingRevocationService::class), ServiceReference::get($r, GuardianProfileClaimAuthorizationService::class), ServiceReference::get($r, PlatformProfileClaimAuthorizationService::class), ServiceReference::get($r, ProfileClaimAcceptanceService::class), ServiceReference::get($r, ProfileClaimDeclineService::class), ServiceReference::get($r, ProfileClaimRevocationService::class), ServiceReference::get($r, ProfileVerificationAssertionService::class), ServiceReference::get($r, ProfileVerificationRevocationService::class), ServiceReference::get($r, PersonDuplicateReportService::class), ServiceReference::get($r, PersonDuplicateConsentService::class), ServiceReference::get($r, PersonDuplicateDismissalService::class), ServiceReference::get($r, PersonDuplicateResolutionService::class), ServiceReference::get($r, PersonDuplicateReviewService::class)))));
        $context->service(ServiceDefinition::factory(PeopleIdentityResolutionReadinessCheck::class, self::ID, [IdentityResolutionConfiguration::class, SchemaHealthCheck::class, IdentityResolutionRepository::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PeopleIdentityResolutionReadinessCheck => new PeopleIdentityResolutionReadinessCheck(ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, SchemaHealthCheck::class), ServiceReference::get($r, IdentityResolutionRepository::class)))));
        $context->service(ServiceDefinition::factory(ProfileClaimMaintenanceService::class, self::ID, [MySqlIdentityResolutionRepository::class, IdentityResolutionConfiguration::class, SecurityAuditEventAppender::class, PeopleProfileSecurityNotificationService::class, TransactionManager::class, Clock::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ProfileClaimMaintenanceService => new ProfileClaimMaintenanceService(ServiceReference::get($r, MySqlIdentityResolutionRepository::class), ServiceReference::get($r, IdentityResolutionConfiguration::class), ServiceReference::get($r, SecurityAuditEventAppender::class), ServiceReference::get($r, PeopleProfileSecurityNotificationService::class), ServiceReference::get($r, TransactionManager::class), ServiceReference::get($r, Clock::class)))));
        $context->service(ServiceDefinition::factory(ScheduledProfileClaimMaintenanceTask::class, self::ID, [ProfileClaimMaintenanceService::class], new ClosureServiceFactory(static fn (DependencyResolver $r): ScheduledProfileClaimMaintenanceTask => new ScheduledProfileClaimMaintenanceTask(ServiceReference::get($r, ProfileClaimMaintenanceService::class)))));
        $context->service(ServiceDefinition::factory(PeopleIdentityResolutionVerifyConsoleCommand::class, self::ID, [PeopleIdentityResolutionReadinessCheck::class], new ClosureServiceFactory(static fn (DependencyResolver $r): PeopleIdentityResolutionVerifyConsoleCommand => new PeopleIdentityResolutionVerifyConsoleCommand(ServiceReference::get($r, PeopleIdentityResolutionReadinessCheck::class)))));
        $context->scheduledTask(new ScheduledTaskRegistration(new ScheduledTaskId('people.profile_claims.maintain'), 'Expire bounded profile claim pairings and pending profile claims.', new FixedIntervalSchedule(900), ScheduledProfileClaimMaintenanceTask::class, 120, self::ID));
    }
}
