<?php

declare(strict_types=1);

$section = $view->string('section');
$scope = $view->string('scope');
$csrf = $view->string('csrf_token');
$submission = $view->string('submission_id');
$error = $view->string('error');
$success = $view->string('success');
$hidden = static function () use ($escape, $csrf, $submission): string {
    return '<input type="hidden" name="csrf_token" value="' . $escape->escapeAttribute($csrf) . '"><input type="hidden" name="submission_id" value="' . $escape->escapeAttribute($submission) . '">';
};
?>
<section data-qmdb-fragment-root data-offline-venue-root aria-label="<?= $escape->escapeAttribute($translator->trans('p13.title')) ?>">
    <nav aria-label="<?= $escape->escapeAttribute($translator->trans('p13.navigation')) ?>">
        <?php if ($scope === 'PLATFORM') : ?>
            <a href="/platform/pilots"><?= $escape->escapeText($translator->trans('p13.pilots')) ?></a>
            <a href="/platform/rollouts"><?= $escape->escapeText($translator->trans('p13.rollouts')) ?></a>
        <?php else : ?>
            <a href="/workspace/offline-devices"><?= $escape->escapeText($translator->trans('p13.devices')) ?></a>
            <a href="/workspace/offline-packages"><?= $escape->escapeText($translator->trans('p13.packages')) ?></a>
            <a href="/workspace/offline-sync"><?= $escape->escapeText($translator->trans('p13.sync')) ?></a>
            <a href="/workspace/offline-conflicts"><?= $escape->escapeText($translator->trans('p13.conflicts')) ?></a>
        <?php endif; ?>
    </nav>
    <div role="status" aria-live="polite" aria-atomic="true" data-offline-status>
        <?php if ($error !== '') : ?><p role="alert"><?= $escape->escapeText($translator->trans($error)) ?></p><?php endif; ?>
        <?php if ($success !== '') : ?><p><?= $escape->escapeText($translator->trans($success)) ?></p><?php endif; ?>
        <p><span data-network-status><?= $escape->escapeText($translator->trans('p13.online')) ?></span> · <span data-pending-count>0</span> <?= $escape->escapeText($translator->trans('p13.pending')) ?></p>
    </div>
    <dl class="metric-grid"><?php foreach ($view->array('summary') as $name => $value) : ?><div><dt><?= $escape->escapeText(str_replace('_', ' ', (string) $name)) ?></dt><dd><?= $escape->escapeText((string) $value) ?></dd></div><?php endforeach; ?></dl>

    <?php if ($section === 'pilots') : ?>
        <h2><?= $escape->escapeText($translator->trans('p13.pilots')) ?></h2>
        <form method="post" action="/platform/pilots"><?= $hidden() ?><label><?= $escape->escapeText($translator->trans('p13.code')) ?><input name="code" required maxlength="80" pattern="[A-Z0-9][A-Z0-9_-]{2,79}"></label><label><?= $escape->escapeText($translator->trans('p13.name')) ?><input name="name" required maxlength="191"></label><label><?= $escape->escapeText($translator->trans('p13.scope')) ?><select name="scope"><option>VENUE</option><option>WORKSPACE</option><option>REGION</option><option>NATIONAL_COHORT</option></select></label><label><?= $escape->escapeText($translator->trans('p13.starts')) ?><input type="datetime-local" name="starts_at" required></label><label><?= $escape->escapeText($translator->trans('p13.ends')) ?><input type="datetime-local" name="ends_at" required></label><button type="submit"><?= $escape->escapeText($translator->trans('p13.create')) ?></button></form>
        <div tabindex="0"><table><caption><?= $escape->escapeText($translator->trans('p13.pilot_register')) ?></caption><thead><tr><th scope="col"><?= $escape->escapeText($translator->trans('p13.code')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.name')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.scope')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.status')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.version')) ?></th></tr></thead><tbody><?php foreach ($view->list('pilots') as $item) : ?><tr><td dir="ltr"><?= $escape->escapeText((string) $item['program_code']) ?></td><td><?= $escape->escapeText((string) $item['name']) ?></td><td><?= $escape->escapeText((string) $item['scope_type']) ?></td><td><?= $escape->escapeText((string) $item['status_code']) ?></td><td><?= $escape->escapeText((string) $item['version']) ?></td></tr><?php endforeach; ?></tbody></table></div>
    <?php elseif ($section === 'rollouts') : ?>
        <h2><?= $escape->escapeText($translator->trans('p13.rollouts')) ?></h2>
        <form method="post" action="/platform/rollouts"><?= $hidden() ?><label><?= $escape->escapeText($translator->trans('p13.code')) ?><input name="code" required maxlength="80" pattern="[A-Z0-9][A-Z0-9_-]{2,79}"></label><label><?= $escape->escapeText($translator->trans('p13.name')) ?><input name="name" required maxlength="191"></label><label><?= $escape->escapeText($translator->trans('p13.scope')) ?><select name="scope"><option>REGIONAL</option><option>STATE</option><option>NATIONAL</option><option>COHORT</option></select></label><label><?= $escape->escapeText($translator->trans('p13.maximum_wave')) ?><input type="number" name="maximum_wave_size" min="1" max="500" required></label><button type="submit"><?= $escape->escapeText($translator->trans('p13.create')) ?></button></form>
        <div tabindex="0"><table><caption><?= $escape->escapeText($translator->trans('p13.rollout_register')) ?></caption><thead><tr><th scope="col"><?= $escape->escapeText($translator->trans('p13.code')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.name')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.scope')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.status')) ?></th></tr></thead><tbody><?php foreach ($view->list('rollouts') as $item) : ?><tr><td dir="ltr"><?= $escape->escapeText((string) $item['rollout_code']) ?></td><td><?= $escape->escapeText((string) $item['name']) ?></td><td><?= $escape->escapeText((string) $item['scope_type']) ?></td><td><?= $escape->escapeText((string) $item['status_code']) ?></td></tr><?php endforeach; ?></tbody></table></div>
    <?php elseif ($section === 'devices') : ?>
        <h2><?= $escape->escapeText($translator->trans('p13.devices')) ?></h2>
        <form method="post" action="/workspace/offline-devices"><?= $hidden() ?><label><?= $escape->escapeText($translator->trans('p13.venue_id')) ?><input name="venue_id" required maxlength="36" dir="ltr"></label><label><?= $escape->escapeText($translator->trans('p13.code')) ?><input name="code" required maxlength="80"></label><label><?= $escape->escapeText($translator->trans('p13.name')) ?><input name="name" required maxlength="191"></label><label><?= $escape->escapeText($translator->trans('p13.device_type')) ?><select name="device_type"><option>BROWSER</option><option>VENUE_NODE</option><option>TABLET</option><option>DESKTOP</option></select></label><label><?= $escape->escapeText($translator->trans('p13.platform')) ?><input name="platform" required maxlength="32"></label><label><?= $escape->escapeText($translator->trans('p13.public_key')) ?><textarea name="public_key" required maxlength="128" dir="ltr"></textarea></label><button type="submit"><?= $escape->escapeText($translator->trans('p13.register')) ?></button></form>
        <div tabindex="0"><table><caption><?= $escape->escapeText($translator->trans('p13.device_register')) ?></caption><thead><tr><th scope="col"><?= $escape->escapeText($translator->trans('p13.code')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.name')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.device_type')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.status')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.version')) ?></th></tr></thead><tbody><?php foreach ($view->list('devices') as $item) : ?><tr><td><?= $escape->escapeText((string) $item['installation_code']) ?></td><td><?= $escape->escapeText((string) $item['display_name']) ?></td><td><?= $escape->escapeText((string) $item['device_type']) ?></td><td><?= $escape->escapeText((string) $item['status_code']) ?></td><td><?= $escape->escapeText((string) $item['version']) ?></td></tr><?php endforeach; ?></tbody></table></div>
    <?php elseif ($section === 'packages') : ?>
        <h2><?= $escape->escapeText($translator->trans('p13.packages')) ?></h2>
        <form method="post" action="/workspace/offline-packages"><?= $hidden() ?><label><?= $escape->escapeText($translator->trans('p13.device_id')) ?><input name="device_id" required maxlength="36" dir="ltr"></label><label><?= $escape->escapeText($translator->trans('p13.edition_id')) ?><input name="edition_id" required maxlength="36" dir="ltr"></label><button type="submit"><?= $escape->escapeText($translator->trans('p13.prepare_package')) ?></button></form>
        <div tabindex="0"><table><caption><?= $escape->escapeText($translator->trans('p13.package_register')) ?></caption><thead><tr><th scope="col"><?= $escape->escapeText($translator->trans('p13.code')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.status')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.expires')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.bytes')) ?></th></tr></thead><tbody><?php foreach ($view->list('packages') as $item) : ?><tr><td><?= $escape->escapeText((string) $item['package_code']) ?></td><td><?= $escape->escapeText((string) $item['status_code']) ?></td><td><?= $escape->escapeText((string) $item['expires_at']) ?></td><td><?= $escape->escapeText((string) $item['byte_size']) ?></td></tr><?php endforeach; ?></tbody></table></div>
    <?php elseif ($section === 'sync') : ?>
        <h2><?= $escape->escapeText($translator->trans('p13.sync')) ?></h2><div tabindex="0"><table><caption><?= $escape->escapeText($translator->trans('p13.sync_register')) ?></caption><thead><tr><th scope="col">ID</th><th scope="col"><?= $escape->escapeText($translator->trans('p13.status')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.changes')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.conflicts')) ?></th></tr></thead><tbody><?php foreach ($view->list('sync_sessions') as $item) : ?><tr><td dir="ltr"><?= $escape->escapeText((string) $item['public_id']) ?></td><td><?= $escape->escapeText((string) $item['status_code']) ?></td><td><?= $escape->escapeText((string) $item['change_count']) ?></td><td><?= $escape->escapeText((string) $item['conflict_count']) ?></td></tr><?php endforeach; ?></tbody></table></div>
    <?php else : ?>
        <h2><?= $escape->escapeText($translator->trans('p13.conflicts')) ?></h2><div tabindex="0"><table><caption><?= $escape->escapeText($translator->trans('p13.conflict_register')) ?></caption><thead><tr><th scope="col">ID</th><th scope="col"><?= $escape->escapeText($translator->trans('p13.type')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.status')) ?></th><th scope="col"><?= $escape->escapeText($translator->trans('p13.version')) ?></th></tr></thead><tbody><?php foreach ($view->list('conflicts') as $item) : ?><tr><td dir="ltr"><?= $escape->escapeText((string) $item['public_id']) ?></td><td><?= $escape->escapeText((string) $item['conflict_type']) ?></td><td><?= $escape->escapeText((string) $item['status_code']) ?></td><td><?= $escape->escapeText((string) $item['version']) ?></td></tr><?php endforeach; ?></tbody></table></div>
    <?php endif; ?>

    <?php if ($scope === 'WORKSPACE') : ?><section aria-labelledby="offline-runtime-title"><h2 id="offline-runtime-title"><?= $escape->escapeText($translator->trans('p13.offline_runtime')) ?></h2><button type="button" data-offline-sync><?= $escape->escapeText($translator->trans('p13.sync_now')) ?></button><button type="button" data-offline-clear><?= $escape->escapeText($translator->trans('p13.clear_offline')) ?></button><p id="offline-runtime-help"><?= $escape->escapeText($translator->trans('p13.offline_help')) ?></p></section><?php endif; ?>
</section>
