<?php

declare(strict_types=1);

namespace Qmdb\Modules\IdentitySecurityNotifications\Domain;

enum AccountSecurityNotificationType: string
{
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case MFA_ENABLED = 'MFA_ENABLED';
    case MFA_DISABLED = 'MFA_DISABLED';
    case TOTP_AUTHENTICATOR_ADDED = 'TOTP_AUTHENTICATOR_ADDED';
    case TOTP_AUTHENTICATOR_REMOVED = 'TOTP_AUTHENTICATOR_REMOVED';
    case PASSKEY_ADDED = 'PASSKEY_ADDED';
    case PASSKEY_REMOVED = 'PASSKEY_REMOVED';
    case RECOVERY_CODES_REGENERATED = 'RECOVERY_CODES_REGENERATED';
    case RECOVERY_CODE_USED = 'RECOVERY_CODE_USED';
    case PASSKEY_SUSPENDED = 'PASSKEY_SUSPENDED';
    case PLATFORM_ROLE_ASSIGNED = 'PLATFORM_ROLE_ASSIGNED';
    case PLATFORM_ROLE_REVOKED = 'PLATFORM_ROLE_REVOKED';
    case WORKSPACE_ROLE_ASSIGNED = 'WORKSPACE_ROLE_ASSIGNED';
    case WORKSPACE_ROLE_REVOKED = 'WORKSPACE_ROLE_REVOKED';
    case TEMPORARY_PRIVILEGE_REQUESTED = 'TEMPORARY_PRIVILEGE_REQUESTED';
    case TEMPORARY_PRIVILEGE_APPROVED = 'TEMPORARY_PRIVILEGE_APPROVED';
    case TEMPORARY_PRIVILEGE_REJECTED = 'TEMPORARY_PRIVILEGE_REJECTED';
    case TEMPORARY_PRIVILEGE_ACTIVATED = 'TEMPORARY_PRIVILEGE_ACTIVATED';
    case TEMPORARY_PRIVILEGE_REVOKED = 'TEMPORARY_PRIVILEGE_REVOKED';
    case TEMPORARY_PRIVILEGE_EXPIRED = 'TEMPORARY_PRIVILEGE_EXPIRED';
    case SUPPORT_ACCESS_REQUESTED = 'SUPPORT_ACCESS_REQUESTED';
    case SUPPORT_ACCESS_PARTIALLY_APPROVED = 'SUPPORT_ACCESS_PARTIALLY_APPROVED';
    case SUPPORT_ACCESS_APPROVED = 'SUPPORT_ACCESS_APPROVED';
    case SUPPORT_ACCESS_ACTIVATED = 'SUPPORT_ACCESS_ACTIVATED';
    case SUPPORT_ACCESS_ENDED = 'SUPPORT_ACCESS_ENDED';
    case SUPPORT_ACCESS_REVOKED = 'SUPPORT_ACCESS_REVOKED';
    case SUPPORT_ACCESS_REVIEW_REQUIRED = 'SUPPORT_ACCESS_REVIEW_REQUIRED';
    case SUPPORT_ACCESS_REVIEW_OVERDUE = 'SUPPORT_ACCESS_REVIEW_OVERDUE';
    case SUPPORT_ACCESS_REVIEW_COMPLETED = 'SUPPORT_ACCESS_REVIEW_COMPLETED';
    case BREAK_GLASS_ACTIVATED = 'BREAK_GLASS_ACTIVATED';
    case BREAK_GLASS_ENDED = 'BREAK_GLASS_ENDED';
    case BREAK_GLASS_EXPIRED = 'BREAK_GLASS_EXPIRED';
    case BREAK_GLASS_REVIEW_REQUIRED = 'BREAK_GLASS_REVIEW_REQUIRED';
    case BREAK_GLASS_REVIEW_OVERDUE = 'BREAK_GLASS_REVIEW_OVERDUE';
    case BREAK_GLASS_REVIEW_COMPLETED = 'BREAK_GLASS_REVIEW_COMPLETED';
    case ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED';
    case ACCOUNT_REACTIVATED = 'ACCOUNT_REACTIVATED';
}
