<?php

declare(strict_types=1);

namespace Qmdb\Modules\IdentitySecurityNotifications\Domain;

enum AccountSecurityNotificationType: string
{
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case MFA_ENABLED = 'MFA_ENABLED';
    case MFA_DISABLED = 'MFA_DISABLED';
    case TOTP_AUTHENTICATOR_ADDED = 'TOTP_AUTHENTICATOR_ADDED';
    case TOTP_AUTHENTICATOR_REMOVED = 'TOTP_AUTHENTICATOR_REMOVED';
    case PASSKEY_ADDED = 'PASSKEY_ADDED';
    case PASSKEY_REMOVED = 'PASSKEY_REMOVED';
    case RECOVERY_CODES_REGENERATED = 'RECOVERY_CODES_REGENERATED';
    case RECOVERY_CODE_USED = 'RECOVERY_CODE_USED';
    case PASSKEY_SUSPENDED = 'PASSKEY_SUSPENDED';
}
