<?php

declare(strict_types=1);

namespace Qmdb\Modules\IdentityResolution\Domain;

enum PersonDuplicateResolutionOutcome: string
{
    case NOT_DUPLICATE = 'NOT_DUPLICATE';
    case CANONICALIZED = 'CANONICALIZED';
    case IDENTITY_LINK_CONFLICT = 'IDENTITY_LINK_CONFLICT';
    case DEMOGRAPHIC_CONFLICT = 'DEMOGRAPHIC_CONFLICT';
    case GEOGRAPHY_CONFLICT = 'GEOGRAPHY_CONFLICT';
    case MEMORIZER_PROGRESS_CONFLICT = 'MEMORIZER_PROGRESS_CONFLICT';
    case ORGANIZATION_AFFILIATION_CONFLICT = 'ORGANIZATION_AFFILIATION_CONFLICT';
    case CONSENT_UNAVAILABLE = 'CONSENT_UNAVAILABLE';
    case CONSENT_DECLINED = 'CONSENT_DECLINED';
    case AFFECTED_RECORD_LIMIT_EXCEEDED = 'AFFECTED_RECORD_LIMIT_EXCEEDED';
}
