<?php

declare(strict_types=1);

namespace Qmdb\Modules\QuranReferenceGovernance\Infrastructure\Persistence;

use PDO;
use Qmdb\Modules\QuranReferenceGovernance\Application\QuranPublicReferenceRepository;
use Qmdb\Shared\Database\Connection\DatabaseConnectionProvider;

final readonly class MySqlQuranPublicReferenceRepository implements QuranPublicReferenceRepository
{
    public function __construct(private DatabaseConnectionProvider $connections) {}
    public function home(): ?array { $row=$this->connections->connection()->query("SELECT r.release_code,r.release_version,s.surah_count,s.ayah_count FROM quran_reference_releases r INNER JOIN quran_release_content_summaries s ON s.release_id=r.id WHERE r.status='ACTIVE' ORDER BY r.id DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC); return is_array($row)?$row:null; }
    public function surahs(): array { return $this->rows("SELECT s.surah_number,s.ayah_count,s.arabic_name,s.transliterated_name,s.english_name,s.revelation_type,s.ruku_count FROM quran_surahs s INNER JOIN quran_reference_releases r ON r.id=s.release_id AND r.status='ACTIVE' ORDER BY s.surah_number ASC"); }
    public function surah(int $number): ?array { $statement=$this->connections->connection()->prepare("SELECT s.id,s.surah_number,s.ayah_count,s.arabic_name,s.transliterated_name,s.english_name,s.revelation_type,s.ruku_count FROM quran_surahs s INNER JOIN quran_reference_releases r ON r.id=s.release_id AND r.status='ACTIVE' WHERE s.surah_number=:number"); $statement->execute([':number'=>$number]); $surah=$statement->fetch(PDO::FETCH_ASSOC); if(!is_array($surah)) return null; $ayahs=$this->connections->connection()->prepare('SELECT surah_number,ayah_number,global_ayah_ordinal,canonical_uthmani_text FROM quran_ayahs WHERE surah_id=:surah ORDER BY ayah_number ASC'); $ayahs->execute([':surah'=>$surah['id']]); unset($surah['id']); return ['surah'=>$surah,'ayahs'=>$this->rowsFrom($ayahs)]; }
    public function ayah(int $surah, int $ayah): ?array { $statement=$this->connections->connection()->prepare("SELECT a.surah_number,a.ayah_number,a.global_ayah_ordinal,a.canonical_uthmani_text,s.arabic_name,s.transliterated_name,s.english_name FROM quran_ayahs a INNER JOIN quran_reference_releases r ON r.id=a.release_id AND r.status='ACTIVE' INNER JOIN quran_surahs s ON s.id=a.surah_id WHERE a.surah_number=:surah AND a.ayah_number=:ayah"); $statement->execute([':surah'=>$surah,':ayah'=>$ayah]); $row=$statement->fetch(PDO::FETCH_ASSOC); return is_array($row)?$row:null; }
    public function partitions(string $type, int $number): array { $statement=$this->connections->connection()->prepare("SELECT p.partition_type,p.partition_number,p.start_global_ayah_ordinal,p.end_global_ayah_ordinal,sa.surah_number start_surah,sa.ayah_number start_ayah,ea.surah_number end_surah,ea.ayah_number end_ayah FROM quran_partitions p INNER JOIN quran_reference_releases r ON r.id=p.release_id AND r.status='ACTIVE' INNER JOIN quran_ayahs sa ON sa.id=p.start_ayah_id INNER JOIN quran_ayahs ea ON ea.id=p.end_ayah_id WHERE p.partition_type=:type AND p.partition_number=:number ORDER BY p.source_index ASC"); $statement->execute([':type'=>$type,':number'=>$number]); return $this->rowsFrom($statement); }
    public function sajdahs(): array { return $this->rows("SELECT m.sajdah_index,m.surah_number,m.ayah_number,m.source_sajdah_type,a.canonical_uthmani_text FROM quran_sajdah_markers m INNER JOIN quran_reference_releases r ON r.id=m.release_id AND r.status='ACTIVE' INNER JOIN quran_ayahs a ON a.id=m.ayah_id ORDER BY m.sajdah_index ASC"); }
    public function search(string $mode, string $query, int $limit): array { if($mode==='EXACT_UTHMANI'){ $statement=$this->connections->connection()->prepare("SELECT a.surah_number,a.ayah_number,a.canonical_uthmani_text FROM quran_ayahs a INNER JOIN quran_reference_releases r ON r.id=a.release_id AND r.status='ACTIVE' WHERE LOCATE(:query,a.canonical_uthmani_text)>0 ORDER BY a.global_ayah_ordinal ASC LIMIT :limit"); } else { $statement=$this->connections->connection()->prepare("SELECT a.surah_number,a.ayah_number,a.canonical_uthmani_text FROM quran_ayah_search_texts t INNER JOIN quran_search_corpora c ON c.id=t.corpus_id AND c.status='ACTIVE' INNER JOIN quran_ayahs a ON a.id=t.ayah_id WHERE LOCATE(:query,t.simple_clean_text)>0 ORDER BY t.global_ayah_ordinal ASC LIMIT :limit"); } $statement->bindValue(':query',$query); $statement->bindValue(':limit',$limit,PDO::PARAM_INT); $statement->execute(); return $this->rowsFrom($statement); }
    /** @return list<array<string,int|string>> */ private function rows(string $sql): array { return $this->rowsFrom($this->connections->connection()->query($sql)); }
    /** @return list<array<string,int|string>> */ private function rowsFrom(\PDOStatement $statement): array { $rows=$statement->fetchAll(PDO::FETCH_ASSOC); return is_array($rows)?array_map(static fn(array $row):array=>$row,$rows):[]; }
}
