<?php

declare(strict_types=1);

namespace Qmdb\Modules\PilotOfflineRollout\Infrastructure\Migration;

use Qmdb\Modules\ProductionHardening\Infrastructure\Migration\CreateOperationalAssuranceMigration;
use Qmdb\Shared\Schema\Migration\Migration;
use Qmdb\Shared\Schema\Migration\MigrationId;
use Qmdb\Shared\Schema\Migration\MigrationStepId;
use Qmdb\Shared\Schema\Migration\SqlMigrationStep;

/** QMDB-MIG-020: frozen platform and offline-operation authority. */
final readonly class CreateOfflinePlatformFoundationMigration implements Migration
{
    public function id(): MigrationId
    {
        return new MigrationId('20260928100000_create_offline_platform_foundation');
    }

    public function description(): string
    {
        return 'Create frozen P13 platform, venue-device, offline-package, submission, sync, conflict, and reconciliation records.';
    }

    public function dependencies(): array
    {
        return [(new CreateOperationalAssuranceMigration())->id()];
    }

    public function reversible(): bool
    {
        return false;
    }

    public function down(): array
    {
        return [];
    }

    public function up(): array
    {
        return [
            $this->step('001_feature_flags', 'Create governed feature flags.', "CREATE TABLE feature_flags (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, flag_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, owning_module VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, version INT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_feature_flag_public(public_id), UNIQUE KEY uq_p13_feature_flag_code(flag_code), CONSTRAINT ck_p13_feature_flag CHECK(status_code IN ('ACTIVE','RETIRED') AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('002_feature_flag_versions', 'Create immutable feature-flag versions.', "CREATE TABLE feature_flag_versions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, feature_flag_id BIGINT UNSIGNED NOT NULL, version_number INT UNSIGNED NOT NULL, scope_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, enabled_flag TINYINT(1) NOT NULL, configuration_json JSON NOT NULL, checksum BINARY(32) NOT NULL, effective_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_feature_flag_version_public(public_id), UNIQUE KEY uq_p13_feature_flag_version(feature_flag_id,version_number), CONSTRAINT fk_p13_feature_flag_version_flag FOREIGN KEY(feature_flag_id) REFERENCES feature_flags(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_feature_flag_version CHECK(version_number>=1 AND scope_code IN ('PLATFORM','WORKSPACE','VENUE') AND enabled_flag IN (0,1) AND JSON_VALID(configuration_json))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('003_configuration_versions', 'Create immutable operational configuration versions.', "CREATE TABLE configuration_versions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, configuration_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, version_number INT UNSIGNED NOT NULL, configuration_json JSON NOT NULL, checksum BINARY(32) NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, effective_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_configuration_public(public_id), UNIQUE KEY uq_p13_configuration_version(configuration_code,version_number), KEY ix_p13_configuration_active(configuration_code,status_code,version_number), CONSTRAINT ck_p13_configuration CHECK(version_number>=1 AND status_code IN ('ACTIVE','RETIRED') AND JSON_VALID(configuration_json))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('004_operational_announcements', 'Create scoped operational announcements.', "CREATE TABLE operational_announcements (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NULL, announcement_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, locale VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, safe_title VARCHAR(191) NOT NULL, safe_body TEXT NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, starts_at DATETIME(6) NOT NULL, ends_at DATETIME(6) NOT NULL, version INT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_announcement_public(public_id), KEY ix_p13_announcement_current(workspace_id,status_code,starts_at,ends_at,id), CONSTRAINT fk_p13_announcement_workspace FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_announcement CHECK(locale IN ('en','ar') AND status_code IN ('DRAFT','ACTIVE','EXPIRED','REVOKED') AND ends_at>starts_at AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('005_background_job_ledger', 'Create bounded background job ledger.', "CREATE TABLE background_job_ledger (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NULL, job_type VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, resource_public_id BINARY(16) NULL, operation_key BINARY(32) NOT NULL, status_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0, available_at DATETIME(6) NOT NULL, leased_until DATETIME(6) NULL, lease_token BINARY(16) NULL, safe_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, completed_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_job_public(public_id), UNIQUE KEY uq_p13_job_operation(job_type,operation_key), KEY ix_p13_job_due(job_type,status_code,available_at,id), CONSTRAINT fk_p13_job_workspace FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_job CHECK(status_code IN ('PENDING','PROCESSING','RETRY','COMPLETED','FAILED','DEAD_LETTER') AND attempt_count<=10)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('006_dead_letter_records', 'Create generic governed dead letters.', "CREATE TABLE dead_letter_records (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NULL, source_kind VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_public_id BINARY(16) NOT NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, context_hash BINARY(32) NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, created_at DATETIME(6) NOT NULL, resolved_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_dead_letter_public(public_id), UNIQUE KEY uq_p13_dead_letter_source(source_kind,source_public_id), KEY ix_p13_dead_letter_status(workspace_id,status_code,created_at,id), CONSTRAINT fk_p13_dead_letter_workspace FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_dead_letter CHECK(status_code IN ('OPEN','REQUEUED','RESOLVED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('007_edge_node_registrations', 'Create tenant- and venue-bound offline device authority.', "CREATE TABLE venue_edge_node_registrations (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, venue_id BIGINT UNSIGNED NOT NULL, installation_code VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, display_name VARCHAR(191) NOT NULL, device_type VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, platform_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, public_key VARBINARY(64) NOT NULL, public_key_sha256 BINARY(32) NOT NULL, scope_manifest_sha256 BINARY(32) NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, version INT UNSIGNED NOT NULL DEFAULT 1, registered_by_account_id BIGINT UNSIGNED NOT NULL, activated_by_account_id BIGINT UNSIGNED NULL, last_seen_at DATETIME(6) NULL, last_sync_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, activated_at DATETIME(6) NULL, suspended_at DATETIME(6) NULL, revoked_at DATETIME(6) NULL, expired_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_edge_public(public_id), UNIQUE KEY uq_p13_edge_code(workspace_id,installation_code), UNIQUE KEY uq_p13_edge_workspace_id(workspace_id,id), KEY ix_p13_edge_venue(workspace_id,venue_id,status_code,id), CONSTRAINT fk_p13_edge_workspace FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_edge_venue FOREIGN KEY(workspace_id,venue_id) REFERENCES competition_venues(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_edge_registrar FOREIGN KEY(registered_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_edge_activator FOREIGN KEY(activated_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_edge CHECK(device_type IN ('BROWSER','VENUE_NODE','TABLET','DESKTOP') AND status_code IN ('PENDING','ACTIVE','SUSPENDED','REVOKED','EXPIRED') AND OCTET_LENGTH(public_key)=32 AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('008_offline_assignment_packages', 'Create minimized signed offline assignment packages.', "CREATE TABLE offline_assignment_packages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, venue_edge_node_registration_id BIGINT UNSIGNED NOT NULL, competition_edition_id BIGINT UNSIGNED NOT NULL, package_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, schema_version SMALLINT UNSIGNED NOT NULL, scope_version INT UNSIGNED NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, manifest_canonical_json JSON NOT NULL, manifest_sha256 BINARY(32) NOT NULL, artifact_sha256 BINARY(32) NOT NULL, signing_key_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, detached_signature VARBINARY(128) NOT NULL, encryption_key_reference_hash BINARY(32) NOT NULL, byte_size BIGINT UNSIGNED NOT NULL, generated_at DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL, downloaded_at DATETIME(6) NULL, activated_at DATETIME(6) NULL, revoked_at DATETIME(6) NULL, superseded_at DATETIME(6) NULL, superseded_by_package_id BIGINT UNSIGNED NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_by_account_id BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_package_public(public_id), UNIQUE KEY uq_p13_package_code(workspace_id,package_code), UNIQUE KEY uq_p13_package_workspace_id(workspace_id,id), KEY ix_p13_package_current(workspace_id,venue_edge_node_registration_id,competition_edition_id,status_code,expires_at,id), KEY ix_p13_package_expiry(status_code,expires_at,id), CONSTRAINT fk_p13_package_workspace FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_package_device FOREIGN KEY(workspace_id,venue_edge_node_registration_id) REFERENCES venue_edge_node_registrations(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_package_edition FOREIGN KEY(workspace_id,competition_edition_id) REFERENCES competition_editions(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_package_supersession FOREIGN KEY(workspace_id,superseded_by_package_id) REFERENCES offline_assignment_packages(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_package_creator FOREIGN KEY(created_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_package CHECK(schema_version>=1 AND scope_version>=1 AND status_code IN ('PREPARING','READY','DOWNLOADED','ACTIVE','EXPIRED','REVOKED','SUPERSEDED','FAILED') AND expires_at>generated_at AND JSON_VALID(manifest_canonical_json) AND byte_size<=268435456 AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('009_offline_submission_events', 'Create immutable device-proposed offline operations.', "CREATE TABLE offline_submission_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, offline_assignment_package_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NOT NULL, client_change_uuid BINARY(16) NOT NULL, device_sequence BIGINT UNSIGNED NOT NULL, entity_type VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, entity_public_id BINARY(16) NOT NULL, operation_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, expected_record_version INT UNSIGNED NOT NULL, payload_schema_version SMALLINT UNSIGNED NOT NULL, payload_ciphertext MEDIUMBLOB NOT NULL, payload_sha256 BINARY(32) NOT NULL, client_occurred_at DATETIME(6) NULL, received_at DATETIME(6) NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_submission_public(public_id), UNIQUE KEY uq_p13_submission_change(device_id,client_change_uuid), UNIQUE KEY uq_p13_submission_sequence(device_id,device_sequence), UNIQUE KEY uq_p13_submission_workspace_id(workspace_id,id), KEY ix_p13_submission_package(workspace_id,offline_assignment_package_id,status_code,id), CONSTRAINT fk_p13_submission_package FOREIGN KEY(workspace_id,offline_assignment_package_id) REFERENCES offline_assignment_packages(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_submission_device FOREIGN KEY(workspace_id,device_id) REFERENCES venue_edge_node_registrations(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_submission CHECK(device_sequence>=1 AND expected_record_version>=1 AND payload_schema_version>=1 AND status_code IN ('RECEIVED','ACCEPTED','REJECTED','CONFLICT') AND operation_code IN ('PARTICIPANT_CHECK_IN','PARTICIPANT_ABSENT','PARTICIPANT_CALLED','PARTICIPANT_READY','PERFORMANCE_STARTED','PERFORMANCE_INTERRUPTED','PERFORMANCE_RESUMED','PERFORMANCE_COMPLETED','SCORE_DRAFT_SAVED','SCORE_SHEET_SUBMITTED','VENUE_INCIDENT_RECORDED','OPERATIONAL_NOTE_RECORDED','JUDGE_ACKNOWLEDGEMENT_RECORDED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('010_synchronization_batches', 'Create bounded device sync sessions.', "CREATE TABLE synchronization_batches (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, venue_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NOT NULL, offline_assignment_package_id BIGINT UNSIGNED NOT NULL, client_session_uuid BINARY(16) NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, first_local_sequence BIGINT UNSIGNED NULL, last_local_sequence BIGINT UNSIGNED NULL, change_count SMALLINT UNSIGNED NOT NULL DEFAULT 0, accepted_count SMALLINT UNSIGNED NOT NULL DEFAULT 0, rejected_count SMALLINT UNSIGNED NOT NULL DEFAULT 0, conflict_count SMALLINT UNSIGNED NOT NULL DEFAULT 0, payload_bytes INT UNSIGNED NOT NULL DEFAULT 0, version INT UNSIGNED NOT NULL DEFAULT 1, opened_at DATETIME(6) NOT NULL, completed_at DATETIME(6) NULL, failed_at DATETIME(6) NULL, expires_at DATETIME(6) NOT NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_sync_public(public_id), UNIQUE KEY uq_p13_sync_client(device_id,client_session_uuid), UNIQUE KEY uq_p13_sync_workspace_id(workspace_id,id), KEY ix_p13_sync_status(workspace_id,venue_id,status_code,opened_at,id), KEY ix_p13_sync_expiry(status_code,expires_at,id), CONSTRAINT fk_p13_sync_device FOREIGN KEY(workspace_id,device_id) REFERENCES venue_edge_node_registrations(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_sync_package FOREIGN KEY(workspace_id,offline_assignment_package_id) REFERENCES offline_assignment_packages(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_sync_venue FOREIGN KEY(workspace_id,venue_id) REFERENCES competition_venues(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_sync CHECK(status_code IN ('OPENED','RECEIVING','VALIDATING','APPLYING','CONFLICTED','COMPLETED','FAILED','EXPIRED') AND change_count<=100 AND payload_bytes<=2097152 AND expires_at>opened_at AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('011_synchronization_conflicts', 'Create private explicit synchronization conflicts.', "CREATE TABLE synchronization_conflicts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, synchronization_batche_id BIGINT UNSIGNED NOT NULL, offline_submission_event_id BIGINT UNSIGNED NOT NULL, conflict_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, server_version INT UNSIGNED NULL, server_state_sha256 BINARY(32) NOT NULL, status_code VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, assigned_at DATETIME(6) NULL, resolved_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_conflict_public(public_id), UNIQUE KEY uq_p13_conflict_submission(offline_submission_event_id), UNIQUE KEY uq_p13_conflict_workspace_id(workspace_id,id), KEY ix_p13_conflict_queue(workspace_id,status_code,created_at,id), CONSTRAINT fk_p13_conflict_batch FOREIGN KEY(workspace_id,synchronization_batche_id) REFERENCES synchronization_batches(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_conflict_submission FOREIGN KEY(workspace_id,offline_submission_event_id) REFERENCES offline_submission_events(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_conflict CHECK(conflict_type IN ('VERSION_MISMATCH','DUPLICATE_CREATE','ENTITY_REMOVED','ENTITY_SUPERSEDED','SCOPE_CHANGED','PERMISSION_REVOKED','INVALID_TRANSITION','SOURCE_CHANGED','PACKAGE_STALE') AND status_code IN ('OPEN','ASSIGNED','UNDER_REVIEW','RESOLVED_ACCEPT_SERVER','RESOLVED_ACCEPT_CLIENT_PROPOSAL','RESOLVED_MANUAL','DISMISSED') AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('012_venue_reconciliation_reports', 'Create immutable venue reconciliation evidence.', "CREATE TABLE venue_reconciliation_reports (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, synchronization_batche_id BIGINT UNSIGNED NOT NULL, accepted_count INT UNSIGNED NOT NULL, rejected_count INT UNSIGNED NOT NULL, conflict_count INT UNSIGNED NOT NULL, first_sequence BIGINT UNSIGNED NULL, last_sequence BIGINT UNSIGNED NULL, evidence_sha256 BINARY(32) NOT NULL, outcome_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, completed_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_reconciliation_public(public_id), UNIQUE KEY uq_p13_reconciliation_batch(synchronization_batche_id), CONSTRAINT fk_p13_reconciliation_batch FOREIGN KEY(workspace_id,synchronization_batche_id) REFERENCES synchronization_batches(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_reconciliation CHECK(outcome_code IN ('PASS','DRIFT','FAILED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
        ];
    }

    private function step(string $id, string $description, string $sql): SqlMigrationStep
    {
        return new SqlMigrationStep(new MigrationStepId($id), $description, $sql);
    }
}
