<?php

declare(strict_types=1);

namespace Qmdb\Modules\PilotOfflineRollout\Infrastructure\Migration;

use Qmdb\Shared\Schema\Migration\Migration;
use Qmdb\Shared\Schema\Migration\MigrationId;
use Qmdb\Shared\Schema\Migration\MigrationStepId;
use Qmdb\Shared\Schema\Migration\SqlMigrationStep;

/** Approved P13 extension for governed pilot and bounded rollout control. */
final readonly class CreatePilotRolloutControlPlaneMigration implements Migration
{
    public function id(): MigrationId
    {
        return new MigrationId('20260928101000_create_pilot_rollout_control_plane');
    }

    public function description(): string
    {
        return 'Create pilot programs, site readiness, incidents, findings, rollout plans, waves, decisions, and health evidence.';
    }

    public function dependencies(): array
    {
        return [(new CreateOfflinePlatformFoundationMigration())->id()];
    }

    public function reversible(): bool
    {
        return false;
    }

    public function down(): array
    {
        return [];
    }

    public function up(): array
    {
        return [
            $this->step('001_pilot_programs', 'Create platform-governed pilot programs.', "CREATE TABLE pilot_programs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, program_code VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, name VARCHAR(191) NOT NULL, description TEXT NULL, scope_type VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, planned_start_at DATETIME(6) NOT NULL, planned_end_at DATETIME(6) NOT NULL, status_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_by_account_id BIGINT UNSIGNED NOT NULL, approved_by_account_id BIGINT UNSIGNED NULL, started_at DATETIME(6) NULL, paused_at DATETIME(6) NULL, completed_at DATETIME(6) NULL, cancelled_at DATETIME(6) NULL, failed_at DATETIME(6) NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_pilot_public(public_id), UNIQUE KEY uq_p13_pilot_code(program_code), KEY ix_p13_pilot_status(status_code,planned_start_at,id), CONSTRAINT fk_p13_pilot_creator FOREIGN KEY(created_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_approver FOREIGN KEY(approved_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_pilot CHECK(scope_type IN ('VENUE','WORKSPACE','REGION','NATIONAL_COHORT') AND status_code IN ('DRAFT','READINESS_REVIEW','APPROVED','ACTIVE','PAUSED','COMPLETED','CANCELLED','FAILED') AND planned_end_at>planned_start_at AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('002_pilot_sites', 'Bind pilot sites to authoritative tenant and competition scope.', "CREATE TABLE pilot_sites (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, pilot_program_id BIGINT UNSIGNED NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, venue_id BIGINT UNSIGNED NOT NULL, edition_id BIGINT UNSIGNED NOT NULL, operational_owner_account_id BIGINT UNSIGNED NOT NULL, status_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, readiness_expires_at DATETIME(6) NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_pilot_site_public(public_id), UNIQUE KEY uq_p13_pilot_site(pilot_program_id,workspace_id,venue_id,edition_id), UNIQUE KEY uq_p13_pilot_site_workspace_id(workspace_id,id), KEY ix_p13_pilot_site_status(pilot_program_id,status_code,id), CONSTRAINT fk_p13_pilot_site_program FOREIGN KEY(pilot_program_id) REFERENCES pilot_programs(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_site_venue FOREIGN KEY(workspace_id,venue_id) REFERENCES competition_venues(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_site_edition FOREIGN KEY(workspace_id,edition_id) REFERENCES competition_editions(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_site_owner FOREIGN KEY(operational_owner_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_pilot_site CHECK(status_code IN ('ASSIGNED','READINESS_REVIEW','READY','ACTIVE','PAUSED','COMPLETED','CANCELLED') AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('003_pilot_readiness', 'Create evidence-bound pilot readiness results.', "CREATE TABLE pilot_site_readiness_checks (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, pilot_site_id BIGINT UNSIGNED NOT NULL, check_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, blocking_flag TINYINT(1) NOT NULL, result_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, evidence_reference_hash BINARY(32) NOT NULL, evaluated_by_account_id BIGINT UNSIGNED NOT NULL, evaluated_at DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_readiness_public(public_id), UNIQUE KEY uq_p13_readiness_version(pilot_site_id,check_code,evaluated_at), KEY ix_p13_readiness_current(workspace_id,pilot_site_id,check_code,expires_at,id), CONSTRAINT fk_p13_readiness_site FOREIGN KEY(workspace_id,pilot_site_id) REFERENCES pilot_sites(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_readiness_evaluator FOREIGN KEY(evaluated_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_readiness CHECK(blocking_flag IN (0,1) AND result_code IN ('PENDING','PASS','FAIL','WAIVED') AND expires_at>evaluated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('004_pilot_runs', 'Create pilot execution evidence without real-user activation.', "CREATE TABLE pilot_runs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, pilot_program_id BIGINT UNSIGNED NOT NULL, run_number SMALLINT UNSIGNED NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, evidence_sha256 BINARY(32) NULL, started_at DATETIME(6) NULL, completed_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_pilot_run_public(public_id), UNIQUE KEY uq_p13_pilot_run(pilot_program_id,run_number), CONSTRAINT fk_p13_pilot_run_program FOREIGN KEY(pilot_program_id) REFERENCES pilot_programs(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_pilot_run CHECK(run_number>=1 AND status_code IN ('PLANNED','ACTIVE','PAUSED','COMPLETED','CANCELLED','FAILED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('005_pilot_events', 'Create append-only pilot events.', "CREATE TABLE pilot_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, pilot_program_id BIGINT UNSIGNED NOT NULL, pilot_site_id BIGINT UNSIGNED NULL, event_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_account_id BIGINT UNSIGNED NOT NULL, previous_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL, resulting_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, safe_metadata_json JSON NOT NULL, evidence_sha256 BINARY(32) NOT NULL, occurred_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_pilot_event_public(public_id), KEY ix_p13_pilot_event_program(pilot_program_id,occurred_at,id), CONSTRAINT fk_p13_pilot_event_program FOREIGN KEY(pilot_program_id) REFERENCES pilot_programs(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_event_site FOREIGN KEY(pilot_site_id) REFERENCES pilot_sites(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_event_actor FOREIGN KEY(actor_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_pilot_event CHECK(JSON_VALID(safe_metadata_json))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('006_pilot_incidents', 'Create private bounded pilot incidents.', "CREATE TABLE pilot_incidents (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, pilot_program_id BIGINT UNSIGNED NOT NULL, pilot_site_id BIGINT UNSIGNED NOT NULL, classification_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, severity_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, statement_ciphertext MEDIUMBLOB NOT NULL, statement_sha256 BINARY(32) NOT NULL, status_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, version INT UNSIGNED NOT NULL DEFAULT 1, reported_by_account_id BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, resolved_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_pilot_incident_public(public_id), UNIQUE KEY uq_p13_pilot_incident_workspace_id(workspace_id,id), KEY ix_p13_pilot_incident_open(workspace_id,pilot_site_id,status_code,severity_code,id), CONSTRAINT fk_p13_pilot_incident_program FOREIGN KEY(pilot_program_id) REFERENCES pilot_programs(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_incident_site FOREIGN KEY(workspace_id,pilot_site_id) REFERENCES pilot_sites(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_incident_reporter FOREIGN KEY(reported_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_pilot_incident CHECK(classification_code IN ('SECURITY','DATA_INTEGRITY','OFFLINE_SYNC','DEVICE_FAILURE','VENUE_OPERATION','ACCESSIBILITY','PERFORMANCE','NOTIFICATION','OTHER_APPROVED') AND severity_code IN ('LOW','MEDIUM','HIGH','CRITICAL') AND status_code IN ('OPEN','TRIAGED','UNDER_REVIEW','MITIGATED','RESOLVED','CLOSED') AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('007_pilot_findings', 'Create immutable approved pilot findings.', "CREATE TABLE pilot_findings (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, pilot_program_id BIGINT UNSIGNED NOT NULL, finding_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, category_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, outcome_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, evidence_sha256 BINARY(32) NOT NULL, safe_recommendation VARCHAR(500) NOT NULL, approved_by_account_id BIGINT UNSIGNED NOT NULL, approved_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_pilot_finding_public(public_id), UNIQUE KEY uq_p13_pilot_finding(pilot_program_id,finding_code), CONSTRAINT fk_p13_pilot_finding_program FOREIGN KEY(pilot_program_id) REFERENCES pilot_programs(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_pilot_finding_approver FOREIGN KEY(approved_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_pilot_finding CHECK(category_code IN ('READINESS','OPERATIONS','SYNC','DEVICE','ACCESSIBILITY','PERFORMANCE','INCIDENT') AND outcome_code IN ('PASS','FAIL','CONDITIONAL','NOT_OBSERVED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('008_rollout_plans', 'Create platform-governed rollout plans.', "CREATE TABLE rollout_plans (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, rollout_code VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, name VARCHAR(191) NOT NULL, scope_type VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, maximum_wave_size INT UNSIGNED NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, version INT UNSIGNED NOT NULL DEFAULT 1, created_by_account_id BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, activated_at DATETIME(6) NULL, paused_at DATETIME(6) NULL, completed_at DATETIME(6) NULL, cancelled_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_rollout_plan_public(public_id), UNIQUE KEY uq_p13_rollout_plan_code(rollout_code), KEY ix_p13_rollout_plan_status(status_code,created_at,id), CONSTRAINT fk_p13_rollout_plan_creator FOREIGN KEY(created_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_rollout_plan CHECK(scope_type IN ('REGIONAL','STATE','NATIONAL','COHORT') AND maximum_wave_size BETWEEN 1 AND 500 AND status_code IN ('DRAFT','READY','ACTIVE','PAUSED','COMPLETED','CANCELLED') AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('009_rollout_waves', 'Create bounded rollout waves.', "CREATE TABLE rollout_waves (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, rollout_plan_id BIGINT UNSIGNED NOT NULL, wave_number SMALLINT UNSIGNED NOT NULL, name VARCHAR(191) NOT NULL, planned_start_at DATETIME(6) NOT NULL, planned_end_at DATETIME(6) NOT NULL, status_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, assignment_count INT UNSIGNED NOT NULL DEFAULT 0, version INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, activated_at DATETIME(6) NULL, paused_at DATETIME(6) NULL, contained_at DATETIME(6) NULL, completed_at DATETIME(6) NULL, cancelled_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_rollout_wave_public(public_id), UNIQUE KEY uq_p13_rollout_wave_number(rollout_plan_id,wave_number), KEY ix_p13_rollout_wave_due(status_code,planned_start_at,id), CONSTRAINT fk_p13_rollout_wave_plan FOREIGN KEY(rollout_plan_id) REFERENCES rollout_plans(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_rollout_wave CHECK(wave_number>=1 AND planned_end_at>planned_start_at AND status_code IN ('PLANNED','READINESS_REVIEW','APPROVED','ACTIVE','PAUSED','CONTAINED','COMPLETED','CANCELLED','FAILED') AND version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('010_rollout_assignments', 'Create explicit rollout-wave assignments.', "CREATE TABLE rollout_wave_assignments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, rollout_wave_id BIGINT UNSIGNED NOT NULL, workspace_id BIGINT UNSIGNED NULL, venue_id BIGINT UNSIGNED NULL, geography_area_id BIGINT UNSIGNED NULL, cohort_code VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, readiness_sha256 BINARY(32) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_rollout_assignment_public(public_id), UNIQUE KEY uq_p13_rollout_assignment_scope(rollout_wave_id,workspace_id,venue_id,geography_area_id,cohort_code), KEY ix_p13_rollout_assignment_wave(rollout_wave_id,status_code,id), CONSTRAINT fk_p13_rollout_assignment_wave FOREIGN KEY(rollout_wave_id) REFERENCES rollout_waves(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_rollout_assignment_workspace FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_rollout_assignment_venue FOREIGN KEY(workspace_id,venue_id) REFERENCES competition_venues(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_rollout_assignment_geography FOREIGN KEY(geography_area_id) REFERENCES geography_administrative_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_rollout_assignment CHECK(status_code IN ('ASSIGNED','READY','ACTIVE','PAUSED','COMPLETED','CANCELLED') AND ((workspace_id IS NOT NULL AND venue_id IS NOT NULL) OR geography_area_id IS NOT NULL OR cohort_code IS NOT NULL))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('011_rollout_decisions', 'Create immutable rollout go/no-go decisions.', "CREATE TABLE rollout_decisions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, rollout_wave_id BIGINT UNSIGNED NOT NULL, decision_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, expected_wave_version INT UNSIGNED NOT NULL, readiness_sha256 BINARY(32) NOT NULL, health_sha256 BINARY(32) NOT NULL, evidence_sha256 BINARY(32) NOT NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, decided_by_account_id BIGINT UNSIGNED NOT NULL, supersedes_decision_id BIGINT UNSIGNED NULL, decided_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_rollout_decision_public(public_id), KEY ix_p13_rollout_decision_wave(rollout_wave_id,decided_at,id), CONSTRAINT fk_p13_rollout_decision_wave FOREIGN KEY(rollout_wave_id) REFERENCES rollout_waves(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_rollout_decision_actor FOREIGN KEY(decided_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_rollout_decision_previous FOREIGN KEY(supersedes_decision_id) REFERENCES rollout_decisions(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_rollout_decision CHECK(decision_code IN ('GO','NO_GO','PAUSE','CONTAIN','COMPLETE') AND expected_wave_version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('012_rollout_events', 'Create append-only rollout events.', "CREATE TABLE rollout_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, rollout_plan_id BIGINT UNSIGNED NOT NULL, rollout_wave_id BIGINT UNSIGNED NULL, event_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_account_id BIGINT UNSIGNED NOT NULL, previous_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL, resulting_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, safe_metadata_json JSON NOT NULL, evidence_sha256 BINARY(32) NOT NULL, occurred_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_rollout_event_public(public_id), KEY ix_p13_rollout_event_plan(rollout_plan_id,occurred_at,id), CONSTRAINT fk_p13_rollout_event_plan FOREIGN KEY(rollout_plan_id) REFERENCES rollout_plans(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_rollout_event_wave FOREIGN KEY(rollout_wave_id) REFERENCES rollout_waves(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_rollout_event_actor FOREIGN KEY(actor_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_rollout_event CHECK(JSON_VALID(safe_metadata_json))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('013_rollout_health', 'Create immutable privacy-safe rollout health snapshots.', "CREATE TABLE rollout_health_snapshots (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, rollout_plan_id BIGINT UNSIGNED NOT NULL, rollout_wave_id BIGINT UNSIGNED NULL, metrics_json JSON NOT NULL, metrics_sha256 BINARY(32) NOT NULL, source_cutoff_at DATETIME(6) NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_rollout_health_public(public_id), KEY ix_p13_rollout_health_wave(rollout_plan_id,rollout_wave_id,source_cutoff_at,id), CONSTRAINT fk_p13_rollout_health_plan FOREIGN KEY(rollout_plan_id) REFERENCES rollout_plans(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_rollout_health_wave FOREIGN KEY(rollout_wave_id) REFERENCES rollout_waves(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_rollout_health CHECK(status_code IN ('CURRENT','STALE','FAILED') AND JSON_VALID(metrics_json))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('014_pilot_event_no_update', 'Protect pilot events from update.', "CREATE TRIGGER trg_p13_pilot_event_no_update BEFORE UPDATE ON pilot_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Pilot events are immutable'"),
            $this->step('015_rollout_decision_no_update', 'Protect rollout decisions from update.', "CREATE TRIGGER trg_p13_rollout_decision_no_update BEFORE UPDATE ON rollout_decisions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Rollout decisions are immutable'"),
            $this->step('016_rollout_health_no_update', 'Protect rollout health snapshots from update.', "CREATE TRIGGER trg_p13_rollout_health_no_update BEFORE UPDATE ON rollout_health_snapshots FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Rollout health snapshots are immutable'"),
        ];
    }

    private function step(string $id, string $description, string $sql): SqlMigrationStep
    {
        return new SqlMigrationStep(new MigrationStepId($id), $description, $sql);
    }
}
