<?php

declare(strict_types=1);

namespace Qmdb\Modules\PilotOfflineRollout\Infrastructure\Migration;

use Qmdb\Shared\Schema\Migration\Migration;
use Qmdb\Shared\Schema\Migration\MigrationId;
use Qmdb\Shared\Schema\Migration\MigrationStepId;
use Qmdb\Shared\Schema\Migration\SqlMigrationStep;

/** Approved P13 extension for device keys, package artifacts, immutable receipts, and conflict decisions. */
final readonly class ExtendSecureOfflineRuntimeMigration implements Migration
{
    public function id(): MigrationId
    {
        return new MigrationId('20260928102000_extend_secure_offline_runtime');
    }

    public function description(): string
    {
        return 'Extend P13 with device-key history, encrypted package artifacts, sync receipts, nonce replay defense, and conflict decisions.';
    }

    public function dependencies(): array
    {
        return [(new CreatePilotRolloutControlPlaneMigration())->id()];
    }

    public function reversible(): bool
    {
        return false;
    }

    public function down(): array
    {
        return [];
    }

    public function up(): array
    {
        return [
            $this->step('001_device_keys', 'Create public-only device-key rotation metadata.', "CREATE TABLE offline_device_keys (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NOT NULL, key_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, public_key VARBINARY(64) NOT NULL, public_key_sha256 BINARY(32) NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, valid_from DATETIME(6) NOT NULL, valid_until DATETIME(6) NOT NULL, rotated_from_key_id BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, revoked_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_device_key_public(public_id), UNIQUE KEY uq_p13_device_key_code(device_id,key_code), KEY ix_p13_device_key_active(workspace_id,device_id,status_code,valid_from,valid_until,id), CONSTRAINT fk_p13_device_key_device FOREIGN KEY(workspace_id,device_id) REFERENCES venue_edge_node_registrations(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_device_key_previous FOREIGN KEY(rotated_from_key_id) REFERENCES offline_device_keys(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_device_key CHECK(OCTET_LENGTH(public_key)=32 AND status_code IN ('PENDING','ACTIVE','REVOKED','EXPIRED') AND valid_until>valid_from)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('002_device_events', 'Create append-only device lifecycle events.', "CREATE TABLE offline_device_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NOT NULL, event_code VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_account_id BIGINT UNSIGNED NOT NULL, previous_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL, resulting_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, evidence_sha256 BINARY(32) NOT NULL, occurred_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_device_event_public(public_id), KEY ix_p13_device_event(workspace_id,device_id,occurred_at,id), CONSTRAINT fk_p13_device_event_device FOREIGN KEY(workspace_id,device_id) REFERENCES venue_edge_node_registrations(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_device_event_actor FOREIGN KEY(actor_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('003_package_entities', 'Create minimized immutable package entity manifests.', "CREATE TABLE offline_package_entities (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, package_id BIGINT UNSIGNED NOT NULL, entity_type VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, entity_public_id BINARY(16) NOT NULL, entity_version INT UNSIGNED NOT NULL, canonical_payload_json JSON NOT NULL, payload_sha256 BINARY(32) NOT NULL, sort_sequence INT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_package_entity_public(public_id), UNIQUE KEY uq_p13_package_entity(package_id,entity_type,entity_public_id), UNIQUE KEY uq_p13_package_entity_order(package_id,sort_sequence), KEY ix_p13_package_entity_list(workspace_id,package_id,sort_sequence,id), CONSTRAINT fk_p13_package_entity_package FOREIGN KEY(workspace_id,package_id) REFERENCES offline_assignment_packages(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_package_entity CHECK(entity_version>=1 AND sort_sequence>=1 AND JSON_VALID(canonical_payload_json))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('004_package_artifacts', 'Create opaque authenticated package artifacts.', "CREATE TABLE offline_package_artifacts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, package_id BIGINT UNSIGNED NOT NULL, storage_reference_hash BINARY(32) NOT NULL, encryption_mode VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, encryption_key_reference_hash BINARY(32) NOT NULL, nonce VARBINARY(32) NOT NULL, associated_data_sha256 BINARY(32) NOT NULL, ciphertext MEDIUMBLOB NOT NULL, artifact_sha256 BINARY(32) NOT NULL, byte_size BIGINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_package_artifact_public(public_id), UNIQUE KEY uq_p13_package_artifact_package(package_id), CONSTRAINT fk_p13_package_artifact_package FOREIGN KEY(workspace_id,package_id) REFERENCES offline_assignment_packages(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_package_artifact CHECK(encryption_mode='XCHACHA20_POLY1305' AND OCTET_LENGTH(nonce)=24 AND byte_size>0 AND byte_size<=268435456)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('005_package_events', 'Create append-only package lifecycle events.', "CREATE TABLE offline_package_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, package_id BIGINT UNSIGNED NOT NULL, event_code VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_kind VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, actor_reference_hash BINARY(32) NOT NULL, previous_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL, resulting_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, evidence_sha256 BINARY(32) NOT NULL, occurred_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_package_event_public(public_id), KEY ix_p13_package_event(workspace_id,package_id,occurred_at,id), CONSTRAINT fk_p13_package_event_package FOREIGN KEY(workspace_id,package_id) REFERENCES offline_assignment_packages(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_package_event CHECK(actor_kind IN ('ACCOUNT','DEVICE','SYSTEM'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('006_sync_changes', 'Create bounded ordered sync-change envelopes.', "CREATE TABLE offline_sync_changes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, sync_session_id BIGINT UNSIGNED NOT NULL, submission_event_id BIGINT UNSIGNED NOT NULL, local_sequence BIGINT UNSIGNED NOT NULL, payload_bytes INT UNSIGNED NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, received_at DATETIME(6) NOT NULL, processed_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_sync_change_public(public_id), UNIQUE KEY uq_p13_sync_change_submission(sync_session_id,submission_event_id), UNIQUE KEY uq_p13_sync_change_sequence(sync_session_id,local_sequence), KEY ix_p13_sync_change_pending(workspace_id,status_code,received_at,id), CONSTRAINT fk_p13_sync_change_session FOREIGN KEY(workspace_id,sync_session_id) REFERENCES synchronization_batches(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_sync_change_submission FOREIGN KEY(workspace_id,submission_event_id) REFERENCES offline_submission_events(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_sync_change CHECK(local_sequence>=1 AND payload_bytes<=32768 AND status_code IN ('RECEIVED','VALIDATED','ACCEPTED','REJECTED','CONFLICT'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('007_sync_receipts', 'Create immutable replay-safe sync receipts.', "CREATE TABLE offline_sync_receipts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, venue_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NOT NULL, sync_session_id BIGINT UNSIGNED NOT NULL, client_change_uuid BINARY(16) NOT NULL, local_sequence BIGINT UNSIGNED NOT NULL, entity_type VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, entity_public_id BINARY(16) NOT NULL, operation_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, result_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, server_entity_version INT UNSIGNED NULL, result_public_id BINARY(16) NOT NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL, request_payload_sha256 BINARY(32) NOT NULL, result_payload_sha256 BINARY(32) NOT NULL, received_at DATETIME(6) NOT NULL, applied_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_sync_receipt_public(public_id), UNIQUE KEY uq_p13_sync_receipt_change(device_id,client_change_uuid), KEY ix_p13_sync_receipt_session(workspace_id,sync_session_id,local_sequence,id), CONSTRAINT fk_p13_sync_receipt_device FOREIGN KEY(workspace_id,device_id) REFERENCES venue_edge_node_registrations(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_sync_receipt_session FOREIGN KEY(workspace_id,sync_session_id) REFERENCES synchronization_batches(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_sync_receipt CHECK(local_sequence>=1 AND result_status IN ('ACCEPTED','REJECTED','CONFLICT','DUPLICATE'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('008_conflict_assignments', 'Create conflict review assignments.', "CREATE TABLE offline_conflict_assignments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, conflict_id BIGINT UNSIGNED NOT NULL, reviewer_account_id BIGINT UNSIGNED NOT NULL, assigned_by_account_id BIGINT UNSIGNED NOT NULL, status_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, assigned_at DATETIME(6) NOT NULL, released_at DATETIME(6) NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_conflict_assignment_public(public_id), KEY ix_p13_conflict_assignment(workspace_id,reviewer_account_id,status_code,assigned_at,id), CONSTRAINT fk_p13_conflict_assignment_conflict FOREIGN KEY(workspace_id,conflict_id) REFERENCES synchronization_conflicts(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_conflict_assignment_reviewer FOREIGN KEY(reviewer_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_conflict_assignment_assigner FOREIGN KEY(assigned_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_conflict_assignment CHECK(status_code IN ('ACTIVE','RELEASED','COMPLETED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('009_conflict_decisions', 'Create immutable conflict decisions.', "CREATE TABLE offline_conflict_decisions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, conflict_id BIGINT UNSIGNED NOT NULL, decision_code VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, expected_conflict_version INT UNSIGNED NOT NULL, safe_reason_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, proposal_schema_version SMALLINT UNSIGNED NULL, resolution_payload_ciphertext MEDIUMBLOB NULL, resolution_payload_sha256 BINARY(32) NOT NULL, evidence_sha256 BINARY(32) NOT NULL, decided_by_account_id BIGINT UNSIGNED NOT NULL, decided_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_conflict_decision_public(public_id), UNIQUE KEY uq_p13_conflict_decision_conflict(conflict_id), CONSTRAINT fk_p13_conflict_decision_conflict FOREIGN KEY(workspace_id,conflict_id) REFERENCES synchronization_conflicts(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_conflict_decision_actor FOREIGN KEY(decided_by_account_id) REFERENCES user_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_conflict_decision CHECK(decision_code IN ('ACCEPT_SERVER','ACCEPT_CLIENT_PROPOSAL','MANUAL','DISMISS') AND expected_conflict_version>=1)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('010_operation_events', 'Create append-only offline authoritative-operation evidence.', "CREATE TABLE offline_operation_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, workspace_id BIGINT UNSIGNED NOT NULL, venue_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NOT NULL, receipt_id BIGINT UNSIGNED NOT NULL, operation_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, entity_public_id BINARY(16) NOT NULL, before_version INT UNSIGNED NULL, after_version INT UNSIGNED NULL, evidence_sha256 BINARY(32) NOT NULL, occurred_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_operation_event_public(public_id), UNIQUE KEY uq_p13_operation_event_receipt(receipt_id), KEY ix_p13_operation_event(workspace_id,venue_id,occurred_at,id), CONSTRAINT fk_p13_operation_event_device FOREIGN KEY(workspace_id,device_id) REFERENCES venue_edge_node_registrations(workspace_id,id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_p13_operation_event_receipt FOREIGN KEY(receipt_id) REFERENCES offline_sync_receipts(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('011_device_nonces', 'Create bounded device request replay protection.', "CREATE TABLE offline_device_nonces (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, device_id BIGINT UNSIGNED NOT NULL, nonce_hash BINARY(32) NOT NULL, request_hash BINARY(32) NOT NULL, request_timestamp DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_device_nonce(device_id,nonce_hash), KEY ix_p13_device_nonce_expiry(expires_at,id), CONSTRAINT fk_p13_device_nonce_device FOREIGN KEY(device_id) REFERENCES venue_edge_node_registrations(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT ck_p13_device_nonce CHECK(expires_at>request_timestamp)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('012_operation_receipts', 'Create P13 browser-operation idempotency receipts.', "CREATE TABLE p13_operation_receipts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id BINARY(16) NOT NULL, scope_kind VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, scope_reference_hash BINARY(32) NOT NULL, operation_code VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, submission_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, request_hash BINARY(32) NOT NULL, outcome_code VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, resource_public_id BINARY(16) NULL, created_at DATETIME(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY uq_p13_operation_receipt_public(public_id), UNIQUE KEY uq_p13_operation_receipt(scope_kind,scope_reference_hash,operation_code,submission_id), CONSTRAINT ck_p13_operation_receipt CHECK(scope_kind IN ('PLATFORM','WORKSPACE','DEVICE') AND outcome_code IN ('CLAIMED','SUCCEEDED','DENIED','FAILED'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"),
            $this->step('013_device_event_no_update', 'Protect device events from update.', "CREATE TRIGGER trg_p13_device_event_no_update BEFORE UPDATE ON offline_device_events FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Offline device events are immutable'"),
            $this->step('014_package_entity_no_update', 'Protect ready package entity manifests.', "CREATE TRIGGER trg_p13_package_entity_no_update BEFORE UPDATE ON offline_package_entities FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Offline package entities are immutable'"),
            $this->step('015_sync_receipt_no_update', 'Protect sync receipts from update.', "CREATE TRIGGER trg_p13_sync_receipt_no_update BEFORE UPDATE ON offline_sync_receipts FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Offline sync receipts are immutable'"),
            $this->step('016_sync_receipt_no_delete', 'Protect sync receipts from deletion.', "CREATE TRIGGER trg_p13_sync_receipt_no_delete BEFORE DELETE ON offline_sync_receipts FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Offline sync receipts are immutable'"),
            $this->step('017_conflict_decision_no_update', 'Protect conflict decisions from update.', "CREATE TRIGGER trg_p13_conflict_decision_no_update BEFORE UPDATE ON offline_conflict_decisions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Offline conflict decisions are immutable'"),
        ];
    }

    private function step(string $id, string $description, string $sql): SqlMigrationStep
    {
        return new SqlMigrationStep(new MigrationStepId($id), $description, $sql);
    }
}
