<?php

declare(strict_types=1);

namespace Qmdb\Modules\SecurityPrivilegedAccess\Domain;

enum PrivilegedAccessReasonCode: string
{
    case TEMPORARY_OPERATIONAL_NEED = 'TEMPORARY_OPERATIONAL_NEED';
    case SECURITY_INVESTIGATION = 'SECURITY_INVESTIGATION';
    case SUPPORT_REQUEST = 'SUPPORT_REQUEST';
    case INCIDENT_RESPONSE = 'INCIDENT_RESPONSE';
    case SERVICE_RECOVERY = 'SERVICE_RECOVERY';
    case ACCESS_REVOKED = 'ACCESS_REVOKED';
    case ACCESS_EXPIRED = 'ACCESS_EXPIRED';
    case ACCESS_ENDED_BY_SUBJECT = 'ACCESS_ENDED_BY_SUBJECT';
    case REQUEST_CANCELLED = 'REQUEST_CANCELLED';
    case REQUEST_REJECTED = 'REQUEST_REJECTED';
    case REVIEW_CONCERN = 'REVIEW_CONCERN';
    case REVIEW_ESCALATION = 'REVIEW_ESCALATION';
}
