<?php

declare(strict_types=1);

namespace Qmdb\Modules\MediaProcessing\Application;

use DateTimeImmutable;
use DateTimeZone;
use PDO;
use Qmdb\Modules\MediaIngestion\Application\MediaBlobStore;
use Qmdb\Shared\Database\Connection\DatabaseConnectionProvider;
use Qmdb\Shared\Identifier\UuidV7;

/** Lease-based FFmpeg worker. It creates immutable private variants and never approves media. */
final readonly class MediaProcessingWorker
{
    public function __construct(private DatabaseConnectionProvider $connections,private MediaBlobStore $storage,private MediaProcessor $processor) {}
    /** @return array{claimed:bool,outcome:string} */ public function processOne():array{$job=$this->claim();if($job===null)return['claimed'=>false,'outcome'=>'NO_WORK'];try{$profile=$job['kind']==='AUDIO'?['profile'=>'AUDIO_NORMALIZED','input_mime'=>'','output_mime'=>'audio/mpeg']:['profile'=>'VIDEO_NORMALIZED','input_mime'=>'','output_mime'=>'video/mp4'];$contents=$this->processor->process($this->storage->get($job['storage_key']),$profile);return $this->finish($job,$contents,$profile['output_mime']);}catch(\Throwable){return $this->retry($job,'PROCESSOR_ERROR');}}
    /** @return array{id:int,workspace_id:int,asset_id:int,asset_version:int,asset_public_id:string,storage_key:string,kind:string,attempt:int,max_attempts:int}|null */ private function claim():?array{$pdo=$this->connections->connection();$pdo->beginTransaction();try{$s=$pdo->prepare("SELECT j.id,j.workspace_id,j.asset_id,j.attempt,j.max_attempts,a.version,a.public_id,a.original_storage_object_key,a.media_kind FROM media_processing_jobs j INNER JOIN media_assets a ON a.id=j.asset_id AND a.workspace_id=j.workspace_id WHERE j.job_type IN ('PROCESS_AUDIO','PROCESS_VIDEO') AND j.status='QUEUED' AND j.available_at<=UTC_TIMESTAMP(6) AND a.status='PROCESSING' ORDER BY j.id LIMIT 1 FOR UPDATE SKIP LOCKED");if(!$s instanceof \PDOStatement)throw new \RuntimeException('Media process claim could not be prepared.');$s->execute();$r=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($r)){$pdo->commit();return null;}$u=$pdo->prepare("UPDATE media_processing_jobs SET status='LEASED',attempt=attempt+1,lease_expires_at=DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 10 MINUTE),updated_at=UTC_TIMESTAMP(6),version=version+1 WHERE id=:id AND status='QUEUED'");if(!$u instanceof \PDOStatement)throw new \RuntimeException('Media process lease could not be prepared.');$u->execute([':id'=>(int)$r['id']]);if($u->rowCount()!==1)throw new \DomainException('Media process lease changed concurrently.');$pdo->commit();return['id'=>(int)$r['id'],'workspace_id'=>(int)$r['workspace_id'],'asset_id'=>(int)$r['asset_id'],'asset_version'=>(int)$r['version'],'asset_public_id'=>UuidV7::fromBinary($r['public_id'])->toString(),'storage_key'=>(string)$r['original_storage_object_key'],'kind'=>(string)$r['media_kind'],'attempt'=>(int)$r['attempt']+1,'max_attempts'=>(int)$r['max_attempts']];}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    /** @param array{id:int,workspace_id:int,asset_id:int,asset_version:int,asset_public_id:string,storage_key:string,kind:string,attempt:int,max_attempts:int} $job @return array{claimed:bool,outcome:string} */ private function finish(array $job,string $contents,string $mime):array{$pdo=$this->connections->connection();$pdo->beginTransaction();try{$now=(new DateTimeImmutable('now',new DateTimeZone('UTC')))->format('Y-m-d H:i:s.u');$a=$pdo->prepare("UPDATE media_assets SET status='PENDING_MODERATION',updated_at=:now,version=version+1 WHERE id=:asset AND workspace_id=:workspace AND status='PROCESSING' AND version=:version");if(!$a instanceof \PDOStatement)throw new \RuntimeException('Media processing transition could not be prepared.');$a->execute([':now'=>$now,':asset'=>$job['asset_id'],':workspace'=>$job['workspace_id'],':version'=>$job['asset_version']]);if($a->rowCount()!==1)throw new \DomainException('Media processing transition changed concurrently.');$key='variants/'.$job['asset_public_id'].'/'.($job['kind']==='AUDIO'?'normalized.mp3':'normalized.mp4');$this->storage->putImmutable($key,$contents);$v=$pdo->prepare("INSERT INTO media_variants (public_id,workspace_id,asset_id,variant_code,storage_provider_code,storage_object_key,mime_type,byte_size,sha256,status,is_public_safe,created_at) VALUES (:public_id,:workspace,:asset,'NORMALIZED_V1','LOCAL_PRIVATE',:key,:mime,:bytes,:sha256,'READY',0,:now)");if(!$v instanceof \PDOStatement)throw new \RuntimeException('Media variant statement could not be prepared.');$v->execute([':public_id'=>UuidV7::generate()->toBinary(),':workspace'=>$job['workspace_id'],':asset'=>$job['asset_id'],':key'=>$key,':mime'=>$mime,':bytes'=>strlen($contents),':sha256'=>hash('sha256',$contents,true),':now'=>$now]);$event=$pdo->prepare("INSERT INTO media_events (workspace_id,asset_id,event_code,actor_account_id,created_at) VALUES (:workspace,:asset,'media.processing.completed',NULL,:now)");if(!$event instanceof \PDOStatement)throw new \RuntimeException('Media processing event could not be prepared.');$event->execute([':workspace'=>$job['workspace_id'],':asset'=>$job['asset_id'],':now'=>$now]);$j=$pdo->prepare("UPDATE media_processing_jobs SET status='SUCCEEDED',lease_expires_at=NULL,completed_at=:now,updated_at=:now,version=version+1 WHERE id=:id AND status='LEASED'");if(!$j instanceof \PDOStatement)throw new \RuntimeException('Media processing completion could not be prepared.');$j->execute([':now'=>$now,':id'=>$job['id']]);if($j->rowCount()!==1)throw new \DomainException('Media processing completion changed concurrently.');$pdo->commit();return['claimed'=>true,'outcome'=>'PROCESSED'];}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    /** @param array{id:int,workspace_id:int,asset_id:int,asset_version:int,asset_public_id:string,storage_key:string,kind:string,attempt:int,max_attempts:int} $job @return array{claimed:bool,outcome:string} */ private function retry(array $job,string $code):array{$pdo=$this->connections->connection();$s=$pdo->prepare("UPDATE media_processing_jobs SET status=:status,lease_expires_at=NULL,available_at=CASE WHEN :status='QUEUED' THEN DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 60 SECOND) ELSE available_at END,completed_at=CASE WHEN :status='DEAD' THEN UTC_TIMESTAMP(6) ELSE NULL END,safe_failure_code=:code,updated_at=UTC_TIMESTAMP(6),version=version+1 WHERE id=:id AND status='LEASED'");if(!$s instanceof \PDOStatement)throw new \RuntimeException('Media processing retry could not be prepared.');$status=$job['attempt']>=$job['max_attempts']?'DEAD':'QUEUED';$s->execute([':status'=>$status,':code'=>$code,':id'=>$job['id']]);if($s->rowCount()!==1)throw new \DomainException('Media processing retry changed concurrently.');return['claimed'=>true,'outcome'=>$status];}
}
