<?php

declare(strict_types=1);

namespace Qmdb\Modules\SecurityAudit\Domain;

enum SecurityEventSubjectKind: string
{
    case ACCOUNT = 'ACCOUNT';
    case SESSION = 'SESSION';
    case DEVICE = 'DEVICE';
    case ROLE_ASSIGNMENT = 'ROLE_ASSIGNMENT';
    case AUTHENTICATOR = 'AUTHENTICATOR';
    case RECOVERY_CODE_SET = 'RECOVERY_CODE_SET';
    case PRIVILEGED_ACCESS = 'PRIVILEGED_ACCESS';
    case WORKSPACE = 'WORKSPACE';
    case SECURITY_AUDIT = 'SECURITY_AUDIT';
    case PERSON = 'PERSON';
    case PERSON_ROLE = 'PERSON_ROLE';
    case GUARDIANSHIP = 'GUARDIANSHIP';
    case ORGANIZATION = 'ORGANIZATION';
    case ORGANIZATION_UNIT = 'ORGANIZATION_UNIT';
    case ORGANIZATION_AFFILIATION = 'ORGANIZATION_AFFILIATION';
    case ORGANIZATION_AFFILIATION_ASSIGNMENT = 'ORGANIZATION_AFFILIATION_ASSIGNMENT';
    case PROFILE_CLAIM = 'PROFILE_CLAIM';
    case PROFILE_VERIFICATION = 'PROFILE_VERIFICATION';
    case PERSON_DUPLICATE_CASE = 'PERSON_DUPLICATE_CASE';
    case PERSON_ALIAS = 'PERSON_ALIAS';
    case QURAN_SOURCE = 'QURAN_SOURCE';
    case QURAN_RELEASE = 'QURAN_RELEASE';
    case QURAN_SEARCH_CORPUS = 'QURAN_SEARCH_CORPUS';
}
