<?php

declare(strict_types=1);

namespace Qmdb\Modules\IdentityAccess\Security\RateLimit;

enum IdentityRateLimitScope: string
{
    case ACCOUNT_REGISTRATION_EMAIL = 'ACCOUNT_REGISTRATION_EMAIL';
    case ACCOUNT_REGISTRATION_PEER = 'ACCOUNT_REGISTRATION_PEER';
    case EMAIL_VERIFICATION_RESEND_EMAIL = 'EMAIL_VERIFICATION_RESEND_EMAIL';
    case EMAIL_VERIFICATION_RESEND_PEER = 'EMAIL_VERIFICATION_RESEND_PEER';
    case EMAIL_VERIFICATION_ATTEMPT = 'EMAIL_VERIFICATION_ATTEMPT';
    case EMAIL_VERIFICATION_PEER = 'EMAIL_VERIFICATION_PEER';
    case PASSWORD_AUTHENTICATION_EMAIL = 'PASSWORD_AUTHENTICATION_EMAIL';
    case PASSWORD_AUTHENTICATION_PEER = 'PASSWORD_AUTHENTICATION_PEER';
    case PASSWORD_RECOVERY_REQUEST_EMAIL = 'PASSWORD_RECOVERY_REQUEST_EMAIL';
    case PASSWORD_RECOVERY_REQUEST_PEER = 'PASSWORD_RECOVERY_REQUEST_PEER';
    case PASSWORD_RECOVERY_ATTEMPT = 'PASSWORD_RECOVERY_ATTEMPT';
    case PASSWORD_RECOVERY_ATTEMPT_PEER = 'PASSWORD_RECOVERY_ATTEMPT_PEER';
    case MFA_AUTHENTICATION_ACCOUNT = 'MFA_AUTHENTICATION_ACCOUNT';
    case MFA_AUTHENTICATION_PEER = 'MFA_AUTHENTICATION_PEER';
    case PASSKEY_AUTHENTICATION_PEER = 'PASSKEY_AUTHENTICATION_PEER';
    case STEP_UP_ACCOUNT = 'STEP_UP_ACCOUNT';
    case STEP_UP_PEER = 'STEP_UP_PEER';
    case PASSKEY_REGISTRATION_ACCOUNT = 'PASSKEY_REGISTRATION_ACCOUNT';
    case PRIVILEGED_ACCESS_REQUEST_ACCOUNT = 'PRIVILEGED_ACCESS_REQUEST_ACCOUNT';
    case PRIVILEGED_ACCESS_REQUEST_PEER = 'PRIVILEGED_ACCESS_REQUEST_PEER';
    case PRIVILEGED_ACCESS_APPROVAL_ACCOUNT = 'PRIVILEGED_ACCESS_APPROVAL_ACCOUNT';
    case PRIVILEGED_ACCESS_ACTIVATION_ACCOUNT = 'PRIVILEGED_ACCESS_ACTIVATION_ACCOUNT';
    case BREAK_GLASS_ACTIVATION_ACCOUNT = 'BREAK_GLASS_ACTIVATION_ACCOUNT';
    case BREAK_GLASS_ACTIVATION_PEER = 'BREAK_GLASS_ACTIVATION_PEER';
    case ACCOUNT_STATE_OPERATION_ACCOUNT = 'ACCOUNT_STATE_OPERATION_ACCOUNT';
    case ACCOUNT_STATE_OPERATION_PEER = 'ACCOUNT_STATE_OPERATION_PEER';
}
