<?php

declare(strict_types=1);

namespace Qmdb\Modules\IdentityAccess\Security\RateLimit;

enum IdentityRateLimitScope: string
{
    case ACCOUNT_REGISTRATION_EMAIL = 'ACCOUNT_REGISTRATION_EMAIL';
    case ACCOUNT_REGISTRATION_PEER = 'ACCOUNT_REGISTRATION_PEER';
    case EMAIL_VERIFICATION_RESEND_EMAIL = 'EMAIL_VERIFICATION_RESEND_EMAIL';
    case EMAIL_VERIFICATION_RESEND_PEER = 'EMAIL_VERIFICATION_RESEND_PEER';
    case EMAIL_VERIFICATION_ATTEMPT = 'EMAIL_VERIFICATION_ATTEMPT';
    case EMAIL_VERIFICATION_PEER = 'EMAIL_VERIFICATION_PEER';
    case PASSWORD_AUTHENTICATION_EMAIL = 'PASSWORD_AUTHENTICATION_EMAIL';
    case PASSWORD_AUTHENTICATION_PEER = 'PASSWORD_AUTHENTICATION_PEER';
    case PASSWORD_RECOVERY_REQUEST_EMAIL = 'PASSWORD_RECOVERY_REQUEST_EMAIL';
    case PASSWORD_RECOVERY_REQUEST_PEER = 'PASSWORD_RECOVERY_REQUEST_PEER';
    case PASSWORD_RECOVERY_ATTEMPT = 'PASSWORD_RECOVERY_ATTEMPT';
    case PASSWORD_RECOVERY_ATTEMPT_PEER = 'PASSWORD_RECOVERY_ATTEMPT_PEER';
}
