<?php

declare(strict_types=1);

namespace Qmdb\Shared\Http\Routing\Security;

use LogicException;

/**
 * Closed production-route policy inventory. New routes must be explicitly
 * classified here before the security verifier can pass.
 */
final class ProductionRouteSecurityPolicyCatalog
{
    /** @var list<string> */
    private const array PUBLIC = [
        'system.home', 'system.about.page', 'system.status.page', 'system.health.live', 'system.health.ready',
        'api.v1.system.about', 'account.registration.form', 'account.registration.submit',
        'account.registration.accepted', 'account.email_verification.resend.form',
        'account.email_verification.resend.submit', 'account.email_verification.completed',
        'account.email_verification.form', 'account.email_verification.submit', 'account.login.form',
        'account.login.submit', 'account.password_recovery.request.form',
        'account.password_recovery.request.submit', 'account.password_recovery.request.accepted',
        'account.password_recovery.reset.form', 'account.password_recovery.reset.submit',
        'account.password_recovery.reset.completed', 'account.mfa.login.form', 'account.mfa.login.totp',
        'account.mfa.login.recovery_code', 'account.mfa.login.passkey.options',
        'account.mfa.login.passkey.verify', 'account.passkey.login.options', 'account.passkey.login.verify',
        'geography.nigeria.index', 'geography.nigeria.area', 'geography.lookup.children',
        'quran.public.home', 'quran.public.surahs', 'quran.public.surah', 'quran.public.ayah',
        'quran.public.partition', 'quran.public.sajdahs', 'quran.public.search',
        'competition.public.results.edition', 'competition.public.results.category', 'competition.public.results.round',
        'competition.public.live', 'competition.public.live.snapshot', 'competition.public.live.stream',
        'certificate.public.verify', 'certificate.public.manifest', 'certificate.public.pdf',
    ];

    /** @var list<string> */
    private const array AUTHENTICATED = [
        'account.logout', 'account.workspaces.index', 'account.workspaces.switch', 'account.workspaces.clear',
        'account.security.events', 'account.privileged_access.index',
        'account.privileged_access.temporary.request.form', 'account.privileged_access.temporary.request.submit',
        'account.privileged_access.support.request.form', 'account.privileged_access.support.request.submit',
        'account.privileged_access.detail', 'account.privileged_access.approve.form',
        'account.privileged_access.approve.submit', 'account.privileged_access.reject.submit',
        'account.privileged_access.cancel.submit', 'account.privileged_access.activate.submit',
        'account.privileged_access.revoke.submit', 'account.privileged_access.active.end.submit',
        'account.privileged_access.break_glass.activate.form',
        'account.privileged_access.break_glass.activate.submit', 'account.privileged_access.review.form',
        'account.privileged_access.review.submit', 'account.security.sessions',
        'account.security.session_revoke.form', 'account.security.session_revoke.submit',
        'account.security.device_revoke.form', 'account.security.device_revoke.submit', 'account.step_up.form',
        'account.step_up.password', 'account.step_up.totp', 'account.step_up.recovery_code',
        'account.step_up.passkey.options', 'account.step_up.passkey.verify', 'account.security.authentication',
        'account.mfa.totp.enroll.form', 'account.mfa.totp.enroll.submit', 'account.mfa.totp.confirm',
        'account.mfa.totp.qr', 'account.mfa.totp.revoke.form', 'account.mfa.totp.revoke.submit',
        'account.passkey.register.form', 'account.passkey.register.options', 'account.passkey.register.verify',
        'account.passkey.revoke.form', 'account.passkey.revoke.submit', 'account.mfa.enable',
        'account.mfa.disable.form', 'account.mfa.disable.submit', 'account.mfa.recovery_codes.status',
        'account.mfa.recovery_codes.regenerate',
        'account.person_profile.view', 'account.person_profile.create.form', 'account.person_profile.create.submit',
        'account.person_profile.edit.form', 'account.person_profile.update.submit', 'account.person_profile.role.activate',
        'account.person_profile.role.deactivate.form', 'account.person_profile.role.deactivate.submit',
        'account.person_profile.memorizer_progress.form', 'account.person_profile.memorizer_progress.submit',
        'account.person_profile.dependents.index', 'account.person_profile.dependent.create.form',
        'account.person_profile.dependent.create.submit', 'account.person_profile.dependent.view',
        'account.person_profile.dependent.edit.form', 'account.person_profile.dependent.update.submit',
        'account.person_profile.dependent.memorizer_progress.form', 'account.person_profile.dependent.memorizer_progress.submit',
        'account.person_profile.guardianship.revoke.form', 'account.person_profile.guardianship.revoke.submit',
        'account.affiliations.index', 'account.affiliations.detail',
        'account.affiliations.accept.form', 'account.affiliations.accept.submit',
        'account.affiliations.decline.form', 'account.affiliations.decline.submit',
        'account.affiliations.leave.form', 'account.affiliations.leave.submit',
        'account.profile_claim_pairing.form', 'account.profile_claim_pairing.create',
        'account.profile_claim_pairing.revoke', 'account.profile_claims.index',
        'account.profile_claim.detail', 'account.profile_claim.accept', 'account.profile_claim.decline',
        'account.dependent_profile_claim.authorization.form', 'account.dependent_profile_claim.authorization.submit',
        'account.dependent_profile_claim.revoke', 'account.person_duplicate.report.form',
        'account.person_duplicate.report.submit', 'account.person_duplicate.index',
        'account.person_duplicate.case.detail', 'account.person_duplicate.consent',
        'account.person_duplicate.decline', 'account.dependent_duplicate.report.form',
        'account.dependent_duplicate.report.submit', 'account.dependent_duplicate.case.detail',
        'account.dependent_duplicate.consent', 'account.dependent_duplicate.decline',
        'account.competition_judging.dashboard', 'account.competition_judging.assignment.detail',
        'account.competition_judging.assignment.accept', 'account.competition_judging.assignment.decline',
        'account.competition_judging.score.form', 'account.competition_judging.score.submit',
        'account.competition_judging.score.lock.form', 'account.competition_judging.score.lock',
        'account.competition_appeal.index', 'account.competition_appeal.detail',
        'account.competition_appeal.withdraw.form', 'account.competition_appeal.withdraw',
    ];

    /** @var list<string> */
    private const array TENANT_REQUIRED = [
        'workspace.current', 'workspace.privileged_access.approve.form',
        'workspace.privileged_access.approve.submit',
    ];

    /** @var array<string, string> */
    private const array BASE_ROLE_PERMISSIONS = [
        'platform.security.accounts.detail' => 'platform.accounts.view',
        'platform.security.accounts.suspend' => 'platform.accounts.suspend',
        'platform.security.accounts.reactivate' => 'platform.accounts.reactivate',
        'platform.security.events' => 'platform.security_events.view',
        'platform.security.events.detail' => 'platform.security_events.view',
        'platform.security.audit' => 'platform.audit.verify',
        'workspace.organizations.index' => 'workspace.organizations.view',
        'workspace.organizations.create.form' => 'workspace.organizations.manage',
        'workspace.organizations.create.submit' => 'workspace.organizations.manage',
        'workspace.organizations.view' => 'workspace.organizations.view',
        'workspace.organizations.edit.form' => 'workspace.organizations.manage',
        'workspace.organizations.update.submit' => 'workspace.organizations.manage',
        'workspace.organizations.retire.form' => 'workspace.organizations.manage',
        'workspace.organizations.retire.submit' => 'workspace.organizations.manage',
        'workspace.organizations.units.create.form' => 'workspace.organization_units.manage',
        'workspace.organizations.units.create.submit' => 'workspace.organization_units.manage',
        'workspace.organizations.units.view' => 'workspace.organization_units.view',
        'workspace.organizations.units.edit.form' => 'workspace.organization_units.manage',
        'workspace.organizations.units.update.submit' => 'workspace.organization_units.manage',
        'workspace.organizations.units.retire.form' => 'workspace.organization_units.manage',
        'workspace.organizations.units.retire.submit' => 'workspace.organization_units.manage',
        'workspace.organizations.affiliations.index' => 'workspace.organization_affiliations.view',
        'workspace.organizations.affiliations.view' => 'workspace.organization_affiliations.view',
        'workspace.organizations.affiliations.request.form' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.request.submit' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.assignments.form' => 'workspace.organization_affiliation_assignments.manage',
        'workspace.organizations.affiliations.assignments.submit' => 'workspace.organization_affiliation_assignments.manage',
        'workspace.organizations.affiliations.withdraw.form' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.withdraw.submit' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.suspend.form' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.suspend.submit' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.resume.form' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.resume.submit' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.end.form' => 'workspace.organization_affiliations.manage',
        'workspace.organizations.affiliations.end.submit' => 'workspace.organization_affiliations.manage',
        'workspace.certificates.issue.form' => 'workspace.certificates.issue',
        'workspace.certificates.issue' => 'workspace.certificates.issue',
        'workspace.certificates.revoke.form' => 'workspace.certificates.revoke',
        'workspace.certificates.revoke' => 'workspace.certificates.revoke',
        'workspace.certificates.archive.form' => 'workspace.certificates.archive',
        'workspace.certificates.archive' => 'workspace.certificates.archive',
        'workspace.media.upload.form' => 'media.assets.upload',
        'workspace.media.upload' => 'media.assets.upload',
        'workspace.media.content' => 'workspace.media.view',
        'workspace.media.index' => 'workspace.media.view',
        'workspace.media.approve.form' => 'workspace.media.approve',
        'workspace.media.approve' => 'workspace.media.approve',
        'workspace.media.reject.form' => 'workspace.media.reject',
        'workspace.media.reject' => 'workspace.media.reject',
        'workspace.media.withdraw-consent.form' => 'media.assets.manage_own',
        'workspace.media.withdraw-consent' => 'media.assets.manage_own',
        'workspace.media.consent-review.form' => 'workspace.media.review',
        'workspace.media.consent-review' => 'workspace.media.review',
        'workspace.media.hold.form' => 'workspace.media.hold',
        'workspace.media.hold' => 'workspace.media.hold',
        'workspace.media.release-hold.form' => 'workspace.media.hold',
        'workspace.media.release-hold' => 'workspace.media.hold',
        'workspace.media.remove.form' => 'workspace.media.remove',
        'workspace.media.remove' => 'workspace.media.remove',
        'workspace.media.archive.form' => 'workspace.media.remove',
        'workspace.media.archive' => 'workspace.media.remove',
        'platform.profile_claim.index' => 'platform.people_profile_claims.authorize',
        'platform.profile_claim.authorization.form' => 'platform.people_profile_claims.authorize',
        'platform.profile_claim.authorization.submit' => 'platform.people_profile_claims.authorize',
        'platform.profile_claim.revoke' => 'platform.people_profile_claims.authorize',
        'platform.profile_verification.index' => 'platform.people_profile_verifications.manage',
        'platform.profile_verification.detail' => 'platform.people_profile_verifications.manage',
        'platform.profile_verification.record' => 'platform.people_profile_verifications.manage',
        'platform.profile_verification.revoke' => 'platform.people_profile_verifications.manage',
        'platform.person_duplicate.index' => 'platform.people_duplicates.view',
        'platform.person_duplicate.detail' => 'platform.people_duplicates.view',
        'platform.person_duplicate.review' => 'platform.people_duplicates.view',
        'platform.person_duplicate.dismiss' => 'platform.people_duplicates.resolve',
        'platform.person_duplicate.resolve.form' => 'platform.people_duplicates.resolve',
        'platform.person_duplicate.resolve.submit' => 'platform.people_duplicates.resolve',
        'platform.quran.releases.index' => 'platform.quran_releases.view',
        'platform.quran.releases.detail' => 'platform.quran_releases.view',
        'platform.quran.releases.stage' => 'platform.quran_releases.manage',
        'platform.quran.releases.validate' => 'platform.quran_releases.manage',
        'platform.quran.releases.approve' => 'platform.quran_releases.approve',
        'platform.quran.releases.activate' => 'platform.quran_releases.activate',
        'platform.quran.releases.reject' => 'platform.quran_releases.manage',
        'platform.quran.search_corpus' => 'platform.quran_search_corpus.view',
        'platform.quran.search_corpus.validate' => 'platform.quran_search_corpus.validate',
        'workspace.competition.round.ready.form' => 'workspace.competitions.manage_rounds',
        'workspace.competition.round.ready' => 'workspace.competitions.manage_rounds',
        'workspace.competition.round.open_scoring.form' => 'workspace.competitions.manage_rounds',
        'workspace.competition.round.open_scoring' => 'workspace.competitions.manage_rounds',
        'workspace.competition.round.close_scoring.form' => 'workspace.competitions.manage_rounds',
        'workspace.competition.round.close_scoring' => 'workspace.competitions.manage_rounds',
        'workspace.competition.round.cancel.form' => 'workspace.competitions.manage_rounds',
        'workspace.competition.round.cancel' => 'workspace.competitions.manage_rounds',
        'workspace.competition.assignment.revoke' => 'workspace.competitions.manage_panels',
        'workspace.competition.result.verify.form' => 'workspace.competitions.verify_results',
        'workspace.competition.result.verify' => 'workspace.competitions.verify_results',
        'workspace.competition.result.calculate.form' => 'workspace.competitions.calculate_results',
        'workspace.competition.result.calculate' => 'workspace.competitions.calculate_results',
        'workspace.competition.result.publish.form' => 'workspace.competitions.publish_results',
        'workspace.competition.result.publish' => 'workspace.competitions.publish_results',
        'workspace.competition.result.void.form' => 'workspace.competitions.publish_results',
        'workspace.competition.result.void' => 'workspace.competitions.publish_results',
        'workspace.competition.appeal.start_review' => 'workspace.competitions.manage_appeals',
        'workspace.competition.appeal.uphold.form' => 'workspace.competitions.manage_appeals',
        'workspace.competition.appeal.uphold' => 'workspace.competitions.manage_appeals',
        'workspace.competition.appeal.dismiss.form' => 'workspace.competitions.manage_appeals',
        'workspace.competition.appeal.dismiss' => 'workspace.competitions.manage_appeals',
        'workspace.competition.live_session.open.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.open' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.pause.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.pause' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.resume.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.resume' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.start_recovery.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.start_recovery' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.complete_recovery.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.complete_recovery' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.close.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.close' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.cancel.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_session.cancel' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.check_in.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.check_in' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.call.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.call' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.ready.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.ready' => 'workspace.competitions.operate_live',
        'workspace.competition.result_publication.prepare.form' => 'workspace.competitions.prepare_publications',
        'workspace.competition.result_publication.prepare' => 'workspace.competitions.prepare_publications',
        'workspace.competition.result_publication.publish_provisional.form' => 'workspace.competitions.publish_provisional_results',
        'workspace.competition.result_publication.publish_provisional' => 'workspace.competitions.publish_provisional_results',
        'workspace.competition.result_publication.hold.form' => 'workspace.competitions.hold_publications',
        'workspace.competition.result_publication.hold' => 'workspace.competitions.hold_publications',
        'workspace.competition.result_publication.release_hold.form' => 'workspace.competitions.hold_publications',
        'workspace.competition.result_publication.release_hold' => 'workspace.competitions.hold_publications',
        'workspace.competition.result_publication.finalize.form' => 'workspace.competitions.finalize_publications',
        'workspace.competition.result_publication.finalize' => 'workspace.competitions.finalize_publications',
        'workspace.competition.result_publication.withdraw.form' => 'workspace.competitions.hold_publications',
        'workspace.competition.result_publication.withdraw' => 'workspace.competitions.hold_publications',
        'workspace.competition.result_publication.supersede.form' => 'workspace.competitions.finalize_publications',
        'workspace.competition.result_publication.supersede' => 'workspace.competitions.finalize_publications',
        'workspace.competition.result_publication.archive.form' => 'workspace.competitions.hold_publications',
        'workspace.competition.result_publication.archive' => 'workspace.competitions.hold_publications',
        'workspace.competition.appeal_adjudication.assign.form' => 'workspace.competitions.adjudicate_appeals',
        'workspace.competition.appeal_adjudication.assign' => 'workspace.competitions.adjudicate_appeals',
        'workspace.competition.appeal_adjudication.accept.form' => 'workspace.competitions.adjudicate_appeals',
        'workspace.competition.appeal_adjudication.accept' => 'workspace.competitions.adjudicate_appeals',
        'workspace.competition.appeal_adjudication.decide.form' => 'workspace.competitions.adjudicate_appeals',
        'workspace.competition.appeal_adjudication.decide' => 'workspace.competitions.adjudicate_appeals',
        'workspace.competition.live_participant.start.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.start' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.interrupt.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.interrupt' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.resume.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.resume' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.complete.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.complete' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.absent.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.absent' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.withdraw.form' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.withdraw' => 'workspace.competitions.operate_live',
        'workspace.competition.live_participant.disqualify.form' => 'workspace.competitions.disqualify_participants',
        'workspace.competition.live_participant.disqualify' => 'workspace.competitions.disqualify_participants',
    ];

    /** @var array<string, string> */
    private const array STEP_UP_ACTIONS = [
        'platform.security.accounts.suspend' => 'ACCOUNT_SUSPEND',
        'platform.security.accounts.reactivate' => 'ACCOUNT_REACTIVATE',
        'account.privileged_access.approve.submit' => 'TEMPORARY_PRIVILEGE_APPROVE',
        'workspace.privileged_access.approve.submit' => 'SUPPORT_ACCESS_WORKSPACE_APPROVE',
        'account.privileged_access.activate.submit' => 'SUPPORT_ACCESS_ACTIVATE',
        'account.privileged_access.revoke.submit' => 'TEMPORARY_PRIVILEGE_REVOKE',
        'account.privileged_access.break_glass.activate.submit' => 'BREAK_GLASS_ACTIVATE',
        'account.privileged_access.review.submit' => 'SUPPORT_ACCESS_REVIEW',
        'account.mfa.totp.enroll.submit' => 'MFA_ENROLL_TOTP',
        'account.mfa.totp.revoke.submit' => 'MFA_REVOKE_TOTP',
        'account.passkey.register.verify' => 'MFA_REGISTER_PASSKEY',
        'account.passkey.revoke.submit' => 'MFA_REVOKE_PASSKEY',
        'account.mfa.enable' => 'MFA_ENABLE',
        'account.mfa.disable.submit' => 'MFA_DISABLE',
        'account.mfa.recovery_codes.regenerate' => 'MFA_REGENERATE_RECOVERY_CODES',
        'account.person_profile.update.submit' => 'PERSON_PROFILE_SENSITIVE_UPDATE',
        'account.person_profile.dependent.update.submit' => 'PERSON_PROFILE_SENSITIVE_UPDATE',
        'account.person_profile.dependent.create.submit' => 'DEPENDENT_PROFILE_CREATE',
        'account.person_profile.guardianship.revoke.submit' => 'GUARDIANSHIP_REVOKE',
        'workspace.organizations.retire.submit' => 'ORGANIZATION_RETIRE',
        'workspace.organizations.units.retire.submit' => 'ORGANIZATION_UNIT_RETIRE',
        'workspace.organizations.affiliations.suspend.submit' => 'ORGANIZATION_AFFILIATION_SUSPEND',
        'workspace.organizations.affiliations.resume.submit' => 'ORGANIZATION_AFFILIATION_RESUME',
        'workspace.organizations.affiliations.end.submit' => 'ORGANIZATION_AFFILIATION_END',
        'account.affiliations.accept.submit' => 'ORGANIZATION_AFFILIATION_ACCEPT',
        'account.affiliations.leave.submit' => 'ORGANIZATION_AFFILIATION_LEAVE',
        'account.dependent_profile_claim.authorization.submit' => 'PROFILE_CLAIM_AUTHORIZE_GUARDIAN',
        'account.profile_claim.accept' => 'PROFILE_CLAIM_ACCEPT',
        'account.dependent_profile_claim.revoke' => 'PROFILE_CLAIM_REVOKE',
        'platform.profile_claim.authorization.submit' => 'PROFILE_CLAIM_AUTHORIZE_PLATFORM',
        'platform.profile_claim.revoke' => 'PROFILE_CLAIM_REVOKE',
        'platform.profile_verification.record' => 'PROFILE_VERIFICATION_RECORD',
        'platform.profile_verification.revoke' => 'PROFILE_VERIFICATION_REVOKE',
        'account.person_duplicate.report.submit' => 'PROFILE_DUPLICATE_REPORT',
        'account.dependent_duplicate.report.submit' => 'PROFILE_DUPLICATE_REPORT',
        'account.person_duplicate.consent' => 'PROFILE_DUPLICATE_CONSENT',
        'account.person_duplicate.decline' => 'PROFILE_DUPLICATE_CONSENT',
        'account.dependent_duplicate.consent' => 'PROFILE_DUPLICATE_CONSENT',
        'account.dependent_duplicate.decline' => 'PROFILE_DUPLICATE_CONSENT',
        'platform.person_duplicate.review' => 'PROFILE_DUPLICATE_REPORT',
        'platform.person_duplicate.dismiss' => 'PROFILE_DUPLICATE_DISMISS',
        'platform.person_duplicate.resolve.submit' => 'PROFILE_DUPLICATE_RESOLVE',
        'platform.quran.releases.approve' => 'QURAN_RELEASE_APPROVE',
        'platform.quran.releases.activate' => 'QURAN_RELEASE_ACTIVATE',
        'platform.quran.releases.reject' => 'QURAN_RELEASE_REJECT',
        'platform.quran.search_corpus.validate' => 'QURAN_SEARCH_CORPUS_VALIDATE',
        'workspace.competition.round.open_scoring' => 'COMPETITION_SCORING_OPEN',
        'workspace.competition.round.close_scoring' => 'COMPETITION_SCORING_CLOSE',
        'workspace.competition.assignment.revoke' => 'COMPETITION_SCORE_CORRECT',
        'workspace.competition.result.verify' => 'COMPETITION_RESULT_VERIFY',
        'workspace.competition.result.publish' => 'COMPETITION_RESULT_PUBLISH',
        'workspace.competition.result.void' => 'COMPETITION_RESULT_VOID',
        'workspace.competition.appeal.uphold' => 'COMPETITION_APPEAL_UPHOLD',
        'workspace.competition.appeal.dismiss' => 'COMPETITION_APPEAL_DISMISS',
        'workspace.competition.live_session.close' => 'COMPETITION_LIVE_SESSION_CLOSE',
        'workspace.competition.live_session.cancel' => 'COMPETITION_LIVE_SESSION_CANCEL',
        'workspace.competition.live_participant.disqualify' => 'COMPETITION_PARTICIPANT_DISQUALIFY',
        'workspace.certificates.issue' => 'CERTIFICATE_ISSUE',
        'workspace.certificates.revoke' => 'CERTIFICATE_REVOKE',
        'workspace.certificates.archive' => 'CERTIFICATE_ARCHIVE',
        'workspace.media.approve' => 'MEDIA_APPROVE',
        'workspace.media.consent-review' => 'MEDIA_CONSENT_GRANT',
        'workspace.media.reject' => 'MEDIA_REJECT',
        'workspace.media.hold' => 'MEDIA_HOLD',
        'workspace.media.release-hold' => 'MEDIA_HOLD',
        'workspace.media.remove' => 'MEDIA_REMOVE',
        'workspace.media.archive' => 'MEDIA_REMOVE',
    ];

    /** @var array<string, string> */
    private const array CSRF_ACTIONS = [
        'workspace.media.upload' => 'media.upload',
        'workspace.media.approve' => 'media.approve',
        'workspace.media.reject' => 'media.reject',
        'workspace.media.withdraw-consent' => 'media.withdraw_consent',
        'workspace.media.consent-review' => 'media.consent_review',
        'workspace.media.hold' => 'media.hold',
        'workspace.media.release-hold' => 'media.release_hold',
        'workspace.media.remove' => 'media.remove',
        'workspace.media.archive' => 'media.archive',
        'account.registration.submit' => 'account.register',
        'account.email_verification.resend.submit' => 'account.email.resend',
        'account.email_verification.submit' => 'account.email.verify',
        'account.login.submit' => 'account.login',
        'account.logout' => 'account.logout',
        'account.workspaces.switch' => 'account.workspace.switch',
        'account.workspaces.clear' => 'account.workspace.clear',
        'platform.security.accounts.suspend' => 'account.state.suspend',
        'platform.security.accounts.reactivate' => 'account.state.reactivate',
        'account.privileged_access.temporary.request.submit' => 'privileged_access.temporary.request',
        'account.privileged_access.support.request.submit' => 'privileged_access.support.request',
        'account.privileged_access.approve.submit' => 'privileged_access.approve',
        'account.privileged_access.reject.submit' => 'privileged_access.reject',
        'account.privileged_access.cancel.submit' => 'privileged_access.cancel',
        'account.privileged_access.activate.submit' => 'privileged_access.activate',
        'account.privileged_access.revoke.submit' => 'privileged_access.revoke',
        'workspace.privileged_access.approve.submit' => 'privileged_access.approve',
        'account.privileged_access.active.end.submit' => 'privileged_access.end',
        'account.privileged_access.break_glass.activate.submit' => 'privileged_access.break_glass.activate',
        'account.privileged_access.review.submit' => 'privileged_access.review',
        'account.security.session_revoke.submit' => 'account.session.revoke',
        'account.security.device_revoke.submit' => 'account.device.revoke',
        'account.password_recovery.request.submit' => 'account.password_recovery.request',
        'account.password_recovery.reset.submit' => 'account.password_recovery.reset',
        'account.mfa.login.totp' => 'account.mfa.login.totp',
        'account.mfa.login.recovery_code' => 'account.mfa.login.recovery_code',
        'account.mfa.login.passkey.options' => 'account.mfa.login.passkey',
        'account.mfa.login.passkey.verify' => 'account.mfa.login.passkey',
        'account.passkey.login.options' => 'account.passkey.login',
        'account.passkey.login.verify' => 'account.passkey.login',
        'account.step_up.password' => 'account.step_up.password',
        'account.step_up.totp' => 'account.step_up.totp',
        'account.step_up.recovery_code' => 'account.step_up.recovery_code',
        'account.step_up.passkey.options' => 'account.step_up.passkey',
        'account.step_up.passkey.verify' => 'account.step_up.passkey',
        'account.mfa.totp.enroll.submit' => 'account.mfa.totp.enroll',
        'account.mfa.totp.confirm' => 'account.mfa.totp.confirm',
        'account.mfa.totp.revoke.submit' => 'account.mfa.totp.revoke',
        'account.passkey.register.options' => 'account.passkey.register',
        'account.passkey.register.verify' => 'account.passkey.register',
        'account.passkey.revoke.submit' => 'account.passkey.revoke',
        'account.mfa.enable' => 'account.mfa.enable',
        'account.mfa.disable.submit' => 'account.mfa.disable',
        'account.mfa.recovery_codes.regenerate' => 'account.mfa.recovery_codes.regenerate',
        'account.person_profile.create.submit' => 'people.profile.create',
        'account.person_profile.update.submit' => 'people.profile.update',
        'account.person_profile.role.activate' => 'people.role.activate',
        'account.person_profile.role.deactivate.submit' => 'people.role.deactivate',
        'account.person_profile.memorizer_progress.submit' => 'people.memorizer_progress.update',
        'account.person_profile.dependent.create.submit' => 'people.dependent.create',
        'account.person_profile.dependent.update.submit' => 'people.dependent.update',
        'account.person_profile.dependent.memorizer_progress.submit' => 'people.memorizer_progress.update',
        'account.person_profile.guardianship.revoke.submit' => 'people.guardianship.revoke',
        'workspace.organizations.create.submit' => 'organizations.organization.create',
        'workspace.organizations.update.submit' => 'organizations.organization.update',
        'workspace.organizations.retire.submit' => 'organizations.organization.retire',
        'workspace.organizations.units.create.submit' => 'organizations.unit.create',
        'workspace.organizations.units.update.submit' => 'organizations.unit.update',
        'workspace.organizations.units.retire.submit' => 'organizations.unit.retire',
        'workspace.organizations.affiliations.request.submit' => 'organization.affiliation.request',
        'workspace.organizations.affiliations.assignments.submit' => 'organization.affiliation.assignments.update',
        'workspace.organizations.affiliations.withdraw.submit' => 'organization.affiliation.withdraw',
        'workspace.organizations.affiliations.suspend.submit' => 'organization.affiliation.suspend',
        'workspace.organizations.affiliations.resume.submit' => 'organization.affiliation.resume',
        'workspace.organizations.affiliations.end.submit' => 'organization.affiliation.end',
        'account.affiliations.accept.submit' => 'organization.affiliation.accept',
        'account.affiliations.decline.submit' => 'organization.affiliation.decline',
        'account.affiliations.leave.submit' => 'organization.affiliation.leave',
        'account.profile_claim_pairing.create' => 'people.claim_pairing.create',
        'account.profile_claim_pairing.revoke' => 'people.claim_pairing.revoke',
        'account.dependent_profile_claim.authorization.submit' => 'people.profile_claim.authorize',
        'account.profile_claim.accept' => 'people.profile_claim.accept',
        'account.profile_claim.decline' => 'people.profile_claim.decline',
        'account.dependent_profile_claim.revoke' => 'people.profile_claim.revoke',
        'platform.profile_claim.authorization.submit' => 'people.profile_claim.authorize',
        'platform.profile_claim.revoke' => 'people.profile_claim.revoke',
        'platform.profile_verification.record' => 'people.profile_verification.record',
        'platform.profile_verification.revoke' => 'people.profile_verification.revoke',
        'account.person_duplicate.report.submit' => 'people.duplicate.report',
        'account.dependent_duplicate.report.submit' => 'people.duplicate.report',
        'account.person_duplicate.consent' => 'people.duplicate.consent',
        'account.person_duplicate.decline' => 'people.duplicate.consent',
        'account.dependent_duplicate.consent' => 'people.duplicate.consent',
        'account.dependent_duplicate.decline' => 'people.duplicate.consent',
        'platform.person_duplicate.review' => 'people.duplicate.report',
        'platform.person_duplicate.dismiss' => 'people.duplicate.dismiss',
        'platform.person_duplicate.resolve.submit' => 'people.duplicate.resolve',
        'platform.quran.releases.stage' => 'quran.release.stage',
        'platform.quran.releases.validate' => 'quran.release.validate',
        'platform.quran.releases.approve' => 'quran.release.approve',
        'platform.quran.releases.activate' => 'quran.release.activate',
        'platform.quran.releases.reject' => 'quran.release.reject',
        'platform.quran.search_corpus.validate' => 'quran.search_corpus.validate',
        'account.competition_judging.assignment.accept' => 'competition.assignment.accept',
        'account.competition_judging.assignment.decline' => 'competition.assignment.decline',
        'account.competition_judging.score.submit' => 'competition.score.submit',
        'account.competition_judging.score.lock' => 'competition.score.lock',
        'account.competition_appeal.withdraw' => 'competition.appeal.withdraw',
        'workspace.competition.round.ready' => 'competition.round.ready',
        'workspace.competition.round.open_scoring' => 'competition.round.open_scoring',
        'workspace.competition.round.close_scoring' => 'competition.round.close_scoring',
        'workspace.competition.round.cancel' => 'competition.round.cancel',
        'workspace.competition.assignment.revoke' => 'competition.assignment.revoke',
        'workspace.competition.result.verify' => 'competition.result.verify',
        'workspace.competition.result.calculate' => 'competition.result.calculate',
        'workspace.competition.result.publish' => 'competition.result.publish',
        'workspace.competition.result.void' => 'competition.result.void',
        'workspace.competition.appeal.start_review' => 'competition.appeal.start_review',
        'workspace.competition.appeal.uphold' => 'competition.appeal.uphold',
        'workspace.competition.appeal.dismiss' => 'competition.appeal.dismiss',
        'workspace.competition.live_session.open' => 'competition.live_session.open',
        'workspace.competition.live_session.pause' => 'competition.live_session.pause',
        'workspace.competition.live_session.resume' => 'competition.live_session.resume',
        'workspace.competition.live_session.start_recovery' => 'competition.live_session.start_recovery',
        'workspace.competition.live_session.complete_recovery' => 'competition.live_session.complete_recovery',
        'workspace.competition.live_session.close' => 'competition.live_session.close',
        'workspace.competition.live_session.cancel' => 'competition.live_session.cancel',
        'workspace.competition.live_participant.check_in' => 'competition.live_participant.check_in',
        'workspace.competition.live_participant.call' => 'competition.live_participant.call',
        'workspace.competition.live_participant.ready' => 'competition.live_participant.ready',
        'workspace.competition.live_participant.start' => 'competition.live_participant.start',
        'workspace.competition.live_participant.interrupt' => 'competition.live_participant.interrupt',
        'workspace.competition.live_participant.resume' => 'competition.live_participant.resume',
        'workspace.competition.live_participant.complete' => 'competition.live_participant.complete',
        'workspace.competition.live_participant.absent' => 'competition.live_participant.absent',
        'workspace.competition.live_participant.withdraw' => 'competition.live_participant.withdraw',
        'workspace.competition.live_participant.disqualify' => 'competition.live_participant.disqualify',
        'workspace.competition.result_publication.prepare' => 'competition.result_publication.prepare',
        'workspace.competition.result_publication.publish_provisional' => 'competition.result_publication.publish_provisional',
        'workspace.competition.result_publication.hold' => 'competition.result_publication.hold',
        'workspace.competition.result_publication.release_hold' => 'competition.result_publication.release_hold',
        'workspace.competition.result_publication.finalize' => 'competition.result_publication.finalize',
        'workspace.competition.result_publication.withdraw' => 'competition.result_publication.withdraw',
        'workspace.competition.result_publication.supersede' => 'competition.result_publication.supersede',
        'workspace.competition.result_publication.archive' => 'competition.result_publication.archive',
        'workspace.competition.appeal_adjudication.assign' => 'competition.appeal_adjudication.assign',
        'workspace.competition.appeal_adjudication.accept' => 'competition.appeal_adjudication.accept',
        'workspace.competition.appeal_adjudication.decide' => 'competition.appeal_adjudication.decide',
        'workspace.certificates.issue' => 'certificate.issue',
        'workspace.certificates.revoke' => 'certificate.revoke',
        'workspace.certificates.archive' => 'certificate.archive',
    ];

    /** @var list<string> */
    private const array IDEMPOTENT = [
        'workspace.media.upload',
        'workspace.media.approve',
        'workspace.media.reject',
        'workspace.media.withdraw-consent',
        'workspace.media.consent-review',
        'workspace.media.hold',
        'workspace.media.release-hold',
        'workspace.media.remove',
        'workspace.media.archive',
        'account.registration.submit', 'account.password_recovery.reset.submit',
        'platform.security.accounts.suspend', 'platform.security.accounts.reactivate',
        'account.privileged_access.temporary.request.submit', 'account.privileged_access.support.request.submit',
        'account.privileged_access.approve.submit', 'workspace.privileged_access.approve.submit',
        'account.privileged_access.activate.submit', 'account.privileged_access.break_glass.activate.submit',
        'account.person_profile.create.submit', 'account.person_profile.update.submit',
        'account.person_profile.role.activate', 'account.person_profile.role.deactivate.submit',
        'account.person_profile.memorizer_progress.submit', 'account.person_profile.dependent.create.submit',
        'account.person_profile.dependent.update.submit', 'account.person_profile.dependent.memorizer_progress.submit',
        'account.person_profile.guardianship.revoke.submit',
        'workspace.organizations.create.submit', 'workspace.organizations.update.submit',
        'workspace.organizations.retire.submit', 'workspace.organizations.units.create.submit',
        'workspace.organizations.units.update.submit', 'workspace.organizations.units.retire.submit',
        'workspace.organizations.affiliations.request.submit',
        'workspace.organizations.affiliations.assignments.submit',
        'workspace.organizations.affiliations.withdraw.submit',
        'workspace.organizations.affiliations.suspend.submit',
        'workspace.organizations.affiliations.resume.submit',
        'workspace.organizations.affiliations.end.submit',
        'workspace.certificates.issue', 'workspace.certificates.revoke', 'workspace.certificates.archive',
        'account.affiliations.accept.submit', 'account.affiliations.decline.submit',
        'account.affiliations.leave.submit',
        'account.profile_claim_pairing.create', 'account.profile_claim_pairing.revoke',
        'account.dependent_profile_claim.authorization.submit', 'account.profile_claim.accept',
        'account.profile_claim.decline', 'account.dependent_profile_claim.revoke',
        'platform.profile_claim.authorization.submit', 'platform.profile_claim.revoke',
        'platform.profile_verification.record', 'platform.profile_verification.revoke',
        'account.person_duplicate.report.submit', 'account.person_duplicate.consent',
        'account.person_duplicate.decline', 'account.dependent_duplicate.report.submit',
        'account.dependent_duplicate.consent', 'account.dependent_duplicate.decline',
        'platform.person_duplicate.review', 'platform.person_duplicate.dismiss',
        'platform.person_duplicate.resolve.submit',
        'platform.quran.releases.stage', 'platform.quran.releases.validate', 'platform.quran.releases.approve',
        'platform.quran.releases.activate', 'platform.quran.releases.reject',
        'platform.quran.search_corpus.validate',
        'account.competition_judging.assignment.accept', 'account.competition_judging.assignment.decline',
        'account.competition_judging.score.submit', 'account.competition_judging.score.lock',
        'account.competition_appeal.withdraw', 'workspace.competition.round.ready',
        'workspace.competition.round.open_scoring', 'workspace.competition.round.close_scoring',
        'workspace.competition.round.cancel', 'workspace.competition.assignment.revoke',
        'workspace.competition.result.verify', 'workspace.competition.result.publish',
        'workspace.competition.result.calculate',
        'workspace.competition.result.void', 'workspace.competition.appeal.start_review',
        'workspace.competition.appeal.uphold', 'workspace.competition.appeal.dismiss',
        'workspace.competition.live_session.open', 'workspace.competition.live_session.pause',
        'workspace.competition.live_session.resume', 'workspace.competition.live_session.start_recovery',
        'workspace.competition.live_session.complete_recovery', 'workspace.competition.live_session.close',
        'workspace.competition.live_session.cancel',
        'workspace.competition.live_participant.check_in', 'workspace.competition.live_participant.call',
        'workspace.competition.live_participant.ready', 'workspace.competition.live_participant.start',
        'workspace.competition.live_participant.interrupt', 'workspace.competition.live_participant.resume',
        'workspace.competition.live_participant.complete', 'workspace.competition.live_participant.absent',
        'workspace.competition.live_participant.withdraw', 'workspace.competition.live_participant.disqualify',
        'workspace.competition.result_publication.prepare', 'workspace.competition.result_publication.publish_provisional',
        'workspace.competition.result_publication.hold', 'workspace.competition.result_publication.release_hold',
        'workspace.competition.result_publication.finalize', 'workspace.competition.result_publication.withdraw',
        'workspace.competition.result_publication.supersede', 'workspace.competition.result_publication.archive',
        'workspace.competition.appeal_adjudication.assign', 'workspace.competition.appeal_adjudication.accept',
        'workspace.competition.appeal_adjudication.decide',
    ];

    /** @var list<string> */
    private const array JSON_MUTATIONS = [
        'account.mfa.login.passkey.options', 'account.mfa.login.passkey.verify', 'account.passkey.login.options',
        'account.passkey.login.verify', 'account.step_up.passkey.options', 'account.step_up.passkey.verify',
        'account.passkey.register.options', 'account.passkey.register.verify',
    ];

    /** @return array<string, RouteSecurityPolicy> */
    public function policies(): array
    {
        $policies = [];
        foreach (self::PUBLIC as $route) {
            $policies[$route] = $this->policy(RouteSecurityClassification::PUBLIC, $route);
        }
        foreach (self::AUTHENTICATED as $route) {
            $policies[$route] = $this->policy(RouteSecurityClassification::AUTHENTICATED, $route);
        }
        foreach (self::TENANT_REQUIRED as $route) {
            $policies[$route] = $this->policy(RouteSecurityClassification::TENANT_REQUIRED, $route);
        }
        foreach (self::BASE_ROLE_PERMISSIONS as $route => $_) {
            $policies[$route] = $this->policy(RouteSecurityClassification::BASE_ROLE_REQUIRED, $route);
        }

        if (count($policies) !== count(array_unique(array_merge(self::PUBLIC, self::AUTHENTICATED, self::TENANT_REQUIRED, array_keys(self::BASE_ROLE_PERMISSIONS))))) {
            throw new LogicException('The closed production route-security catalog contains duplicate route names.');
        }

        return $policies;
    }

    private function policy(RouteSecurityClassification $classification, string $route): RouteSecurityPolicy
    {
        $permission = self::BASE_ROLE_PERMISSIONS[$route] ?? null;
        $assurance = $this->assuranceForPermission($permission);

        return new RouteSecurityPolicy(
            $classification,
            $classification === RouteSecurityClassification::TENANT_REQUIRED || str_starts_with($route, 'workspace.organizations.') || str_starts_with($route, 'workspace.competition.') || str_starts_with($route, 'workspace.certificates.') || str_starts_with($route, 'workspace.media.'),
            $permission,
            $assurance,
            self::STEP_UP_ACTIONS[$route] ?? null,
            self::CSRF_ACTIONS[$route] ?? null,
            in_array($route, self::IDEMPOTENT, true),
            $classification !== RouteSecurityClassification::PUBLIC
                || str_contains($route, 'verification')
                || str_contains($route, '.password_recovery.')
                || str_contains($route, '.mfa.')
                || str_contains($route, '.passkey.'),
            in_array($route, self::JSON_MUTATIONS, true) ? 'application/json' : null,
        );
    }

    private function assuranceForPermission(?string $permission): ?string
    {
        return match ($permission) {
            'workspace.media.approve', 'workspace.media.reject', 'workspace.media.hold', 'workspace.media.remove' => 'PHISHING_RESISTANT',
            'workspace.media.view', 'workspace.media.review', 'media.assets.upload', 'media.assets.manage_own' => 'PHISHING_RESISTANT',
            'platform.accounts.view', 'platform.security_events.view',
            'workspace.organizations.manage', 'workspace.organization_units.manage',
            'workspace.organization_affiliations.manage', 'workspace.organization_affiliation_assignments.manage' => 'MULTI_FACTOR',
            'workspace.organizations.view', 'workspace.organization_units.view', 'workspace.organization_affiliations.view' => 'PRIMARY',
            'platform.accounts.suspend', 'platform.accounts.reactivate', 'platform.audit.verify',
            'platform.people_profile_claims.authorize', 'platform.people_profile_verifications.manage',
            'platform.people_duplicates.resolve' => 'PHISHING_RESISTANT',
            'platform.people_duplicates.view' => 'MULTI_FACTOR',
            'platform.quran_releases.view', 'platform.quran_releases.manage' => 'MULTI_FACTOR',
            'platform.quran_releases.approve', 'platform.quran_releases.activate' => 'PHISHING_RESISTANT',
            'platform.quran_search_corpus.view', 'platform.quran_public_reference.verify' => 'MULTI_FACTOR',
            'platform.quran_search_corpus.validate' => 'PHISHING_RESISTANT',
            'workspace.competitions.manage_judges', 'workspace.competitions.manage_rounds',
            'workspace.competitions.manage_rubrics', 'workspace.competitions.judge_scores',
            'workspace.competitions.manage_panels', 'workspace.competitions.view_sensitive_scores',
            'workspace.competitions.audit_results', 'workspace.competitions.calculate_results' => 'MULTI_FACTOR',
            'workspace.competitions.monitor_scoring' => 'PRIMARY',
            'workspace.competitions.operate_live' => 'MULTI_FACTOR',
            'workspace.competitions.prepare_publications' => 'MULTI_FACTOR',
            'workspace.competitions.verify_results', 'workspace.competitions.publish_results',
            'workspace.competitions.manage_appeals', 'workspace.competitions.correct_scores',
            'workspace.competitions.disqualify_participants', 'workspace.competitions.publish_provisional_results',
            'workspace.competitions.hold_publications', 'workspace.competitions.finalize_publications',
            'workspace.competitions.adjudicate_appeals' => 'PHISHING_RESISTANT',
            'workspace.certificates.view', 'workspace.certificates.manage_templates', 'workspace.certificates.prepare',
            'workspace.certificates.issue', 'workspace.certificates.revoke', 'workspace.certificates.archive' => 'PHISHING_RESISTANT',
            default => null,
        };
    }
}
