<?php

declare(strict_types=1);

namespace Qmdb\Modules\IdentityMultiFactor\Domain;

enum StepUpAction: string
{
    case MFA_ENROLL_TOTP = 'MFA_ENROLL_TOTP';
    case MFA_REGISTER_PASSKEY = 'MFA_REGISTER_PASSKEY';
    case MFA_ENABLE = 'MFA_ENABLE';
    case MFA_DISABLE = 'MFA_DISABLE';
    case MFA_REGENERATE_RECOVERY_CODES = 'MFA_REGENERATE_RECOVERY_CODES';
    case MFA_REVOKE_TOTP = 'MFA_REVOKE_TOTP';
    case MFA_REVOKE_PASSKEY = 'MFA_REVOKE_PASSKEY';
    case AUTHORIZATION_PLATFORM_ROLE_ASSIGN = 'AUTHORIZATION_PLATFORM_ROLE_ASSIGN';
    case AUTHORIZATION_PLATFORM_ROLE_REVOKE = 'AUTHORIZATION_PLATFORM_ROLE_REVOKE';
    case AUTHORIZATION_WORKSPACE_ROLE_ASSIGN = 'AUTHORIZATION_WORKSPACE_ROLE_ASSIGN';
    case AUTHORIZATION_WORKSPACE_ROLE_REVOKE = 'AUTHORIZATION_WORKSPACE_ROLE_REVOKE';
    case TEMPORARY_PRIVILEGE_APPROVE = 'TEMPORARY_PRIVILEGE_APPROVE';
    case TEMPORARY_PRIVILEGE_ACTIVATE = 'TEMPORARY_PRIVILEGE_ACTIVATE';
    case TEMPORARY_PRIVILEGE_REVOKE = 'TEMPORARY_PRIVILEGE_REVOKE';
    case SUPPORT_ACCESS_PLATFORM_APPROVE = 'SUPPORT_ACCESS_PLATFORM_APPROVE';
    case SUPPORT_ACCESS_WORKSPACE_APPROVE = 'SUPPORT_ACCESS_WORKSPACE_APPROVE';
    case SUPPORT_ACCESS_ACTIVATE = 'SUPPORT_ACCESS_ACTIVATE';
    case SUPPORT_ACCESS_REVOKE = 'SUPPORT_ACCESS_REVOKE';
    case SUPPORT_ACCESS_REVIEW = 'SUPPORT_ACCESS_REVIEW';
    case BREAK_GLASS_ACTIVATE = 'BREAK_GLASS_ACTIVATE';
    case BREAK_GLASS_REVIEW = 'BREAK_GLASS_REVIEW';
    case ACCOUNT_SUSPEND = 'ACCOUNT_SUSPEND';
    case ACCOUNT_REACTIVATE = 'ACCOUNT_REACTIVATE';
    case PERSON_PROFILE_SENSITIVE_UPDATE = 'PERSON_PROFILE_SENSITIVE_UPDATE';
    case DEPENDENT_PROFILE_CREATE = 'DEPENDENT_PROFILE_CREATE';
    case GUARDIANSHIP_REVOKE = 'GUARDIANSHIP_REVOKE';
    case ORGANIZATION_RETIRE = 'ORGANIZATION_RETIRE';
    case ORGANIZATION_UNIT_RETIRE = 'ORGANIZATION_UNIT_RETIRE';
    case ORGANIZATION_AFFILIATION_ACCEPT = 'ORGANIZATION_AFFILIATION_ACCEPT';
    case ORGANIZATION_AFFILIATION_ACCEPT_LEADERSHIP = 'ORGANIZATION_AFFILIATION_ACCEPT_LEADERSHIP';
    case ORGANIZATION_AFFILIATION_SUSPEND = 'ORGANIZATION_AFFILIATION_SUSPEND';
    case ORGANIZATION_AFFILIATION_RESUME = 'ORGANIZATION_AFFILIATION_RESUME';
    case ORGANIZATION_AFFILIATION_END = 'ORGANIZATION_AFFILIATION_END';
    case ORGANIZATION_AFFILIATION_LEAVE = 'ORGANIZATION_AFFILIATION_LEAVE';
    case ORGANIZATION_LEADERSHIP_ASSIGN = 'ORGANIZATION_LEADERSHIP_ASSIGN';
    case ORGANIZATION_LEADERSHIP_REMOVE = 'ORGANIZATION_LEADERSHIP_REMOVE';
    case PROFILE_CLAIM_AUTHORIZE_GUARDIAN = 'PROFILE_CLAIM_AUTHORIZE_GUARDIAN';
    case PROFILE_CLAIM_AUTHORIZE_PLATFORM = 'PROFILE_CLAIM_AUTHORIZE_PLATFORM';
    case PROFILE_CLAIM_ACCEPT = 'PROFILE_CLAIM_ACCEPT';
    case PROFILE_CLAIM_REVOKE = 'PROFILE_CLAIM_REVOKE';
    case PROFILE_VERIFICATION_RECORD = 'PROFILE_VERIFICATION_RECORD';
    case PROFILE_VERIFICATION_REVOKE = 'PROFILE_VERIFICATION_REVOKE';
    case PROFILE_DUPLICATE_REPORT = 'PROFILE_DUPLICATE_REPORT';
    case PROFILE_DUPLICATE_CONSENT = 'PROFILE_DUPLICATE_CONSENT';
    case PROFILE_DUPLICATE_DISMISS = 'PROFILE_DUPLICATE_DISMISS';
    case PROFILE_DUPLICATE_RESOLVE = 'PROFILE_DUPLICATE_RESOLVE';
    case QURAN_RELEASE_APPROVE = 'QURAN_RELEASE_APPROVE';
    case QURAN_RELEASE_ACTIVATE = 'QURAN_RELEASE_ACTIVATE';
    case QURAN_RELEASE_REJECT = 'QURAN_RELEASE_REJECT';
    case QURAN_SEARCH_CORPUS_VALIDATE = 'QURAN_SEARCH_CORPUS_VALIDATE';
    case COMPETITION_PROGRAM_ACTIVATE = 'COMPETITION_PROGRAM_ACTIVATE';
    case COMPETITION_EDITION_PUBLISH = 'COMPETITION_EDITION_PUBLISH';
    case COMPETITION_REGISTRATION_OPEN = 'COMPETITION_REGISTRATION_OPEN';
    case COMPETITION_REGISTRATION_CLOSE = 'COMPETITION_REGISTRATION_CLOSE';
    case COMPETITION_REGISTRATION_REOPEN = 'COMPETITION_REGISTRATION_REOPEN';
    case COMPETITION_EDITION_CANCEL = 'COMPETITION_EDITION_CANCEL';
    case COMPETITION_ROSTER_FINALIZE = 'COMPETITION_ROSTER_FINALIZE';
    case COMPETITION_RUBRIC_ACTIVATE = 'COMPETITION_RUBRIC_ACTIVATE';
    case COMPETITION_SCORING_OPEN = 'COMPETITION_SCORING_OPEN';
    case COMPETITION_SCORING_CLOSE = 'COMPETITION_SCORING_CLOSE';
    case COMPETITION_SCORE_CORRECT = 'COMPETITION_SCORE_CORRECT';
    case COMPETITION_RESULT_VERIFY = 'COMPETITION_RESULT_VERIFY';
    case COMPETITION_RESULT_PUBLISH = 'COMPETITION_RESULT_PUBLISH';
    case COMPETITION_RESULT_VOID = 'COMPETITION_RESULT_VOID';
    case COMPETITION_PARTICIPANT_DISQUALIFY = 'COMPETITION_PARTICIPANT_DISQUALIFY';
    case COMPETITION_APPEAL_UPHOLD = 'COMPETITION_APPEAL_UPHOLD';
    case COMPETITION_APPEAL_DISMISS = 'COMPETITION_APPEAL_DISMISS';
    case COMPETITION_LIVE_SESSION_CLOSE = 'COMPETITION_LIVE_SESSION_CLOSE';
    case COMPETITION_LIVE_SESSION_CANCEL = 'COMPETITION_LIVE_SESSION_CANCEL';

    public function requirement(): AuthenticationAssuranceLevel
    {
        return match ($this) {
            self::MFA_ENROLL_TOTP, self::MFA_REGISTER_PASSKEY, self::ORGANIZATION_AFFILIATION_ACCEPT, self::ORGANIZATION_AFFILIATION_LEAVE, self::PROFILE_DUPLICATE_REPORT => AuthenticationAssuranceLevel::PRIMARY,
            self::AUTHORIZATION_PLATFORM_ROLE_ASSIGN,
            self::AUTHORIZATION_PLATFORM_ROLE_REVOKE,
            self::SUPPORT_ACCESS_PLATFORM_APPROVE,
            self::SUPPORT_ACCESS_WORKSPACE_APPROVE,
            self::SUPPORT_ACCESS_ACTIVATE,
            self::SUPPORT_ACCESS_REVOKE,
            self::SUPPORT_ACCESS_REVIEW,
            self::BREAK_GLASS_ACTIVATE,
            self::BREAK_GLASS_REVIEW, self::ORGANIZATION_LEADERSHIP_ASSIGN, self::ORGANIZATION_LEADERSHIP_REMOVE,
            self::PROFILE_CLAIM_AUTHORIZE_PLATFORM, self::PROFILE_VERIFICATION_RECORD,
            self::PROFILE_VERIFICATION_REVOKE, self::PROFILE_DUPLICATE_RESOLVE => AuthenticationAssuranceLevel::PHISHING_RESISTANT,
            self::QURAN_RELEASE_APPROVE, self::QURAN_RELEASE_ACTIVATE, self::QURAN_RELEASE_REJECT,
            self::QURAN_SEARCH_CORPUS_VALIDATE,
            self::COMPETITION_PROGRAM_ACTIVATE, self::COMPETITION_EDITION_PUBLISH,
            self::COMPETITION_REGISTRATION_OPEN, self::COMPETITION_REGISTRATION_CLOSE,
            self::COMPETITION_REGISTRATION_REOPEN, self::COMPETITION_EDITION_CANCEL,
            self::COMPETITION_ROSTER_FINALIZE,
            self::COMPETITION_RUBRIC_ACTIVATE, self::COMPETITION_SCORING_OPEN,
            self::COMPETITION_SCORING_CLOSE, self::COMPETITION_SCORE_CORRECT,
            self::COMPETITION_RESULT_VERIFY, self::COMPETITION_RESULT_PUBLISH,
            self::COMPETITION_RESULT_VOID, self::COMPETITION_PARTICIPANT_DISQUALIFY,
            self::COMPETITION_APPEAL_UPHOLD, self::COMPETITION_APPEAL_DISMISS,
            self::COMPETITION_LIVE_SESSION_CLOSE, self::COMPETITION_LIVE_SESSION_CANCEL => AuthenticationAssuranceLevel::PHISHING_RESISTANT,
            self::ACCOUNT_SUSPEND, self::ACCOUNT_REACTIVATE => AuthenticationAssuranceLevel::PHISHING_RESISTANT,
            default => AuthenticationAssuranceLevel::MULTI_FACTOR,
        };
    }

    public function continuation(): string
    {
        return match ($this) {
            self::MFA_ENROLL_TOTP => '/account/security/mfa/totp/enroll',
            self::MFA_REGISTER_PASSKEY => '/account/security/passkeys/register',
            self::MFA_DISABLE => '/account/security/mfa/disable',
            self::TEMPORARY_PRIVILEGE_APPROVE,
            self::TEMPORARY_PRIVILEGE_ACTIVATE,
            self::TEMPORARY_PRIVILEGE_REVOKE,
            self::SUPPORT_ACCESS_PLATFORM_APPROVE,
            self::SUPPORT_ACCESS_WORKSPACE_APPROVE,
            self::SUPPORT_ACCESS_ACTIVATE,
            self::SUPPORT_ACCESS_REVOKE,
            self::SUPPORT_ACCESS_REVIEW,
            self::BREAK_GLASS_ACTIVATE,
            self::BREAK_GLASS_REVIEW => '/account/security/privileged-access',
            self::ACCOUNT_SUSPEND, self::ACCOUNT_REACTIVATE => '/platform/security/accounts',
            self::PERSON_PROFILE_SENSITIVE_UPDATE,
            self::DEPENDENT_PROFILE_CREATE,
            self::GUARDIANSHIP_REVOKE => '/account/profile',
            self::ORGANIZATION_RETIRE,
            self::ORGANIZATION_UNIT_RETIRE,
            self::ORGANIZATION_AFFILIATION_SUSPEND,
            self::ORGANIZATION_AFFILIATION_RESUME,
            self::ORGANIZATION_AFFILIATION_END,
            self::ORGANIZATION_LEADERSHIP_ASSIGN,
            self::ORGANIZATION_LEADERSHIP_REMOVE => '/workspace/organizations',
            self::ORGANIZATION_AFFILIATION_ACCEPT,
            self::ORGANIZATION_AFFILIATION_ACCEPT_LEADERSHIP,
            self::ORGANIZATION_AFFILIATION_LEAVE => '/account/affiliations',
            self::PROFILE_CLAIM_AUTHORIZE_GUARDIAN,
            self::PROFILE_CLAIM_ACCEPT,
            self::PROFILE_CLAIM_REVOKE,
            self::PROFILE_DUPLICATE_REPORT,
            self::PROFILE_DUPLICATE_CONSENT => '/account/profile/claims',
            self::PROFILE_CLAIM_AUTHORIZE_PLATFORM,
            self::PROFILE_VERIFICATION_RECORD,
            self::PROFILE_VERIFICATION_REVOKE,
            self::PROFILE_DUPLICATE_DISMISS,
            self::PROFILE_DUPLICATE_RESOLVE => '/platform/people/profile-claims',
            self::QURAN_RELEASE_APPROVE,
            self::QURAN_RELEASE_ACTIVATE,
            self::QURAN_RELEASE_REJECT,
            self::QURAN_SEARCH_CORPUS_VALIDATE => '/platform/quran/releases',
            self::COMPETITION_PROGRAM_ACTIVATE,
            self::COMPETITION_EDITION_PUBLISH,
            self::COMPETITION_REGISTRATION_OPEN,
            self::COMPETITION_REGISTRATION_CLOSE,
            self::COMPETITION_REGISTRATION_REOPEN,
            self::COMPETITION_EDITION_CANCEL,
            self::COMPETITION_ROSTER_FINALIZE,
            self::COMPETITION_RUBRIC_ACTIVATE, self::COMPETITION_SCORING_OPEN,
            self::COMPETITION_SCORING_CLOSE, self::COMPETITION_SCORE_CORRECT,
            self::COMPETITION_RESULT_VERIFY, self::COMPETITION_RESULT_PUBLISH,
            self::COMPETITION_RESULT_VOID, self::COMPETITION_PARTICIPANT_DISQUALIFY,
            self::COMPETITION_APPEAL_UPHOLD, self::COMPETITION_APPEAL_DISMISS,
            self::COMPETITION_LIVE_SESSION_CLOSE, self::COMPETITION_LIVE_SESSION_CANCEL => '/workspace/competitions',
            default => '/account/security/authentication',
        };
    }
}
