<?php

declare(strict_types=1);

namespace Qmdb\Modules\IdentityMultiFactor\Domain;

enum StepUpAction: string
{
    case MFA_ENROLL_TOTP = 'MFA_ENROLL_TOTP';
    case MFA_REGISTER_PASSKEY = 'MFA_REGISTER_PASSKEY';
    case MFA_ENABLE = 'MFA_ENABLE';
    case MFA_DISABLE = 'MFA_DISABLE';
    case MFA_REGENERATE_RECOVERY_CODES = 'MFA_REGENERATE_RECOVERY_CODES';
    case MFA_REVOKE_TOTP = 'MFA_REVOKE_TOTP';
    case MFA_REVOKE_PASSKEY = 'MFA_REVOKE_PASSKEY';
    case AUTHORIZATION_PLATFORM_ROLE_ASSIGN = 'AUTHORIZATION_PLATFORM_ROLE_ASSIGN';
    case AUTHORIZATION_PLATFORM_ROLE_REVOKE = 'AUTHORIZATION_PLATFORM_ROLE_REVOKE';
    case AUTHORIZATION_WORKSPACE_ROLE_ASSIGN = 'AUTHORIZATION_WORKSPACE_ROLE_ASSIGN';
    case AUTHORIZATION_WORKSPACE_ROLE_REVOKE = 'AUTHORIZATION_WORKSPACE_ROLE_REVOKE';
    case TEMPORARY_PRIVILEGE_APPROVE = 'TEMPORARY_PRIVILEGE_APPROVE';
    case TEMPORARY_PRIVILEGE_ACTIVATE = 'TEMPORARY_PRIVILEGE_ACTIVATE';
    case TEMPORARY_PRIVILEGE_REVOKE = 'TEMPORARY_PRIVILEGE_REVOKE';
    case SUPPORT_ACCESS_PLATFORM_APPROVE = 'SUPPORT_ACCESS_PLATFORM_APPROVE';
    case SUPPORT_ACCESS_WORKSPACE_APPROVE = 'SUPPORT_ACCESS_WORKSPACE_APPROVE';
    case SUPPORT_ACCESS_ACTIVATE = 'SUPPORT_ACCESS_ACTIVATE';
    case SUPPORT_ACCESS_REVOKE = 'SUPPORT_ACCESS_REVOKE';
    case SUPPORT_ACCESS_REVIEW = 'SUPPORT_ACCESS_REVIEW';
    case BREAK_GLASS_ACTIVATE = 'BREAK_GLASS_ACTIVATE';
    case BREAK_GLASS_REVIEW = 'BREAK_GLASS_REVIEW';
    case ACCOUNT_SUSPEND = 'ACCOUNT_SUSPEND';
    case ACCOUNT_REACTIVATE = 'ACCOUNT_REACTIVATE';
    case PERSON_PROFILE_SENSITIVE_UPDATE = 'PERSON_PROFILE_SENSITIVE_UPDATE';
    case DEPENDENT_PROFILE_CREATE = 'DEPENDENT_PROFILE_CREATE';
    case GUARDIANSHIP_REVOKE = 'GUARDIANSHIP_REVOKE';
    case ORGANIZATION_RETIRE = 'ORGANIZATION_RETIRE';
    case ORGANIZATION_UNIT_RETIRE = 'ORGANIZATION_UNIT_RETIRE';
    case ORGANIZATION_AFFILIATION_ACCEPT = 'ORGANIZATION_AFFILIATION_ACCEPT';
    case ORGANIZATION_AFFILIATION_ACCEPT_LEADERSHIP = 'ORGANIZATION_AFFILIATION_ACCEPT_LEADERSHIP';
    case ORGANIZATION_AFFILIATION_SUSPEND = 'ORGANIZATION_AFFILIATION_SUSPEND';
    case ORGANIZATION_AFFILIATION_RESUME = 'ORGANIZATION_AFFILIATION_RESUME';
    case ORGANIZATION_AFFILIATION_END = 'ORGANIZATION_AFFILIATION_END';
    case ORGANIZATION_AFFILIATION_LEAVE = 'ORGANIZATION_AFFILIATION_LEAVE';
    case ORGANIZATION_LEADERSHIP_ASSIGN = 'ORGANIZATION_LEADERSHIP_ASSIGN';
    case ORGANIZATION_LEADERSHIP_REMOVE = 'ORGANIZATION_LEADERSHIP_REMOVE';

    public function requirement(): AuthenticationAssuranceLevel
    {
        return match ($this) {
            self::MFA_ENROLL_TOTP, self::MFA_REGISTER_PASSKEY, self::ORGANIZATION_AFFILIATION_ACCEPT, self::ORGANIZATION_AFFILIATION_LEAVE => AuthenticationAssuranceLevel::PRIMARY,
            self::AUTHORIZATION_PLATFORM_ROLE_ASSIGN,
            self::AUTHORIZATION_PLATFORM_ROLE_REVOKE,
            self::SUPPORT_ACCESS_PLATFORM_APPROVE,
            self::SUPPORT_ACCESS_WORKSPACE_APPROVE,
            self::SUPPORT_ACCESS_ACTIVATE,
            self::SUPPORT_ACCESS_REVOKE,
            self::SUPPORT_ACCESS_REVIEW,
            self::BREAK_GLASS_ACTIVATE,
            self::BREAK_GLASS_REVIEW, self::ORGANIZATION_LEADERSHIP_ASSIGN, self::ORGANIZATION_LEADERSHIP_REMOVE => AuthenticationAssuranceLevel::PHISHING_RESISTANT,
            self::ACCOUNT_SUSPEND, self::ACCOUNT_REACTIVATE => AuthenticationAssuranceLevel::PHISHING_RESISTANT,
            default => AuthenticationAssuranceLevel::MULTI_FACTOR,
        };
    }

    public function continuation(): string
    {
        return match ($this) {
            self::MFA_ENROLL_TOTP => '/account/security/mfa/totp/enroll',
            self::MFA_REGISTER_PASSKEY => '/account/security/passkeys/register',
            self::MFA_DISABLE => '/account/security/mfa/disable',
            self::TEMPORARY_PRIVILEGE_APPROVE,
            self::TEMPORARY_PRIVILEGE_ACTIVATE,
            self::TEMPORARY_PRIVILEGE_REVOKE,
            self::SUPPORT_ACCESS_PLATFORM_APPROVE,
            self::SUPPORT_ACCESS_WORKSPACE_APPROVE,
            self::SUPPORT_ACCESS_ACTIVATE,
            self::SUPPORT_ACCESS_REVOKE,
            self::SUPPORT_ACCESS_REVIEW,
            self::BREAK_GLASS_ACTIVATE,
            self::BREAK_GLASS_REVIEW => '/account/security/privileged-access',
            self::ACCOUNT_SUSPEND, self::ACCOUNT_REACTIVATE => '/platform/security/accounts',
            self::PERSON_PROFILE_SENSITIVE_UPDATE,
            self::DEPENDENT_PROFILE_CREATE,
            self::GUARDIANSHIP_REVOKE => '/account/profile',
            self::ORGANIZATION_RETIRE,
            self::ORGANIZATION_UNIT_RETIRE,
            self::ORGANIZATION_AFFILIATION_SUSPEND,
            self::ORGANIZATION_AFFILIATION_RESUME,
            self::ORGANIZATION_AFFILIATION_END,
            self::ORGANIZATION_LEADERSHIP_ASSIGN,
            self::ORGANIZATION_LEADERSHIP_REMOVE => '/workspace/organizations',
            self::ORGANIZATION_AFFILIATION_ACCEPT,
            self::ORGANIZATION_AFFILIATION_ACCEPT_LEADERSHIP,
            self::ORGANIZATION_AFFILIATION_LEAVE => '/account/affiliations',
            default => '/account/security/authentication',
        };
    }
}
